import { getPublishedMarketingStrategy } from "@/lib/marketing/strategy";
import { EmptyState, PageHeader, Section } from "../../components/os-primitives";

export const dynamic = "force-dynamic";

export default async function StrategyPage({ params }: { params: Promise<{ brandSlug: string }> }) {
  const { brandSlug } = await params; const strategy = await getPublishedMarketingStrategy(brandSlug);
  if (!strategy) return <div className="space-y-6"><PageHeader eyebrow="MARKETING · ESTRATEGIA" title="Estrategia de marketing" description="La dirección publicada para este periodo." /><EmptyState status="Sin estrategia publicada" title="Tu estrategia aparecerá aquí" description="Cuando tu equipo publique una estrategia podrás consultar objetivos, audiencia y prioridades." source="Estrategia" /></div>;
  const label = new Intl.DateTimeFormat("es-MX", { month: "long", year: "numeric" }).format(new Date(strategy.periodYear, strategy.periodMonth - 1, 15));
  return <div className="space-y-6"><PageHeader eyebrow={`ESTRATEGIA · ${label.toUpperCase()}`} title="Estrategia de marketing" description="La dirección publicada para convertir prioridades en ejecución." /><section className="os-card-primary"><p className="text-xs font-semibold uppercase tracking-wider text-violet-700">Versión {strategy.version}</p><h2 className="mt-3 text-2xl font-semibold">{strategy.objectivePrimary || "Objetivo del periodo"}</h2></section><Section title="Dirección"><div className="grid gap-4 md:grid-cols-2"><Field label="Objetivos secundarios" value={strategy.objectivesSecondary} /><Field label="Público" value={strategy.targetAudience} /><Field label="Enfoque estratégico" value={strategy.strategicFocus} /><Field label="Oferta prioritaria" value={strategy.offerFocus} /></div></Section><Section title="Contenido"><div className="grid gap-4 md:grid-cols-2"><Field label="Pilares" value={strategy.contentPillars} /><Field label="Canales" value={strategy.channels} /><Field label="Frecuencia" value={strategy.cadence} /><Field label="Tono" value={strategy.tone} /></div></Section><Section title="Campañas y éxito"><div className="grid gap-4 md:grid-cols-2"><Field label="Campañas / prioridades" value={strategy.campaigns} /><Field label="CTA principal" value={strategy.primaryCta} /><Field label="Qué vamos a medir" value={strategy.successMetrics} /><Field label="Próximo hito" value={strategy.nextMilestone} /></div></Section></div>;
}
function Field({ label, value }: { label: string; value: unknown }) { const text = Array.isArray(value) ? value.filter(Boolean).join(" · ") : typeof value === "string" ? value : ""; return text ? <div className="os-card-subtle"><p className="os-label">{label}</p><p className="mt-2 text-sm leading-6">{text}</p></div> : null; }
