"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CONTENT_GROUP_LABELS, contentTypeLabel, dateLabel, deliveryLabel, distributionLabel, periodLabel, type ContentGroup, type WorkspaceContentItem } from "@/lib/workspace/content-presentation";

type Data = { period: { month: number; year: number }; items: WorkspaceContentItem[]; brands: Array<{ slug: string; name: string }>; assignees: Array<{ id: string; name: string }>; counts: Record<ContentGroup, number> };
const groups: ContentGroup[] = ["planned", "production", "review", "changes", "client", "scheduled", "published", "cancelled"];

export function ContentClient({ data }: { data: Data }) {
  const router = useRouter(); const [brand, setBrand] = useState(""); const [group, setGroup] = useState(""); const [distribution, setDistribution] = useState(""); const [assignee, setAssignee] = useState(""); const [contentType, setContentType] = useState(""); const [search, setSearch] = useState(""); const [grouping, setGrouping] = useState<"status" | "brand">("status");
  const items = useMemo(() => { const query = search.trim().toLocaleLowerCase("es"); return data.items.filter((item) => (!brand || item.brandSlug === brand) && (!group || item.group === group) && (!distribution || item.distributionType === distribution) && (!assignee || item.assignedTo === assignee) && (!contentType || item.contentType === contentType) && (!query || `${item.title} ${item.brandName}`.toLocaleLowerCase("es").includes(query))); }, [data.items, brand, group, distribution, assignee, contentType, search]);
  const sections = useMemo(() => { const map = new Map<string, WorkspaceContentItem[]>(); for (const item of items) { const key = grouping === "status" ? item.group : item.brandName; map.set(key, [...(map.get(key) || []), item]); } return [...map.entries()]; }, [items, grouping]);
  function setPeriod(month: number, year: number) { const normalized = new Date(year, month - 1, 1); router.push(`/workspace/content?month=${normalized.getMonth() + 1}&year=${normalized.getFullYear()}`); }
  return <main className="space-y-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-cyan-300">Torre de control</p><h1 className="mt-2 text-3xl font-semibold">CONTENIDO</h1><p className="mt-2 text-sm text-slate-400">Control global de la producción de todas las marcas.</p></div><div className="flex items-center gap-2 rounded-xl border border-white/10 p-1"><button onClick={() => setPeriod(data.period.month - 1, data.period.year)} className="px-3 py-2 text-slate-400">←</button><span className="min-w-36 text-center text-sm font-medium">{periodLabel(data.period.month, data.period.year)}</span><button onClick={() => setPeriod(data.period.month + 1, data.period.year)} className="px-3 py-2 text-slate-400">→</button></div></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{groups.filter((x) => x !== "cancelled").map((key) => <div key={key} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">{CONTENT_GROUP_LABELS[key]}</p><p className="mt-2 text-2xl font-semibold">{data.counts[key]}</p></div>)}</section>
    <section className="flex flex-wrap gap-2"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar título o marca" className="min-w-52 rounded-xl border border-white/10 bg-[#0b192a] px-3 py-2 text-xs outline-none focus:border-cyan-300/50" /><Select value={brand} onChange={setBrand} label="Marca" options={data.brands.map((x) => [x.slug, x.name])} /><Select value={group} onChange={setGroup} label="Estado" options={groups.map((x) => [x, CONTENT_GROUP_LABELS[x]])} /><Select value={distribution} onChange={setDistribution} label="Orgánico / Pauta" options={[["organic", "Orgánico"], ["paid", "Pauta"]]} /><Select value={assignee} onChange={setAssignee} label="Responsable" options={data.assignees.map((x) => [x.id, x.name])} /><Select value={contentType} onChange={setContentType} label="Tipo" options={[["reel", "Reel"], ["post", "Post"], ["story", "Story"], ["carousel", "Carrusel"]]} /><div className="ml-auto flex rounded-xl border border-white/10 p-1"><button onClick={() => setGrouping("status")} className={`rounded-lg px-3 py-1 text-xs ${grouping === "status" ? "bg-white/10 text-white" : "text-slate-500"}`}>Por estado</button><button onClick={() => setGrouping("brand")} className={`rounded-lg px-3 py-1 text-xs ${grouping === "brand" ? "bg-white/10 text-white" : "text-slate-500"}`}>Por marca</button></div></section>
    {sections.length === 0 ? <div className="rounded-3xl border border-dashed border-white/10 p-12 text-center text-sm text-slate-400">No hay contenido en este periodo con los filtros elegidos.</div> : sections.map(([key, values]) => <section key={key}><div className="mb-3 flex items-center gap-3"><h2 className="text-sm font-semibold uppercase tracking-[.16em] text-slate-300">{grouping === "status" ? CONTENT_GROUP_LABELS[key as ContentGroup] : key}</h2><span className="text-xs text-slate-600">{values.length}</span></div><div className="grid gap-3 xl:grid-cols-2">{values.map((item) => <article key={item.id} className="grid grid-cols-[92px_1fr] gap-4 rounded-2xl border border-white/10 bg-[#0b192a] p-3"><Preview item={item} /><div className="min-w-0"><div className="flex flex-wrap gap-2 text-[10px] uppercase tracking-wider text-cyan-200"><span>{item.brandName}</span><span>{contentTypeLabel(item.contentType)}</span><span>{distributionLabel(item.distributionType)}</span>{item.deliveryType && item.deliveryType !== "contractual" && <span className="text-violet-200">{deliveryLabel(item.deliveryType)}</span>}</div><h3 className="mt-2 truncate font-medium">{item.title}</h3><p className="mt-2 text-xs text-slate-400">{item.assigneeName || "Sin responsable"} · {item.distributionType === "paid" ? "Activación prevista" : "Publicación"}: {dateLabel(item.publishDate || item.dueDate)}</p><div className="mt-3 flex items-center justify-between"><span className="text-xs font-medium text-slate-300">{item.statusLabel}</span><Link href={`/workspace/brands/${encodeURIComponent(item.brandSlug)}/calendar?month=${data.period.month}&year=${data.period.year}&item=${encodeURIComponent(item.id)}`} className="text-xs font-semibold text-cyan-300 hover:text-cyan-200">Abrir pieza →</Link></div></div></article>)}</div></section>)}
  </main>;
}
function Select({ value, onChange, label, options }: { value: string; onChange: (value: string) => void; label: string; options: string[][] }) { return <select value={value} onChange={(event) => onChange(event.target.value)} className="rounded-xl border border-white/10 bg-[#0b192a] px-3 py-2 text-xs text-slate-300"><option value="">{label}</option>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select>; }
function Preview({ item }: { item: WorkspaceContentItem }) { return item.thumbnailUrl ? <img src={item.thumbnailUrl} alt="" className="h-24 w-[92px] rounded-xl object-cover" /> : <div className="grid h-24 w-[92px] place-items-center rounded-xl bg-gradient-to-br from-cyan-300/15 to-blue-500/10 text-[10px] font-semibold uppercase text-cyan-200">{contentTypeLabel(item.contentType)}</div>; }
