import Link from "next/link";
import { notFound } from "next/navigation";
import { getStudioPieceChangeContext, type StudioCurrentDeliverable } from "@/lib/studio/changes";
import { requireStudioAccess, requireStudioBrandAccess, getStudioPiece } from "@/lib/studio/server";
import { getProductionCapabilities } from "@/lib/studio/production";
import { studioStatusLabels, distributionLabel } from "@/lib/studio/dashboard";
import { WorkflowActions } from "./workflow-actions";

export const dynamic = "force-dynamic";

export default async function PiecePage({ params }: { params: Promise<{ pieceId: string }> }) {
  const studio = await requireStudioAccess(); const { pieceId } = await params; const piece = await getStudioPiece(studio, pieceId); if (!piece) notFound();
  const access = await requireStudioBrandAccess(String(piece.brand_slug));
  const [caps, changeContext] = await Promise.all([getProductionCapabilities(access.brand.slug), piece.status === "changes_requested" ? getStudioPieceChangeContext(studio.userId, pieceId, access.brand.slug) : Promise.resolve(null)]);
  return <main className="min-h-screen bg-[#07111f] p-6 text-white sm:p-10"><Link href={piece.status === "changes_requested" ? "/studio/changes" : "/studio"} className="text-sm text-cyan-300">← {piece.status === "changes_requested" ? "Cambios" : "Studio"}</Link><div className="mt-8 max-w-5xl"><p className="text-xs uppercase tracking-wider text-cyan-300">{typeLabel(String(piece.content_type))} · {distributionLabel(piece.distribution_type)} · {piece.distribution_type === "paid" ? "Activación prevista" : "Publicación"} {formatDate(piece.publish_date || piece.due_date)}</p><h1 className="mt-3 text-3xl font-semibold">{String(piece.title || "Sin título")}</h1><p className="mt-2 text-slate-400">{access.brand.name} · {studioStatusLabels[String(piece.status)] || "Pieza"}</p>
    {changeContext && <><section className={`mt-8 rounded-3xl border p-6 ${changeContext.change.source === "client" ? "border-fuchsia-300/25 bg-fuchsia-300/[.055]" : "border-amber-300/25 bg-amber-300/[.05]"}`}><p className={`text-xs font-semibold uppercase tracking-[.2em] ${changeContext.change.source === "client" ? "text-fuchsia-200" : "text-amber-200"}`}>CAMBIOS SOLICITADOS</p><p className="mt-3 text-sm text-slate-400">{changeContext.change.requestedByLabel} · {formatDateTime(changeContext.change.requestedAt)}</p><p className="mt-4 whitespace-pre-wrap text-base leading-7 text-white">“{changeContext.change.message}”</p></section><Deliverable asset={changeContext.deliverable} title={String(piece.title || "pieza")} /><WorkflowActions pieceId={String(piece.id)} status={String(piece.status)} /></>}
    <section className="mt-8"><p className="text-xs uppercase tracking-[.2em] text-slate-500">INFORMACIÓN DE PIEZA</p><div className="mt-4 grid gap-4 md:grid-cols-2"><Info label="Objetivo" value={piece.objective} /><Info label="Brief" value={piece.brief} /><Info label="CTA" value={piece.cta} /><Info label="Dirección visual" value={piece.visual_direction} /></div></section>
    <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs uppercase tracking-wider text-violet-200">REFERENCIAS</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-300">{String(piece.reference_notes || "No hay referencias adicionales para esta pieza.")}</p></section>
    {!changeContext && <WorkflowActions pieceId={String(piece.id)} status={String(piece.status)} />}
    <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs uppercase tracking-wider text-cyan-300">PRODUCTION CAPABILITIES</p><p className="mt-3 text-sm text-slate-300">Modelo Cometa {caps.canUseAgencyModel ? "autorizada ✓" : "no confirmado"} · Manos {caps.canUseHands ? "✓" : "–"} · Producto solo {caps.canUseProductOnly ? "✓" : "–"}</p></section>
  </div></main>;
}
function Deliverable({ asset, title }: { asset: StudioCurrentDeliverable | null; title: string }) { return <section className="mt-6 rounded-3xl border border-cyan-300/20 bg-white/[.035] p-5"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-200">ENTREGABLE ACTUAL</p>{asset ? <div className="mt-4 grid gap-5 md:grid-cols-[minmax(0,360px)_1fr]">{asset.url && isImage(asset.mimeType, asset.url) ? <img src={asset.url} alt={`Entregable actual de ${title}`} className="max-h-[420px] w-full rounded-2xl bg-black/20 object-contain" /> : <div className="grid min-h-48 place-items-center rounded-2xl border border-white/10 bg-gradient-to-br from-cyan-300/[.1] to-violet-300/[.08] text-sm text-cyan-200">{asset.type === "video" ? "Video disponible" : "Archivo disponible"}</div>}<div><p className="font-medium text-white">{asset.name || "Entregable de producción"}</p><p className="mt-2 text-xs uppercase tracking-wider text-slate-500">{providerLabel(asset.provider)} · {asset.type || "Asset"}</p><p className="mt-2 text-xs text-slate-400">Cargado {formatDateTime(asset.createdAt)}</p>{asset.url && <a href={asset.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-xl border border-cyan-300/30 px-4 py-2 text-sm font-semibold text-cyan-200">Ver entregable seguro ↗</a>}</div></div> : <p className="mt-4 text-sm text-slate-400">No hay un asset visual disponible. Revisa la información de la pieza antes de preparar la corrección.</p>}</section>; }
function Info({ label, value }: { label: string; value: unknown }) { return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-200">{String(value || "Sin información")}</p></div>; }
function isImage(mime: string | null, url: string) { return mime?.startsWith("image/") || /\.(png|jpe?g|webp|gif)(?:\?|$)/i.test(url); }
function providerLabel(provider: string | null) { return provider === "supabase" ? "Cometa Drive" : provider === "canva" ? "Canva" : provider === "drive" ? "Google Drive" : provider || "Archivo"; }
function typeLabel(value: string) { return ({ reel: "Reel", story: "Story", carousel: "Carrusel", post: "Post", static_post: "Post" } as Record<string, string>)[value] || "Contenido"; }
function formatDate(value: unknown) { const date = typeof value === "string" ? value : null; return date ? new Intl.DateTimeFormat("es-MX", { day: "numeric", month: "short", timeZone: "UTC" }).format(new Date(`${date.slice(0, 10)}T12:00:00Z`)) : "sin fecha"; }
function formatDateTime(value: string | null) { return value ? new Intl.DateTimeFormat("es-MX", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit", timeZone: "America/Mexico_City" }).format(new Date(value)) : "fecha no disponible"; }
