import "server-only";
import { createClient } from "@supabase/supabase-js";
import { requireAdminWorkspace } from "@/lib/workspace/admin-brands";
import { normalizeMarketingChannels } from "@/lib/marketing/channels";

const CONTEXT_KEYS = ["average_ticket", "commercial_objective", "priority_offer", "sales_model", "priority_market", "ad_budget", "upcoming_promotions", "target_audience", "channels", "optional_constraints"] as const;
const STATES = new Set(["verified", "confirmed", "inference", "unknown"]);
function db() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE; if (!url || !key) throw new Error("Missing Supabase server configuration"); return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); }
async function brand(slug: string) { const client = db(); const { data, error } = await client.from("brands").select("id,slug,name").eq("slug", slug).maybeSingle(); if (error) throw error; if (!data) throw new Error("BRAND_NOT_FOUND"); return { client, brand: data as { id: string; slug: string; name: string } }; }
function sanitizeClaims(input: unknown) { const source = input && typeof input === "object" ? input as Record<string, unknown> : {}; const result: Record<string, unknown> = {}; for (const key of CONTEXT_KEYS) { const claim = source[key]; if (!claim || typeof claim !== "object" || Array.isArray(claim)) continue; const row = claim as Record<string, unknown>; const state = String(row.state || "unknown"); if (!STATES.has(state)) throw new Error("INVALID_CONTEXT_STATE"); const value = key === "channels" ? normalizeMarketingChannels(row.value) : row.value ?? null; result[key] = { value, state }; } return result; }
export async function getStrategicOnboarding(slug: string) { await requireAdminWorkspace(); const { client, brand: b } = await brand(slug); const [diagnoses, context, evidence, packages, assignment] = await Promise.all([client.from("cometa_brand_diagnoses").select("id,brand_id,brand_slug,legacy_analysis_id,status,requested_by,started_at,completed_at,created_at,updated_at").eq("brand_id", b.id).order("created_at", { ascending: false }).limit(10), client.from("cometa_brand_context").select("brand_id,brand_slug,latest_diagnosis_id,context_claims,updated_by,created_at,updated_at").eq("brand_id", b.id).maybeSingle(), client.from("orion_evidence").select("id,source_type,source_url,source_name,evidence_status,collection_method,evidence_summary,confidence_score,visual_signals,ai_observations,created_at").eq("brand_name", b.name).order("created_at", { ascending: false }).limit(50), client.from("cometa_marketing_packages").select("code,name,organic_reels_per_week,organic_posts_per_week,organic_stories_per_week,paid_base_reels,paid_base_carousels,paid_base_posts,paid_review_interval_days").eq("active", true).order("code"), client.from("cometa_brand_marketing_packages").select("id,package_code,package_snapshot,effective_from,effective_to,confirmed_by").eq("brand_id", b.id).is("effective_to", null).maybeSingle()]); for (const result of [diagnoses, context, evidence, packages, assignment]) if (result.error) throw result.error; const claims = context.data?.context_claims || {}; const checks = { business_understood: Boolean((claims as Record<string, unknown>).priority_offer || (evidence.data || []).length), commercial_objective_confirmed: hasState(claims, "commercial_objective", ["confirmed", "verified"]), priority_offer_confirmed: hasState(claims, "priority_offer", ["confirmed", "verified"]), audience_context_sufficient: hasState(claims, "target_audience", ["confirmed", "verified"]) || hasState(claims, "priority_market", ["confirmed", "verified"]), channels_identified: hasState(claims, "channels", ["confirmed", "verified"]), marketing_package_assigned: Boolean(assignment.data) }; const missing = Object.entries(checks).filter(([, ok]) => !ok).map(([key]) => key); return { brand: b, diagnoses: diagnoses.data || [], context: context.data, evidence: evidence.data || [], packages: packages.data || [], assignment: assignment.data, readiness: { ready: missing.length === 0, checks, missing } }; }
function hasState(claims: unknown, key: string, states: string[]) { const row = claims && typeof claims === "object" ? (claims as Record<string, unknown>)[key] : null; return Boolean(row && typeof row === "object" && states.includes(String((row as Record<string, unknown>).state))); }
export async function saveContext(slug: string, input: unknown) { const actor = await requireAdminWorkspace(); const { client, brand: b } = await brand(slug); const claims = sanitizeClaims(input); const { data, error } = await client.from("cometa_brand_context").upsert({ brand_id: b.id, brand_slug: b.slug, context_claims: claims, updated_by: actor.userId, updated_at: new Date().toISOString() }, { onConflict: "brand_id" }).select().single(); if (error) throw error; return data; }
export async function assignPackage(slug: string, code: string) { const actor = await requireAdminWorkspace(); const { client, brand: b } = await brand(slug); const pkg = await client.from("cometa_marketing_packages").select("*").eq("code", code).eq("active", true).maybeSingle(); if (pkg.error) throw pkg.error; if (!pkg.data) throw new Error("PACKAGE_NOT_FOUND"); await client.from("cometa_brand_marketing_packages").update({ effective_to: new Date().toISOString().slice(0, 10), updated_at: new Date().toISOString() }).eq("brand_id", b.id).is("effective_to", null); const { data, error } = await client.from("cometa_brand_marketing_packages").insert({ brand_id: b.id, brand_slug: b.slug, package_code: pkg.data.code, package_snapshot: pkg.data, effective_from: new Date().toISOString().slice(0, 10), confirmed_by: actor.userId }).select().single(); if (error) throw error; return data; }
export async function startDiagnosis(slug: string, sources: Record<string, unknown>) { const actor = await requireAdminWorkspace(); const { client, brand: b } = await brand(slug); const diagnosis = await client.from("cometa_brand_diagnoses").insert({ brand_id: b.id, brand_slug: b.slug, status: "collecting", requested_by: actor.userId, started_at: new Date().toISOString() }).select().single(); if (diagnosis.error) throw diagnosis.error; const analysis = await client.from("brand_analysis").insert({ brand_name: b.name, brand_slug: b.slug, industry: sources.industry || null, city: sources.city || null, instagram: sources.instagram || null, facebook: sources.facebook || null, tiktok: sources.tiktok || null, website: sources.website || null, competitors: sources.competitors || null, objective: sources.objective || null, budget: sources.budget || null, problem: sources.problem || null, analysis: null }).select("id").single(); if (analysis.error) { await client.from("cometa_brand_diagnoses").update({ status: "failed", updated_at: new Date().toISOString() }).eq("id", diagnosis.data.id); throw analysis.error; } const updated = await client.from("cometa_brand_diagnoses").update({ legacy_analysis_id: analysis.data.id, updated_at: new Date().toISOString() }).eq("id", diagnosis.data.id).select().single(); if (updated.error) throw updated.error; return updated.data; }
export { CONTEXT_KEYS };
