"use client";
import { useEffect, useState } from "react";
import { readOfflineOutbox } from "@/lib/pos/offline-outbox";

export function PosConnectionStatus({ brandSlug }: { brandSlug: string }) {
  const [online, setOnline] = useState(true); const [pending, setPending] = useState(0); const [syncing, setSyncing] = useState(false); const [updateAvailable, setUpdateAvailable] = useState<ServiceWorkerRegistration | null>(null);
  useEffect(() => { const update = () => setOnline(navigator.onLine); update(); const onOnline = () => { setOnline(true); setSyncing(true); window.setTimeout(() => setSyncing(false), 700); }; const onOffline = () => setOnline(false); window.addEventListener("online", onOnline); window.addEventListener("offline", onOffline); void readOfflineOutbox(brandSlug).then((items) => setPending(items.filter((item) => item.status === "PENDING" || item.status === "FAILED").length)); if ("serviceWorker" in navigator) void navigator.serviceWorker.ready.then((registration) => { if (registration.waiting) setUpdateAvailable(registration); registration.addEventListener("updatefound", () => { const worker = registration.installing; worker?.addEventListener("statechange", () => { if (worker.state === "installed" && navigator.serviceWorker.controller) setUpdateAvailable(registration); }); }); }); return () => { window.removeEventListener("online", onOnline); window.removeEventListener("offline", onOffline); }; }, [brandSlug]);
  const label = !online ? "Sin conexión" : syncing ? "Sincronizando…" : pending ? "Cambios pendientes" : "Operación en vivo";
  return <div className="mt-2 flex flex-wrap items-center gap-3 text-[11px] text-[var(--pos-text-muted)]"><span role="status" aria-live="polite" className="inline-flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${!online ? "bg-amber-400" : pending ? "bg-amber-400" : "bg-emerald-400"}`} />{label}{!online ? <span>· Trabajando con los últimos datos guardados.</span> : null}</span>{updateAvailable ? <button type="button" className="underline" onClick={() => { updateAvailable.waiting?.postMessage({ type: "SKIP_WAITING" }); setUpdateAvailable(null); }}>Nueva versión disponible · Actualizar</button> : null}</div>;
}
