"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { buyerOrderStatus, buyerSections, formatMxn } from "@/lib/comu/buyer-experience";
import { EmptyState, ProductCard, type PublicListing } from "../../components/public-ui";
import { useCommerce } from "../../components/commerce";
type Address = { id: string; label: string; recipient_name: string; phone: string; line1: string; line2?: string; city: string; state: string; postal_code: string; is_default: boolean };
type Order = { id: string; order_number: string; status: string; created_at: string; grand_total: number; comu_order_suborders?: Array<{ comu_sellers?: { public_name: string } }>; comu_order_items?: Array<{ id: string; quantity: number; comu_order_item_snapshots?: Array<{ snapshot?: { listingTitle?: string } }> }> };
type Experience = { profile: { displayName: string; email: string }; favorites: string[]; foundationReady: boolean; points: Array<{ points: number; created_at: string; expires_at: string }> };
export default function BuyerAccount({ initialSection }: { initialSection?: string }) {
  const { favorites: savedIds } = useCommerce();
  const [section, setSection] = useState<string>(buyerSections.find(title => title === initialSection) || "Resumen"), [account, setAccount] = useState<Experience | null>(null), [orders, setOrders] = useState<Order[]>([]), [addresses, setAddresses] = useState<Address[]>([]), [catalog, setCatalog] = useState<PublicListing[]>([]);
  const [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<Address | null>(null); const dialog = useRef<HTMLDialogElement>(null);
  const [asOf, setAsOf] = useState(0);
  const load = useCallback(async () => {
    try {
      const responses = await Promise.all([fetch("/api/comu/buyer/experience"), fetch("/api/comu/orders"), fetch("/api/comu/buyer/addresses"), fetch("/api/comu/catalog")]);
      if (responses.some(response => response.status === 401)) { window.location.assign("/login?next=%2Fcomu%2Faccount%2Fbuyer"); return; }
      if (responses.some(response => !response.ok)) throw new Error();
      const [profile, history, delivery, products] = await Promise.all(responses.map(response => response.json()));
      setAccount(profile); setOrders(history.orders || []); setAddresses(delivery.addresses || []); setCatalog(products.listings || []); setAsOf(Date.now()); setError("");
    } catch { setError("No pudimos cargar tu cuenta. Tu información sigue guardada."); } finally { setLoading(false); }
  }, []);
  useEffect(() => { const task = setTimeout(() => void load(), 0); return () => clearTimeout(task); }, [load]);
  const favorites = catalog.filter(row => savedIds.includes(row.id));
  const mainAddress = addresses.find(row => row.is_default);
  const availablePoints = account?.points.filter(row => new Date(row.expires_at).getTime() > asOf).reduce((sum, row) => sum + row.points, 0);
  async function saveAddress(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return; setBusy(true); const form = Object.fromEntries(new FormData(event.currentTarget));
    const body = editing ? { ...form, id: editing.id } : { label: form.label, recipientName: form.recipient_name, phone: form.phone, line1: form.line1, line2: form.line2, city: form.city, state: form.state, postalCode: form.postal_code, country: "MX", isDefault: false };
    try { const response = await fetch("/api/comu/buyer/addresses", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { setNotice(data.error || "No pudimos guardar la dirección."); return; } dialog.current?.close(); setNotice("Dirección guardada"); await load(); } catch { setNotice("No pudimos guardar la dirección."); } finally { setBusy(false); }
  }
  async function addressAction(address: Address, action: "delete" | "default") {
    if (busy || (action === "delete" && !window.confirm(`¿Eliminar la dirección ${address.label}?`))) return; setBusy(true);
    try { const response = await fetch(`/api/comu/buyer/addresses${action === "delete" ? `?id=${address.id}` : ""}`, { method: action === "delete" ? "DELETE" : "PATCH", headers: { "Content-Type": "application/json" }, ...(action === "default" ? { body: JSON.stringify({ id: address.id, action }) } : {}) }); const data = await response.json(); setNotice(response.ok ? "Direcciones actualizadas" : data.error || "No pudimos actualizar la dirección."); if (response.ok) await load(); } catch { setNotice("No pudimos actualizar la dirección."); } finally { setBusy(false); }
  }
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; setBusy(true); const displayName = new FormData(event.currentTarget).get("displayName"); try { const response = await fetch("/api/comu/buyer/experience", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "profile", displayName }) }); setNotice(response.ok ? "Perfil actualizado" : "No pudimos actualizar tu perfil."); if (response.ok) await load(); } catch { setNotice("No pudimos actualizar tu perfil."); } finally { setBusy(false); } }
  function editAddress(address: Address | null) { setEditing(address); dialog.current?.showModal(); }
  return <main className="mx-auto max-w-7xl px-5 py-12 md:py-16"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="comu-eyebrow">Mi COMU</p><h1 className="comu-title mt-4">Hola{account?.profile.displayName ? `, ${account.profile.displayName}` : ""}.</h1></div><Link href="/comu/account" className="text-sm underline underline-offset-4">Cambiar a vendedor</Link></div><div className="mt-12 grid gap-10 md:grid-cols-[190px_1fr]"><nav aria-label="Mi cuenta" className="flex gap-2 overflow-auto pb-3 md:block md:space-y-2">{buyerSections.map(title => <button key={title} aria-current={section === title ? "page" : undefined} onClick={() => { setSection(title); setNotice(""); }} className={`shrink-0 rounded-full px-4 py-3 text-left text-sm md:block md:w-full ${section === title ? "bg-[#252d28] text-white" : "text-[#72675e] hover:bg-[#eee7de]"}`}>{title}</button>)}</nav><div className="min-w-0"><h2 className="mb-8 text-3xl font-semibold tracking-tight">{section}</h2>{loading ? <p role="status">Preparando tu espacio…</p> : error ? <div role="alert"><p>{error}</p><button onClick={() => void load()} className="comu-button mt-4">Reintentar</button></div> : <>
      {section === "Resumen" && <div className="space-y-10"><section><h3 className="mb-4 text-lg font-semibold">Tus últimas compras</h3><OrderList orders={orders.slice(0, 2)} /></section><div className="grid gap-8 border-t border-[#d9cfc4] pt-8 sm:grid-cols-2"><section><h3 className="font-semibold">Tu dirección principal</h3><p className="mt-3 text-sm leading-7 text-[#72675e]">{mainAddress ? `${mainAddress.line1}, ${mainAddress.city}` : "Aún no has elegido una dirección principal."}</p><button className="mt-4 text-sm underline" onClick={() => setSection("Direcciones")}>Ver direcciones</button></section><section><h3 className="font-semibold">Tus recompensas</h3><p className="mt-3 text-sm text-[#72675e]">{account?.foundationReady ? `${availablePoints} puntos disponibles` : "Tu próxima historia con COMU comienza aquí."}</p><button className="mt-4 text-sm underline" onClick={() => setSection("Puntos y recompensas")}>Ver puntos</button></section></div><section><h3 className="mb-4 text-lg font-semibold">Piezas que te gustan</h3>{favorites.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{favorites.slice(0, 3).map(listing => <ProductCard key={listing.id} listing={listing} />)}</div> : <p className="text-sm text-[#72675e]">Tu selección de favoritos aparecerá aquí.</p>}</section><section className="border-t border-[#d9cfc4] pt-6"><h3 className="font-semibold">Método de pago principal</h3><p className="mt-3 text-sm text-[#72675e]">No hay un método guardado para mostrar.</p></section></div>}
      {section === "Pedidos" && <OrderList orders={orders} />}
      {section === "Favoritos" && (favorites.length ? <div className="grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3">{favorites.map(listing => <ProductCard key={listing.id} listing={listing} />)}</div> : <EmptyState title="Un lugar para tus próximas piezas favoritas." body={account?.foundationReady ? "Guarda lo que te guste mientras exploras. Lo encontrarás aquí." : "Estamos preparando tus favoritos. Por ahora, descubre la selección de COMU."} />)}
      {section === "Métodos de pago" && <><EmptyState title="Tus métodos de pago, en un solo lugar." body="Pronto podrás guardar un método de pago de forma segura. No necesitas agregar una tarjeta ahora." /><p className="mt-6 max-w-lg text-sm leading-7 text-[#72675e]">Cuando esté disponible, aquí verás únicamente la marca, los últimos cuatro dígitos y el vencimiento. COMU no guarda el número completo de tu tarjeta ni su código de seguridad.</p></>}
      {section === "Direcciones" && <><button onClick={() => editAddress(null)} className="comu-button mb-7">Agregar dirección</button>{addresses.length ? <div className="divide-y divide-[#d9cfc4]">{addresses.map(address => <article key={address.id} className="py-6"><h3 className="font-semibold">{address.label}{address.is_default && <span className="ml-3 rounded-full bg-[#e2eadf] px-3 py-1 text-xs">Principal</span>}</h3><address className="mt-3 text-sm not-italic leading-7 text-[#72675e]">{address.recipient_name}<br />{address.line1} {address.line2}<br />{address.city}, {address.state}, {address.postal_code}</address><div className="mt-4 flex flex-wrap gap-5 text-sm underline"><button disabled={busy} onClick={() => editAddress(address)}>Editar</button>{!address.is_default && <button disabled={busy} onClick={() => void addressAction(address, "default")}>Hacer principal</button>}<button disabled={busy} onClick={() => void addressAction(address, "delete")}>Eliminar</button></div></article>)}</div> : <EmptyState title="¿A dónde llegará tu próxima pieza?" body="Agrega una dirección de entrega para tenerla a mano." />}</>}
      {section === "Puntos y recompensas" && <><p className="text-5xl font-semibold tracking-tight">{account?.foundationReady ? availablePoints : "—"}<span className="ml-3 text-base font-normal text-[#72675e]">puntos disponibles</span></p><p className="mt-5 max-w-lg leading-7 text-[#72675e]">Los puntos tienen una vigencia de 12 meses. Una reseña válida de una compra verificada suma 100 puntos cuando el programa esté disponible.</p><div className="mt-8"><h3 className="mb-4 font-semibold">Historial y vencimientos</h3>{account?.points.length ? <ul className="divide-y divide-[#d9cfc4]">{account.points.map((row, index) => <li key={index} className="flex justify-between gap-5 py-4 text-sm"><span>Reseña verificada · +{row.points}</span><span>Vence {new Date(row.expires_at).toLocaleDateString("es-MX")}</span></li>)}</ul> : <p className="text-sm text-[#72675e]">Aún no hay movimientos para mostrar.</p>}</div><div className="mt-10"><EmptyState title="Más motivos para volver." body="Cuando tengas una recompensa disponible, aparecerá aquí con sus condiciones. No hay descuentos activos para aplicar desde esta sección." /></div></>}
      {section === "Perfil" && <form onSubmit={saveProfile} className="max-w-md space-y-6"><label className="block text-sm">Cómo te llamamos<input name="displayName" required maxLength={100} defaultValue={account?.profile.displayName} className="comu-field" /></label><div><p className="text-sm">Correo de tu cuenta</p><p className="mt-2 text-[#72675e]">{account?.profile.email}</p></div><button disabled={busy} className="comu-button">Guardar cambios</button></form>}
    </>}{notice && <p role="status" className="mt-6 rounded-xl bg-[#eee7de] p-4 text-sm">{notice}</p>}</div></div>
    <dialog ref={dialog} className="comu-modal" aria-labelledby="address-title"><div className="flex justify-between"><h2 id="address-title" className="text-2xl font-semibold">{editing ? "Editar dirección" : "Nueva dirección"}</h2><button onClick={() => dialog.current?.close()} aria-label="Cerrar" className="px-3 text-2xl">×</button></div><form key={editing?.id || "new"} onSubmit={saveAddress} className="mt-6 grid gap-4 sm:grid-cols-2">{[["label", "Nombre (casa, trabajo)"], ["recipient_name", "Quién recibe"], ["phone", "Teléfono"], ["postal_code", "Código postal"], ["line1", "Calle y número"], ["line2", "Interior (opcional)"], ["city", "Ciudad"], ["state", "Estado"]].map(([name, label]) => <label key={name} className="text-sm">{label}<input name={name} required={name !== "line2"} maxLength={200} pattern={name === "postal_code" ? "[0-9]{5}" : undefined} defaultValue={editing ? String(editing[name as keyof Address] || "") : ""} className="comu-field" /></label>)}<button disabled={busy} className="comu-button mt-3 sm:col-span-2">Guardar dirección</button></form>{notice && <p role="status" className="mt-4 text-sm">{notice}</p>}</dialog>
  </main>;
}
export function OrderList({ orders }: { orders: Order[] }) { return orders.length ? <div className="divide-y divide-[#d9cfc4]">{orders.map(order => <Link key={order.id} href={`/comu/account/orders/${order.id}?view=detail`} className="block py-5"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">Pedido #{order.order_number}</h3><span className="rounded-full bg-[#e2eadf] px-3 py-1 text-xs">{buyerOrderStatus(order.status)}</span></div><p className="mt-3 text-sm text-[#72675e]">{new Date(order.created_at).toLocaleDateString("es-MX")} · {order.comu_order_suborders?.map(row => row.comu_sellers?.public_name).filter(Boolean).join(", ")}</p><p className="mt-2 text-sm">{order.comu_order_items?.map(row => `${row.quantity} × ${row.comu_order_item_snapshots?.[0]?.snapshot?.listingTitle || "Pieza"}`).join(" · ")}</p><div className="mt-4 flex justify-between text-sm"><strong>{formatMxn(Number(order.grand_total))}</strong><span className="underline underline-offset-4">Ver pedido →</span></div></Link>)}</div> : <EmptyState title="Tu primera historia está por comenzar." body="Aquí encontrarás tus pedidos y podrás seguir cada entrega." />; }
