-- REPORTS V1C POST-FLIGHT — READ ONLY
WITH funcs(name,definer)AS(VALUES('pos_signal_rule_config',true),('pos_emit_intelligence_signal',true),('pos_generate_intelligence_signals',true),('pos_get_intelligence_signals',true)), checks AS(
 SELECT 'TABLE signals' check_name,to_regclass('public.pos_intelligence_signals')IS NOT NULL passed,COALESCE(to_regclass('public.pos_intelligence_signals')::text,'absent')actual,'public.pos_intelligence_signals'expected
 UNION ALL SELECT'TABLE configs',to_regclass('public.pos_signal_rule_configs')IS NOT NULL,COALESCE(to_regclass('public.pos_signal_rule_configs')::text,'absent'),'public.pos_signal_rule_configs'
 UNION ALL SELECT'SIGNALS columns',count(*)=30,count(*)::text,'30'FROM information_schema.columns WHERE table_schema='public'AND table_name='pos_intelligence_signals'
 UNION ALL SELECT'CONFIG columns',count(*)=9,count(*)::text,'9'FROM information_schema.columns WHERE table_schema='public'AND table_name='pos_signal_rule_configs'
 UNION ALL SELECT'CHECK constraints',count(*)>=7,count(*)::text,'>=7'FROM pg_constraint WHERE conrelid='public.pos_intelligence_signals'::regclass AND contype='c'
 UNION ALL SELECT'INDEX signals',count(*)>=5,count(*)::text,'>=5'FROM pg_indexes WHERE schemaname='public'AND tablename='pos_intelligence_signals'
 UNION ALL SELECT'RLS both',bool_and(relrowsecurity),string_agg(relname||'='||relrowsecurity,','),'both true'FROM pg_class WHERE oid IN('public.pos_intelligence_signals'::regclass,'public.pos_signal_rule_configs'::regclass)
 UNION ALL SELECT'SELECT policies',count(*)=2,count(*)::text,'2'FROM pg_policies WHERE schemaname='public'AND tablename IN('pos_intelligence_signals','pos_signal_rule_configs')AND cmd='SELECT'
 UNION ALL SELECT'NO write policies',count(*)=0,count(*)::text,'0'FROM pg_policies WHERE schemaname='public'AND tablename IN('pos_intelligence_signals','pos_signal_rule_configs')AND cmd IN('ALL','INSERT','UPDATE','DELETE')
 UNION ALL SELECT'FUNCTION count',count(*)=4,count(*)::text,'4'FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'AND p.proname IN(SELECT name FROM funcs)
 UNION ALL SELECT'FUNCTION security definer',bool_and(p.prosecdef),string_agg(p.proname||'='||p.prosecdef,','ORDER BY p.proname),'all true'FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'AND p.proname IN(SELECT name FROM funcs)
 UNION ALL SELECT'FUNCTION search_path',bool_and('search_path=public'=ANY(COALESCE(p.proconfig,'{}'))),string_agg(p.proname||'='||COALESCE(array_to_string(p.proconfig,','),'null'),';'),'all public'FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'AND p.proname IN(SELECT name FROM funcs)
 UNION ALL SELECT'ACL service_role RPCs',count(*)FILTER(WHERE has_function_privilege('service_role',p.oid,'EXECUTE'))=2,count(*)FILTER(WHERE has_function_privilege('service_role',p.oid,'EXECUTE'))||' granted','2 granted'FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'AND p.proname IN(SELECT name FROM funcs)
 UNION ALL SELECT'HELPERS internal',bool_and(NOT has_function_privilege('service_role',p.oid,'EXECUTE')),string_agg(p.proname||'='||has_function_privilege('service_role',p.oid,'EXECUTE'),','),'helpers false'FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'AND p.proname IN('pos_signal_rule_config','pos_emit_intelligence_signal')
 UNION ALL SELECT'ACL browser denied',bool_and(NOT has_function_privilege('anon',p.oid,'EXECUTE')AND NOT has_function_privilege('authenticated',p.oid,'EXECUTE')AND NOT EXISTS(SELECT 1 FROM aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner)))a WHERE a.grantee=0 AND a.privilege_type='EXECUTE')),count(*)FILTER(WHERE has_function_privilege('anon',p.oid,'EXECUTE')OR has_function_privilege('authenticated',p.oid,'EXECUTE'))||' exposed','0 exposed'FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'AND p.proname IN(SELECT name FROM funcs)
 UNION ALL SELECT'RULE versions',position('_v1'IN pg_get_functiondef(p.oid))>0,'generator contains versioned rules','contains _v1'FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'AND p.proname='pos_generate_intelligence_signals')
SELECT check_name,passed,actual,expected FROM checks UNION ALL SELECT'SUMMARY all_checks_passed',bool_and(passed),bool_and(passed)::text,'true'FROM checks;
