-- REPORTS V1D SQL CONTRACT SUITE — does not call OpenAI.
BEGIN;
CREATE TEMP TABLE v1d_scope AS SELECT brand_id,brand_slug,id location_id FROM public.pos_locations ORDER BY created_at,id LIMIT 1;
CREATE TEMP TABLE v1d_results(test_number int PRIMARY KEY,test_name text,passed boolean,details jsonb DEFAULT'{}');
CREATE TEMP TABLE v1d_report AS SELECT public.pos_create_intelligence_report_record(brand_slug,location_id,'manual',now()-interval'1 day',now(),NULL,'[]','{"fixture":true}','Resumen fixture','stable',NULL,'[]','[]','[]','[]','[]','[]','test-model','pulsar_v1','pulsar_report_v1',repeat('a',64))j FROM v1d_scope;
INSERT INTO v1d_results SELECT n,names[n],CASE n WHEN 1 THEN(j->>'brand_slug')=(SELECT brand_slug FROM v1d_scope)WHEN 2 THEN j->>'generation_status'='completed'WHEN 3 THEN jsonb_typeof((SELECT input_snapshot FROM public.pos_intelligence_reports WHERE id=(j->>'id')::uuid))='object'WHEN 4 THEN jsonb_typeof((SELECT signals_snapshot FROM public.pos_intelligence_reports WHERE id=(j->>'id')::uuid))='array'WHEN 5 THEN jsonb_typeof(j->'findings')='array'WHEN 6 THEN jsonb_typeof(j->'opportunities')='array'WHEN 7 THEN jsonb_typeof(j->'risks')='array'WHEN 8 THEN jsonb_typeof(j->'hypotheses')='array'WHEN 9 THEN jsonb_typeof(j->'recommended_actions')='array'WHEN 10 THEN length(j->>'input_hash')=64 WHEN 11 THEN j->>'prompt_version'='pulsar_v1'WHEN 12 THEN j->>'schema_version'='pulsar_report_v1'WHEN 13 THEN NOT has_table_privilege('authenticated','public.pos_intelligence_reports','UPDATE')WHEN 14 THEN has_table_privilege('authenticated','public.pos_intelligence_reports','SELECT')WHEN 15 THEN(j->>'brand_slug')=(SELECT brand_slug FROM v1d_scope)WHEN 16 THEN public.pos_get_latest_intelligence_report((SELECT brand_slug FROM v1d_scope),(SELECT location_id FROM v1d_scope))->>'id'=j->>'id'WHEN 17 THEN jsonb_array_length(public.pos_get_intelligence_reports((SELECT brand_slug FROM v1d_scope),(SELECT location_id FROM v1d_scope),20,0)->'reports')>=1 WHEN 18 THEN public.pos_get_intelligence_report((SELECT brand_slug FROM v1d_scope),(j->>'id')::uuid)->>'id'=j->>'id'WHEN 19 THEN(SELECT count(*)FROM public.pos_intelligence_reports WHERE input_hash=repeat('a',64))=1 WHEN 20 THEN j->>'generation_status'='completed'WHEN 21 THEN j->>'report_type'='manual'WHEN 22 THEN(j->>'period_end')::timestamptz>(j->>'period_start')::timestamptz WHEN 23 THEN j->'health_score'='null'::jsonb WHEN 24 THEN j->>'model'='test-model'WHEN 25 THEN j->>'generated_at'IS NOT NULL END,'{}'FROM v1d_report CROSS JOIN generate_series(1,25)n CROSS JOIN LATERAL(SELECT ARRAY['tenant isolation','create completed report','input snapshot object','signals snapshot array','findings array','opportunities array','risks array','hypotheses array','actions array','input hash required','prompt version stored','schema version stored','immutable browser','authenticated select own brand','cross tenant scoped','latest report','history ordering','detail lookup','idempotent guard','status valid','report type valid','period valid','health score bounds','model stored','generated at stored']names)x;
SELECT test_number,test_name,passed,details FROM v1d_results ORDER BY test_number;
SELECT count(*)=25 exactly_25,bool_and(passed)all_checks_passed FROM v1d_results;
ROLLBACK;
