import "server-only";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { requireBrandAccess, requireBrandOsAccess } from "@/lib/brand-os/server";
import { requireAdminWorkspace } from "@/lib/workspace/admin-brands";
import { ADMIN_ITEM_FIELDS } from "@/lib/mercury/admin-content";
import { recordCometaActivityEventAfterMutation } from "@/lib/cosmos/activity";
const REVIEW_TABLE = "mercury_client_content_reviews";
const REVIEW_FIELDS = "id,content_item_id,calendar_id,brand_slug,status,submitted_at,submitted_by,decided_at,decided_by,decision_comment,asset_snapshot,content_snapshot,created_at,updated_at";
function db(): SupabaseClient { const url=process.env.NEXT_PUBLIC_SUPABASE_URL, key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_ROLE; if(!url||!key)throw Error("SERVER_CONFIG"); return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}); }
function snapshot(row:Record<string,unknown>){return {title:row.title,contentType:row.content_type,platform:row.platform,objective:row.objective,brief:row.brief,copy:row.copy_base,cta:row.cta,visualDirection:row.visual_direction,referenceNotes:row.reference_notes,publishDate:row.publish_date};}
async function itemFor(brandSlug:string,id:string,admin:boolean){if(admin)await requireAdminWorkspace();const access=admin?await requireBrandAccess(brandSlug):await requireBrandOsAccess(brandSlug);const client=db();const result=await client.from("mercury_content_items").select(ADMIN_ITEM_FIELDS).eq("id",id).eq("brand_slug",access.brand.slug).maybeSingle();if(result.error)throw result.error;if(!result.data)throw Error("CONTENT_NOT_FOUND");return {access,client,item:result.data as Record<string,unknown>};}
async function hasPriorReview(client:SupabaseClient,brandSlug:string,contentItemId:string,currentReviewId?:string){let query=client.from(REVIEW_TABLE).select("id").eq("content_item_id",contentItemId).eq("brand_slug",brandSlug).limit(1);if(currentReviewId)query=query.neq("id",currentReviewId);const result=await query;if(result.error)throw result.error;return Boolean(result.data?.length);}
async function recordReviewEvent(input:{access:Awaited<ReturnType<typeof itemFor>>["access"];item:Record<string,unknown>;actor:string;review:Record<string,unknown>;eventType:"content.sent_for_review"|"content.resent_for_review"|"content.changes_requested"|"content.approved";statusFrom?:string;statusTo?:string;actorType:"admin"|"client"}){const reviewId=String(input.review.id);await recordCometaActivityEventAfterMutation({eventType:input.eventType,entityType:"content_review",entityId:reviewId,reviewId,brand:{id:input.access.brand.id,slug:input.access.brand.slug},actor:{type:input.actorType,userId:input.actor},contentItemId:String(input.item.id),contentTitle:String(input.item.title||"Contenido sin título"),contentType:typeof input.item.content_type==="string"?input.item.content_type:null,platform:typeof input.item.platform==="string"?input.item.platform:null,occurredAt:String(input.review.decided_at||input.review.submitted_at||""),statusFrom:input.statusFrom,statusTo:input.statusTo});}
export async function sendForReview(brandSlug:string,id:string,actor:string){const context=await itemFor(brandSlug,id,true);const {access,client,item}=context;const existing=await client.from(REVIEW_TABLE).select(REVIEW_FIELDS).eq("content_item_id",id).eq("brand_slug",access.brand.slug).eq("status","pending").maybeSingle();if(existing.error)throw existing.error;if(existing.data)return {review:existing.data,duplicate:true};const resent=await hasPriorReview(client,access.brand.slug,id);const assets=await client.from("mercury_content_assets").select("id,asset_type,provider").eq("content_item_id",id).eq("brand_slug",access.brand.slug).neq("asset_status","deleted");if(assets.error)throw assets.error;const review=await client.from(REVIEW_TABLE).insert({content_item_id:id,calendar_id:item.calendar_id,brand_slug:access.brand.slug,status:"pending",submitted_by:actor,asset_snapshot:(assets.data||[]).map(a=>({assetId:String(a.id),assetType:a.asset_type,provider:a.provider})),content_snapshot:snapshot(item)}).select(REVIEW_FIELDS).single();if(review.error){const retry=await client.from(REVIEW_TABLE).select(REVIEW_FIELDS).eq("content_item_id",id).eq("brand_slug",access.brand.slug).eq("status","pending").maybeSingle();if(!retry.error&&retry.data)return {review:retry.data,duplicate:true};throw review.error;}const updated=await client.from("mercury_content_items").update({status:"sent_to_client"}).eq("id",id).eq("brand_slug",access.brand.slug);if(updated.error)throw updated.error;await recordReviewEvent({access,item,actor,review:review.data as Record<string,unknown>,eventType:resent?"content.resent_for_review":"content.sent_for_review",actorType:"admin"});return {review:review.data,duplicate:false};}
export async function decideReview(brandSlug:string,id:string,actor:string,decision:"approved"|"changes_requested",comment?:string){const context=await itemFor(brandSlug,id,false);const {access,client,item}=context;if(decision==="changes_requested"&&(!comment||comment.trim().length<3||comment.length>2000))throw Error("INVALID_COMMENT");const current=await client.from(REVIEW_TABLE).select(REVIEW_FIELDS).eq("content_item_id",id).eq("brand_slug",access.brand.slug).eq("status","pending").maybeSingle();if(current.error)throw current.error;if(!current.data)throw Error("REVIEW_NOT_PENDING");const now=new Date().toISOString();const update=await client.from(REVIEW_TABLE).update({status:decision,decided_by:actor,decided_at:now,decision_comment:decision==="changes_requested"?comment!.trim():null,updated_at:now}).eq("id",current.data.id).eq("status","pending").select(REVIEW_FIELDS).maybeSingle();if(update.error)throw update.error;if(!update.data)throw Error("REVIEW_ALREADY_DECIDED");const statusTo=decision==="approved"?"approved_client":"changes_requested";const itemUpdate=await client.from("mercury_content_items").update({status:statusTo}).eq("id",id).eq("brand_slug",access.brand.slug);if(itemUpdate.error)throw itemUpdate.error;await recordReviewEvent({access,item,actor,review:update.data as Record<string,unknown>,eventType:decision==="approved"?"content.approved":"content.changes_requested",statusFrom:"pending",statusTo:decision,actorType:"client"});return update.data;}
export async function getReviewForClient(brandSlug:string,id:string){const {access,client}=await itemFor(brandSlug,id,false);const result=await client.from(REVIEW_TABLE).select("id,status,submitted_at,decided_at,decision_comment,asset_snapshot,content_snapshot").eq("content_item_id",id).eq("brand_slug",access.brand.slug).order("created_at",{ascending:false}).limit(1).maybeSingle();if(result.error)throw result.error;if(!result.data)return null;return {id:String(result.data.id),status:result.data.status,submittedAt:result.data.submitted_at,decidedAt:result.data.decided_at,decisionComment:result.data.decision_comment||null,assetSnapshot:result.data.asset_snapshot||[]};}
export async function getReviewHistory(brandSlug:string,id:string){const {access,client}=await itemFor(brandSlug,id,true);const result=await client.from(REVIEW_TABLE).select(REVIEW_FIELDS).eq("content_item_id",id).eq("brand_slug",access.brand.slug).order("created_at",{ascending:false});if(result.error)throw result.error;return result.data||[];}
