"use client";
import { useEffect, useState } from "react";
type Order = { id: string; order_number?: string; fulfillment_status?: string; fulfillment_route?: "HUB" | "DIRECT"; overdue?: boolean; comu_orders?: { order_number?: string } };
const labels: Record<string, string> = { PAID: "Nuevos", PREPARING: "Preparando", READY_FOR_HUB: "Listos para entregar", HANDED_TO_HUB: "Entregados al HUB", HUB_RECEIVED: "Recibidos por HUB", CONSOLIDATED: "Consolidados", READY_TO_SHIP: "Listos para envío", SHIPPED: "Enviados", DELIVERED: "Entregados" };
const hubNext: Record<string, { status: string; label: string }> = { PAID: { status: "PREPARING", label: "Comenzar preparación" }, PREPARING: { status: "READY_FOR_HUB", label: "Pedido listo" }, READY_FOR_HUB: { status: "HANDED_TO_HUB", label: "Entregado al HUB" } };
const directNext: Record<string, { status: string; label: string }> = { PAID: { status: "PREPARING", label: "Comenzar preparación" }, PREPARING: { status: "READY_TO_SHIP", label: "Pedido listo para envío" } };
export default function SellerOrders() {
  const [orders, setOrders] = useState<Order[]>([]); const [sellerId, setSellerId] = useState(""); const [message, setMessage] = useState("");
  async function load(id: string) { const response = await fetch(`/api/comu/seller/orders?sellerId=${encodeURIComponent(id)}`); const data = await response.json() as { orders?: Order[]; message?: string }; setOrders(data.orders || []); if (!response.ok) setMessage(data.message || "No se pudieron cargar los pedidos."); }
  useEffect(() => { void fetch("/api/comu/sellers?mine=1").then(r => r.json()).then((data: { sellers?: Array<{ id: string }> }) => { const id = data.sellers?.[0]?.id || ""; setSellerId(id); if (id) void load(id); }); }, []);
  async function advance(order: Order, status: string) { const response = await fetch(`/api/comu/seller/orders/${order.id}/fulfillment`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, status }) }); const data = await response.json() as { message?: string }; setMessage(response.ok ? "Pedido actualizado." : data.message || "No se pudo actualizar."); if (sellerId) void load(sellerId); }
  async function prepareDirect(order: Order) { const response = await fetch(`/api/comu/seller/orders/${order.id}/direct-shipment`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, weightKg: 1, lengthCm: 30, widthCm: 20, heightCm: 10 }) }); const data = await response.json() as { message?: string }; setMessage(response.ok ? "Guía local preparada." : data.message || "No se pudo preparar el envío."); if (sellerId) void load(sellerId); }
  async function shipDirect(order: Order) { const response = await fetch(`/api/comu/seller/orders/${order.id}/direct-shipment`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, action: "SHIP" }) }); const data = await response.json() as { message?: string }; setMessage(response.ok ? "Pedido marcado como enviado." : data.message || "No se pudo marcar el envío."); if (sellerId) void load(sellerId); }
  return <main className="mx-auto max-w-6xl px-5 py-12"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Seller studio</p><h1 className="mt-3 text-5xl font-black">Pedidos de tu tienda</h1>{message ? <p className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold">{message}</p> : null}<div className="mt-8 space-y-4">{orders.map(order => { const status = order.fulfillment_status || "PAID"; const action = (order.fulfillment_route === "DIRECT" ? directNext : hubNext)[status]; return <article key={order.id} className="rounded-3xl bg-white p-6"><div className="flex items-center justify-between gap-4"><div><p className="font-black">#{order.comu_orders?.order_number || order.order_number || order.id.slice(0, 8)}</p><p className="text-sm text-slate-600">{labels[status] || status} · {order.fulfillment_route === "DIRECT" ? "Envío directo" : "HUB"}</p></div>{order.overdue ? <span className="rounded-full bg-red-100 px-3 py-1 text-xs font-black text-red-700">Atrasado</span> : null}</div>{action ? <button onClick={() => void advance(order, action.status)} className="mt-5 rounded-full bg-[#17201d] px-5 py-3 text-sm font-bold text-white">{action.label}</button> : null}{order.fulfillment_route === "DIRECT" && status === "READY_TO_SHIP" ? <><button onClick={() => void prepareDirect(order)} className="ml-3 mt-5 rounded-full border px-5 py-3 text-sm font-bold">Preparar envío local</button><button onClick={() => void shipDirect(order)} className="ml-3 mt-5 rounded-full border px-5 py-3 text-sm font-bold">Marcar enviado</button></> : null}</article>; })}{!orders.length ? <p className="text-slate-500">No hay pedidos para preparar.</p> : null}</div></main>;
}
