"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

export type StudioPieceListItem = { id: string; brandName: string; title: string; contentType: string | null; distributionType: string | null; status: string; publishDate: string | null; dueDate: string | null };
type Filter = "all" | "today" | "week" | "changes" | "organic" | "paid" | "production" | "ready";
const filters: Array<[Filter, string]> = [["all", "Todas"], ["today", "Hoy"], ["week", "Esta semana"], ["changes", "Cambios"], ["organic", "Orgánico"], ["paid", "Pauta"], ["production", "En producción"], ["ready", "Listas"]];

export function PiecesClient({ items }: { items: StudioPieceListItem[] }) { const [filter, setFilter] = useState<Filter>("all"); const [search, setSearch] = useState(""); const visible = useMemo(() => items.filter((item) => matches(item, filter) && (!search.trim() || `${item.title} ${item.brandName}`.toLocaleLowerCase("es").includes(search.trim().toLocaleLowerCase("es")))), [items, filter, search]); return <><header><p className="text-[10px] uppercase tracking-[.3em] text-cyan-300">CREATIVE OPERATIONS</p><h1 className="mt-2 text-3xl font-semibold">MIS PIEZAS</h1><p className="mt-2 text-sm text-slate-400">Todo tu trabajo asignado, organizado para producir.</p><p className="mt-4 text-xs text-slate-500">{items.length} {items.length === 1 ? "pieza asignada" : "piezas asignadas"}</p></header><div className="mt-7 flex flex-wrap items-center gap-2"><div className="flex flex-wrap gap-2">{filters.map(([value, label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-3 py-1.5 text-xs transition ${filter === value ? "bg-cyan-300 text-slate-950" : "border border-white/10 text-slate-300 hover:border-cyan-300/30"}`}>{label}</button>)}</div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por título o marca" className="min-w-56 flex-1 rounded-xl border border-white/10 bg-white/[.035] px-3 py-2 text-xs outline-none placeholder:text-slate-600 focus:border-cyan-300/40 sm:ml-auto sm:max-w-xs" /></div>{visible.length ? <div className="mt-6 grid gap-3 xl:grid-cols-2">{visible.map((item) => <PieceCard key={item.id} item={item} />)}</div> : <div className="mt-8 rounded-3xl border border-dashed border-emerald-300/20 bg-emerald-300/[.025] p-10 text-center"><p className="font-semibold text-emerald-200">✓ Todo al día</p><p className="mt-2 text-sm text-slate-400">{items.length ? "No hay piezas con estos filtros." : "No tienes piezas asignadas."}</p></div>}</>;
}
function PieceCard({ item }: { item: StudioPieceListItem }) { const changes = item.status === "changes_requested"; return <article className={`grid grid-cols-[72px_1fr] gap-4 rounded-2xl border p-3.5 transition ${changes ? "border-rose-300/25 bg-rose-300/[.045]" : "border-white/10 bg-white/[.03] hover:border-cyan-300/20"}`}><Preview type={item.contentType} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2 text-[10px] font-semibold uppercase tracking-wider"><span className="text-cyan-300">{typeLabel(item.contentType)}</span><span className="text-slate-500">{distributionLabel(item.distributionType)}</span><span className={`ml-auto ${statusTone(item.status)}`}>{statusLabel(item.status)}</span></div><h2 className="mt-2 line-clamp-2 text-[15px] font-medium leading-snug">{item.title}</h2><p className="mt-1 text-[11px] font-semibold uppercase tracking-[.14em] text-slate-500">{item.brandName}</p><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-slate-400">{item.distributionType === "paid" ? "Activación" : "Publicación"} · {humanDate(item.publishDate || item.dueDate)}</p><Link href={`/studio/pieces/${encodeURIComponent(item.id)}`} className={`whitespace-nowrap text-xs font-semibold ${changes ? "text-rose-200" : "text-cyan-300"}`}>{changes ? "Resolver cambios" : "Ver pieza"} →</Link></div>{changes && <p className="mt-2 text-[11px] text-rose-200/80">Cambio solicitado · revisa la indicación antes de continuar.</p>}</div></article>; }
function matches(item: StudioPieceListItem, filter: Filter) { if (filter === "all") return true; if (filter === "changes") return item.status === "changes_requested"; if (filter === "organic") return item.distributionType !== "paid"; if (filter === "paid") return item.distributionType === "paid"; if (filter === "production") return item.status === "in_design"; if (filter === "ready") return ["design_uploaded", "internal_review", "approved_internal"].includes(item.status); const date = item.publishDate || item.dueDate; if (!date) return false; const target = new Date(`${date.slice(0, 10)}T12:00:00`); const now = new Date(); if (filter === "today") return target.toDateString() === now.toDateString(); const day = now.getDay() || 7; const start = new Date(now); start.setDate(now.getDate() - day + 1); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(start.getDate() + 7); return target >= start && target < end; }
function Preview({ type }: { type: string | null }) { const kind = type || "post"; return <div className="relative grid h-[76px] w-[72px] place-items-center overflow-hidden rounded-xl border border-cyan-300/15 bg-[#0c2035] text-cyan-200">{kind === "reel" ? <><span className="h-14 w-8 rounded-md border border-violet-300/40"/><span className="absolute">▶</span></> : kind === "story" ? <span className="h-14 w-8 rounded-md border border-cyan-300/50"/> : kind === "carousel" ? <><span className="absolute h-10 w-10 translate-x-1 translate-y-1 rounded border border-cyan-300/30"/><span className="relative h-10 w-10 rounded border border-cyan-300/60"/></> : <span className="h-11 w-11 rounded border border-cyan-300/50"/>}</div>; }
function typeLabel(value: string | null) { return ({ reel: "Reel", story: "Story", carousel: "Carrusel", post: "Post", static_post: "Post" } as Record<string, string>)[value || ""] || "Contenido"; }
function distributionLabel(value: string | null) { return value === "paid" ? "Pauta" : value === "organic_paid" ? "Orgánico + Pauta" : "Orgánico"; }
function statusLabel(value: string) { return ({ generated: "Planeada", assigned: "Asignada", in_design: "En producción", design_uploaded: "Lista para revisión", internal_review: "Revisión interna", changes_requested: "Cambios solicitados", approved_internal: "Aprobada por Cometa", sent_to_client: "Cliente revisando", approved_client: "Aprobada por cliente", scheduled: "Programada", published: "Publicada", analyzed: "Analizada", cancelled: "Cancelada" } as Record<string, string>)[value] || "En proceso"; }
function statusTone(value: string) { return value === "changes_requested" ? "text-rose-200" : ["design_uploaded", "internal_review", "approved_internal"].includes(value) ? "text-emerald-200" : "text-slate-400"; }
function humanDate(value: string | null) { return value ? new Intl.DateTimeFormat("es-MX", { day: "numeric", month: "short", timeZone: "UTC" }).format(new Date(`${value.slice(0, 10)}T12:00:00Z`)) : "Sin fecha"; }
