import Link from "next/link";
import { getStudioChangeCards, type StudioChangeCard } from "@/lib/studio/changes";
import { getStudioWorkspaceData, requireStudioAccess } from "@/lib/studio/server";

export const dynamic = "force-dynamic";

export default async function ChangesPage() {
  const studio = await requireStudioAccess(); const workspace = await getStudioWorkspaceData(studio);
  const items = await getStudioChangeCards(studio.userId, workspace.brands.map((brand) => String(brand.slug)));
  return <main className="min-h-screen bg-[#07111f] text-white"><div className="mx-auto grid max-w-[1600px] lg:grid-cols-[240px_minmax(0,1fr)]"><StudioNav count={items.length} /><section className="min-w-0 p-5 sm:p-8 lg:p-10"><header><p className="text-[10px] uppercase tracking-[.3em] text-cyan-300">CREATIVE OPERATIONS</p><h1 className="mt-2 text-3xl font-semibold">CAMBIOS</h1><p className="mt-2 text-sm text-slate-400">Estas piezas necesitan correcciones antes de continuar.</p><p className="mt-4 text-xs font-medium text-rose-200">{items.length} {items.length === 1 ? "pieza necesita" : "piezas necesitan"} tu atención.</p></header>{items.length ? <div className="mt-8 grid gap-5 xl:grid-cols-2">{items.map((item) => <ChangeCard key={item.id} item={item} />)}</div> : <div className="mt-10 rounded-3xl border border-dashed border-emerald-300/20 bg-emerald-300/[.03] p-12 text-center"><p className="text-lg font-semibold text-emerald-200">✓ Todo al día</p><p className="mt-2 text-sm text-slate-400">No tienes correcciones pendientes.</p></div>}</section></div></main>;
}

function StudioNav({ count }: { count: number }) { const links = [["/studio", "Inicio"], ["/studio/operation", "Operación"], ["/studio/pieces", "Piezas"], ["/studio/changes", "Cambios"], ["/studio/recordings", "Grabaciones"], ["/studio/resources", "Recursos"]]; return <aside className="border-r border-white/[.07] bg-[#081525] p-5 lg:min-h-screen"><div className="text-lg font-semibold tracking-[.28em]">COMETA</div><div className="text-[10px] uppercase tracking-[.25em] text-cyan-300">STUDIO</div><p className="mb-2 mt-10 px-2 text-[10px] uppercase tracking-[.2em] text-slate-600">MI PRODUCCIÓN</p><nav className="space-y-1">{links.map(([href, label]) => <Link key={href} href={href} className={`flex items-center rounded-xl px-3 py-2.5 text-sm transition ${href === "/studio/changes" ? "bg-rose-400/[.08] text-rose-100" : "text-slate-300 hover:bg-white/[.06]"}`}><span>{label}</span>{label === "Cambios" && count > 0 && <span className="ml-auto rounded-full bg-rose-400/20 px-2 text-[10px] text-rose-200">{count}</span>}</Link>)}</nav></aside>; }
function ChangeCard({ item }: { item: StudioChangeCard }) { const client = item.change.source === "client"; return <article className={`overflow-hidden rounded-3xl border bg-[#0b192a] ${client ? "border-fuchsia-300/20" : "border-amber-300/20"}`}><div className="grid gap-5 p-4 sm:grid-cols-[150px_1fr]"><Preview item={item} /><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-300">{item.brandName}</p><p className="mt-2 text-xs uppercase tracking-wider text-slate-400">{typeLabel(item.contentType)} · {distributionLabel(item.distributionType)}</p><h2 className="mt-2 text-lg font-semibold leading-snug">{item.title}</h2><p className="mt-2 text-xs text-slate-400">{item.distributionType === "paid" ? "Activación prevista" : "Publicación"} · {formatDate(item.publishDate || item.dueDate)}</p><span className="mt-3 inline-block rounded-full bg-rose-400/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-rose-200">Cambios solicitados</span></div></div><div className={`mx-4 mb-4 rounded-2xl border p-4 ${client ? "border-fuchsia-300/20 bg-fuchsia-300/[.055]" : "border-amber-300/20 bg-amber-300/[.05]"}`}><p className={`text-[10px] font-semibold uppercase tracking-[.18em] ${client ? "text-fuchsia-200" : "text-amber-200"}`}>{client ? "Cambio del cliente" : "Cambio interno"}</p><p className="mt-3 line-clamp-4 whitespace-pre-wrap text-sm leading-6 text-slate-100">“{item.change.message}”</p><p className="mt-3 text-xs text-slate-400">{item.change.requestedByLabel} · {formatDateTime(item.change.requestedAt)}</p></div><div className="border-t border-white/[.07] p-4 text-right"><Link href={`/studio/pieces/${encodeURIComponent(item.id)}`} className="inline-flex rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-cyan-200">Resolver cambios</Link></div></article>; }
function Preview({ item }: { item: StudioChangeCard }) { if (item.deliverable?.url && isImage(item.deliverable.mimeType, item.deliverable.url)) return <img src={item.deliverable.url} alt={`Entregable actual de ${item.title}`} className="h-40 w-full rounded-2xl object-cover sm:h-44" />; return <div className="grid h-40 w-full place-items-center rounded-2xl border border-cyan-300/15 bg-gradient-to-br from-cyan-300/[.12] via-[#102039] to-violet-300/[.1] text-center text-xs font-semibold uppercase tracking-wider text-cyan-200 sm:h-44">{item.deliverable ? "Entregable disponible" : typeLabel(item.contentType)}</div>; }
function isImage(mime: string | null, url: string) { return mime?.startsWith("image/") || /\.(png|jpe?g|webp|gif)(?:\?|$)/i.test(url); }
function typeLabel(value: string | null) { return ({ reel: "Reel", story: "Story", carousel: "Carrusel", post: "Post", static_post: "Post" } as Record<string, string>)[value || ""] || "Contenido"; }
function distributionLabel(value: string | null) { return value === "paid" ? "Pauta" : value === "organic_paid" ? "Orgánico + Pauta" : "Orgánico"; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("es-MX", { day: "numeric", month: "short", timeZone: "UTC" }).format(new Date(`${value.slice(0, 10)}T12:00:00Z`)) : "Sin fecha"; }
function formatDateTime(value: string | null) { return value ? new Intl.DateTimeFormat("es-MX", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit", timeZone: "America/Mexico_City" }).format(new Date(value)) : "Fecha no disponible"; }
