import Link from "next/link";
import { InsightCard, OsIcon, PageHeader, Section, StatusBadge } from "../components/os-primitives";

const categories = [{ label: "Riesgos", icon: "alert" as const }, { label: "Oportunidades", icon: "spark" as const }, { label: "Recomendaciones", icon: "arrow" as const }, { label: "Observando", icon: "check" as const }];
const sources = [{ name: "Sales AI", detail: "Conversaciones y seguimiento", status: "Disponible" }, { name: "Marketing", detail: "Estrategia y ejecución", status: "Disponible" }, { name: "WhatsApp", detail: "Canal de conversaciones", status: "Disponible" }, { name: "Cometa POS", detail: "Ventas e inventario", status: "No conectado" }];
export default function IntelligencePage() {
  return <div className="space-y-6"><PageHeader eyebrow="COMETA INTELLIGENCE" title="Qué importa ahora" description="Lo que Cometa está viendo en tu negocio, explicado con evidencia para ayudarte a decidir." />
    <section className="os-card-primary overflow-hidden border-cyan-100 bg-gradient-to-br from-white via-white to-cyan-50/70"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-cyan-50 text-cyan-700"><OsIcon name="spark" className="h-5 w-5" /></div><div><div className="flex flex-wrap items-center gap-2"><StatusBadge label="Observando" tone="positive" /><span className="text-xs text-[var(--os-text-muted)]">Sin señales prioritarias</span></div><h2 className="mt-2 text-lg font-semibold tracking-[-0.03em]">Cometa está reuniendo evidencia de tus fuentes conectadas.</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-[var(--os-text-muted)]">Cuando haya suficiente actividad, aquí aparecerán oportunidades, riesgos y recomendaciones con su contexto.</p></div></div><Link href="../connections" className="shrink-0 text-sm font-semibold text-blue-700">Revisar fuentes →</Link></div></section>
    <Section title="Resumen de señales" description="Una lectura rápida del estado de tu negocio."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{categories.map((item) => <article key={item.label} className="os-card flex items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><OsIcon name={item.icon} className="h-4 w-4" /></div><div><p className="os-label">{item.label}</p><p className="mt-1 text-2xl font-semibold tracking-[-0.04em]">0</p></div></article>)}</div></Section>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1.7fr)_minmax(250px,.75fr)]"><div className="min-w-0 space-y-5"><Section title="Señales para explorar"><div className="grid gap-3 md:grid-cols-3"><InsightCard kind="Oportunidades" title="Aún no hay oportunidades" summary="Aparecerán cuando Cometa detecte patrones accionables." /><InsightCard kind="Riesgos" title="Sin riesgos prioritarios" summary="No se han registrado señales que requieran atención." /><InsightCard kind="Recomendaciones" title="Sin recomendaciones" summary="Las recomendaciones se basarán en actividad real." /></div></Section></div><Section title="Fuentes conectadas" description="Lo que Cometa puede observar hoy."><div className="os-card space-y-1">{sources.map((source) => <div key={source.name} className="flex items-center gap-3 border-b border-[var(--os-border)] py-3 last:border-0"><div className="h-2.5 w-2.5 shrink-0 rounded-full bg-slate-300" /><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{source.name}</p><p className="mt-0.5 text-xs text-[var(--os-text-muted)]">{source.detail}</p></div><span className={`text-[11px] font-semibold ${source.status === "Disponible" ? "text-emerald-700" : "text-slate-500"}`}>{source.status}</span></div>)}</div></Section></div>
  </div>;
}
