import Link from "next/link";
import { WorkspaceShell } from "../components/workspace-shell";
import { getAdminCalendarWorkspaceOverview, type AdminCalendarSummary } from "@/lib/workspace/admin-calendars";
import { calendarPeriod, contentStatusLabel, shortEditorialDate } from "@/lib/workspace/presentation";

export const dynamic = "force-dynamic";

export default async function WorkspaceCalendarsPage() {
  const overview = await getAdminCalendarWorkspaceOverview();
  const calendars = overview.brands.flatMap((brand) => brand.calendars);
  const totals = calendars.reduce((sum, calendar) => ({ pieces: sum.pieces + calendar.counts.total, changes: sum.changes + calendar.counts.changesRequested, approved: sum.approved + calendar.counts.approvedClient, published: sum.published + calendar.counts.published }), { pieces: 0, changes: 0, approved: 0, published: 0 });
  const latest = [...calendars].sort((a, b) => b.cycleYear - a.cycleYear || b.cycleMonth - a.cycleMonth)[0];

  return <WorkspaceShell>
    <header className="border-b border-white/[.08] pb-7"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-cyan-300">Operación de contenido</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-white sm:text-5xl">Calendarios</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Contenido, revisiones y publicaciones de todas tus marcas.</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-white/10 bg-white/[.035] px-4 py-2 text-xs text-slate-300">{latest ? `Periodo más reciente · ${calendarPeriod(latest.cycleMonth, latest.cycleYear)}` : "Sin periodos registrados"}</span><span className="rounded-full border border-cyan-400/20 bg-cyan-400/[.08] px-4 py-2 text-xs text-cyan-200">{calendars.length} {calendars.length === 1 ? "calendario" : "calendarios"}</span></div></div>
      <div className="mt-7 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/[.06] pt-5"><InlineStat value={totals.pieces} label="piezas" /><InlineStat value={totals.changes} label="cambios solicitados" tone="amber" /><InlineStat value={totals.approved} label="aprobadas" tone="emerald" /><InlineStat value={totals.published} label="publicadas" tone="cyan" /></div>
    </header>

    {overview.brands.length ? <div className="mt-7 space-y-4">{overview.brands.map((brand) => <section key={brand.slug} className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#0b1829]"><div className="flex flex-col justify-between gap-4 px-5 py-5 sm:flex-row sm:items-center sm:px-7"><div><h2 className="text-xl font-semibold tracking-tight text-white">{brand.name}</h2><p className="mt-1 text-sm text-slate-500">{brand.calendars.length ? `${brand.calendars.length} ${brand.calendars.length === 1 ? "periodo registrado" : "periodos registrados"}` : "Sin calendario registrado"}</p></div><Link href={`/workspace/brands/${brand.slug}/calendar`} className="w-fit text-sm font-semibold text-cyan-300 transition hover:text-cyan-100">Abrir calendario →</Link></div>{brand.calendars.length ? <div className="border-t border-white/[.07]">{brand.calendars.map((calendar) => <CalendarRow key={calendar.id} calendar={calendar} />)}</div> : <p className="border-t border-white/[.07] px-5 py-6 text-sm text-slate-500 sm:px-7">Esta marca todavía no tiene periodos de contenido registrados.</p>}</section>)}</div> : <div className="mt-8 border-y border-white/[.08] py-16 text-center"><p className="text-lg font-medium text-white">No hay marcas registradas</p><p className="mt-2 text-sm text-slate-500">Los calendarios aparecerán aquí cuando exista información real.</p></div>}
  </WorkspaceShell>;
}

function CalendarRow({ calendar }: { calendar: AdminCalendarSummary }) {
  const status = contentStatusLabel(calendar.status);
  return <article className="grid gap-6 px-5 py-6 sm:px-7 lg:grid-cols-[minmax(220px,.7fr)_minmax(320px,1.2fr)] lg:gap-10"><div><div className="flex flex-wrap items-center gap-3"><h3 className="text-lg font-medium text-white">{calendarPeriod(calendar.cycleMonth, calendar.cycleYear)}</h3><span className="rounded-full border border-white/10 px-2.5 py-1 text-[11px] text-slate-400">{status}</span></div><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-sm"><span><strong className="font-semibold text-white">{calendar.counts.total}</strong> <span className="text-slate-500">piezas</span></span><span><strong className="font-semibold text-amber-200">{calendar.counts.changesRequested}</strong> <span className="text-slate-500">cambios</span></span><span><strong className="font-semibold text-emerald-200">{calendar.counts.approvedClient}</strong> <span className="text-slate-500">aprobadas</span></span><span><strong className="font-semibold text-cyan-200">{calendar.counts.published}</strong> <span className="text-slate-500">publicadas</span></span></div></div><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-slate-500">Próximas</p>{calendar.upcomingPublications.length ? <div className="mt-3 divide-y divide-white/[.06]">{calendar.upcomingPublications.map((item) => <PublicationRow key={item.id} item={item} />)}</div> : <p className="mt-4 text-sm text-slate-500">No hay próximas publicaciones registradas para este periodo.</p>}</div></article>;
}

function PublicationRow({ item }: { item: AdminCalendarSummary["upcomingPublications"][number] }) { const date = shortEditorialDate(item.publishDate); return <div className="grid grid-cols-[58px_minmax(0,1fr)] gap-4 py-3 first:pt-0 last:pb-0"><time dateTime={item.publishDate} className="flex flex-col leading-none"><span className="text-xl font-semibold text-white">{date.day}</span><span className="mt-1 text-[10px] font-semibold tracking-[.16em] text-cyan-300">{date.month}</span></time><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-100">{item.title}</p><p className="mt-1 text-xs text-slate-500">{contentStatusLabel(item.status)}</p></div></div>; }
function InlineStat({ value, label, tone = "white" }: { value: number; label: string; tone?: "white" | "amber" | "emerald" | "cyan" }) { const color = tone === "amber" ? "text-amber-200" : tone === "emerald" ? "text-emerald-200" : tone === "cyan" ? "text-cyan-200" : "text-white"; return <p className="text-sm"><strong className={`text-lg font-semibold ${color}`}>{value}</strong> <span className="ml-1 text-slate-500">{label}</span></p>; }
