"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { DecisionCard, EmptyState, ErrorState, InsightCard, MetricCard, Section, Skeleton } from "./os-primitives";

type Center = { pulse: { attentionCount: number }; sales: { leads: number | null; hotLeads: number | null; requiresHuman: number | null; followupsPending: number | null }; marketing: { strategyPublished: boolean; contentInReview: number; contentPublished: number }; connections: { whatsapp: { status: string }; pos: { status: string } }; availability: { sales: boolean; marketing: boolean; connections: boolean }; intelligence: { signals: unknown[] }; work: { recent: unknown[] } };
export function CommandCenterClient({ brandSlug }: { brandSlug: string }) {
  const [data, setData] = useState<Center | null>(null); const [error, setError] = useState(false);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/os/${encodeURIComponent(brandSlug)}/command-center`, { cache: "no-store", signal: controller.signal }).then((r) => r.ok ? r.json() : Promise.reject()).then((payload: Center) => setData(payload)).catch(() => { if (!controller.signal.aborted) setError(true); }); return () => controller.abort(); }, [brandSlug]);
  if (error) return <ErrorState />; if (!data) return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Skeleton /><Skeleton /><Skeleton /><Skeleton /></div>;
  const base = `/brand/${encodeURIComponent(brandSlug)}/os`; const attention = data.pulse.attentionCount; const sales = data.sales; const content = data.marketing.contentInReview + data.marketing.contentPublished;
  return <div className="space-y-8"><Section title="Hoy en tu negocio" description="La actividad que merece contexto, no sólo números."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Leads activos" value={String(sales.leads ?? 0)} context={sales.hotLeads ? `${sales.hotLeads} calientes` : "Sin actividad prioritaria"} status={sales.hotLeads ? "attention" : "neutral"} /><MetricCard label="Atención" value={String(attention)} context={attention ? "Asuntos para revisar" : "Todo bajo control"} status={attention ? "attention" : "positive"} /><MetricCard label="Seguimientos" value={String(sales.followupsPending ?? 0)} context="Pendientes" /><MetricCard label="Contenido" value={String(content)} context={data.availability.marketing ? `${data.marketing.contentInReview} en revisión` : "Esperando actividad"} /></div></Section>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1.65fr)_minmax(280px,.85fr)]"><div className="min-w-0 space-y-6"><Section title="Cometa Intelligence" description="Señales, oportunidades y recomendaciones explicadas con evidencia." accent="intelligence"><div className="grid gap-3 md:grid-cols-3">{data.intelligence.signals.length ? <InsightCard kind="Señal" title="Hay señales para explorar" summary="Cometa encontró actividad persistida para revisar." action={<Link href={`${base}/intelligence`} className="text-xs font-semibold text-blue-700">Ver Intelligence →</Link>} /> : <div className="md:col-span-3"><EmptyState status="Observando" title="Aún estamos reuniendo señales" description="Cuando exista evidencia real, aparecerá aquí con su contexto y próximo paso." source="Actividad conectada" action={<Link href={`${base}/intelligence`} className="inline-flex rounded-xl bg-[var(--os-primary)] px-4 py-2.5 text-sm font-semibold text-white">Ver Intelligence</Link>} /></div>}</div></Section></div><section className="min-w-0"><div className="mb-3 flex items-center justify-between gap-3"><div><p className="os-label">PRÓXIMAS DECISIONES</p><p className="mt-1 text-sm text-[var(--os-text-muted)]">Lo que merece tu atención.</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold text-slate-600">{attention + (data.marketing.contentInReview ? 1 : 0)}</span></div><div className="space-y-3">{attention ? <DecisionCard title="Revisar asuntos de Sales AI" context={`${attention} conversaciones requieren atención.`} href={`${base}/sales`} /> : null}{data.marketing.contentInReview ? <DecisionCard title="Revisar contenido" context="Hay piezas esperando tu revisión." href={`${base}/marketing/content`} /> : null}{!attention && !data.marketing.contentInReview ? <div className="os-card-subtle"><p className="text-sm font-semibold">No hay decisiones prioritarias ahora</p><p className="mt-1 text-xs text-[var(--os-text-muted)]">Cometa seguirá observando la actividad conectada.</p></div> : null}</div></section></div></div>;
}
