"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState, type ReactNode } from "react";
import { OsIcon } from "./os-primitives";

const nav = [["Resumen", "", "home"], ["Intelligence", "/intelligence", "spark"], ["Sales AI", "/sales", "sales"], ["Marketing", "/marketing", "marketing"], ["Trabajo realizado", "/work", "work"], ["Reportes", "/reports", "report"], ["Conexiones", "/connections", "link"], ["Configuración", "/settings", "settings"]] as const;
export function OsShell({ brand, posAvailable, children }: { brand: { slug: string; name: string }; posAvailable: boolean; children: ReactNode }) {
  const pathname = usePathname(); const [mobileOpen, setMobileOpen] = useState(false); const base = `/brand/${encodeURIComponent(brand.slug)}/os`;
  return <div className="min-h-screen bg-[var(--os-canvas)] text-[var(--os-text)]"><div className="mx-auto flex min-h-screen max-w-[1600px]">
    <aside className={`fixed inset-y-0 left-0 z-40 w-[264px] border-r border-slate-800 bg-[#07142d] px-4 py-5 text-white transition-transform lg:static lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}><div className="flex h-full flex-col"><div className="flex items-center justify-between px-2"><Link href={base} onClick={() => setMobileOpen(false)} className="min-w-0"><p className="text-[11px] font-bold tracking-[0.22em] text-blue-300">COMETA OS</p><p className="mt-2 truncate text-[15px] font-semibold text-white">{brand.name}</p></Link><button type="button" className="rounded-lg p-2 text-slate-400 lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Cerrar navegación">×</button></div>
      <nav aria-label="Navegación principal" className="mt-9 space-y-1">{nav.map(([label, suffix, icon]) => { const href = `${base}${suffix}`; const active = suffix === "" ? pathname === base : pathname.startsWith(href); return <Link key={href} href={href} onClick={() => setMobileOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${active ? "bg-[#1D4ED8] text-white shadow-lg shadow-blue-950/30" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><OsIcon name={icon} className="h-[18px] w-[18px] shrink-0" />{label}</Link>; })}</nav>
      <div className="mt-auto space-y-4 border-t border-white/10 pt-5">{posAvailable ? <Link href={`/brand/${encodeURIComponent(brand.slug)}/pos`} className="flex items-center justify-between rounded-xl bg-white px-3 py-2.5 text-sm font-semibold text-slate-950">Cometa POS <span aria-hidden="true">↗</span></Link> : null}<div className="rounded-xl bg-white/5 px-3 py-3"><div className="flex items-center gap-2 text-xs font-semibold text-slate-300"><span className="h-2 w-2 rounded-full bg-emerald-400" /> Centro de crecimiento</div><p className="mt-1 pl-4 text-[11px] text-slate-500">Impulsado por Cometa OS</p></div></div></div></aside>
    {mobileOpen ? <button type="button" aria-label="Cerrar navegación" className="fixed inset-0 z-30 bg-slate-950/30 lg:hidden" onClick={() => setMobileOpen(false)} /> : null}<div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-14 items-center justify-between border-b border-[var(--os-border)] bg-[var(--os-surface)]/95 px-4 backdrop-blur sm:px-8"><div className="flex min-w-0 items-center gap-3"><button type="button" onClick={() => setMobileOpen(true)} className="rounded-lg border border-[var(--os-border)] p-2 text-slate-600 lg:hidden" aria-label="Abrir navegación">☰</button><span className="truncate text-sm font-medium text-[var(--os-text-muted)]">{brand.name}</span></div><div className="flex items-center gap-3"><span className="hidden text-xs font-medium text-[var(--os-text-muted)] sm:inline">Cometa OS</span><div className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-100 text-sm font-semibold text-blue-700" aria-hidden="true">{brand.name.slice(0, 1).toUpperCase()}</div></div></header><main className="min-w-0 px-4 py-6 sm:px-8 sm:py-8 lg:px-10">{children}</main></div>
  </div></div>;
}
