import Link from "next/link";
import { getClientMarketingContent } from "@/lib/marketing/client-marketing";
import { PageHeader, Section, StatusBadge } from "../../components/os-primitives";

export const dynamic = "force-dynamic";

export default async function ContentPage({ params }: { params: Promise<{ brandSlug: string }> }) {
  const { brandSlug } = await params; const items = await getClientMarketingContent(brandSlug); const base = `/brand/${encodeURIComponent(brandSlug)}/os/marketing`;
  const counts = { production: items.filter((item) => ["generated", "internal_review", "assigned", "in_design", "design_uploaded", "approved_internal", "changes_requested"].includes(item.status)).length, review: items.filter((item) => item.status === "sent_to_client").length, approved: items.filter((item) => item.status === "approved_client").length, scheduled: items.filter((item) => item.status === "scheduled").length, published: items.filter((item) => item.status === "published").length };
  return <div className="space-y-6"><PageHeader eyebrow="MARKETING · CONTENIDO" title="Contenido" description="Piezas visibles, revisiones y publicaciones de tu marca." /><div className="grid gap-3 sm:grid-cols-5">{Object.entries(counts).map(([key, value]) => <div key={key} className="os-card-subtle"><p className="text-xs font-semibold capitalize text-slate-500">{key === "review" ? "En revisión" : key === "production" ? "En producción" : key === "published" ? "Publicado" : key === "scheduled" ? "Programado" : "Aprobado"}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><Section title="Biblioteca de contenido"><div className="divide-y divide-slate-200 overflow-hidden rounded-2xl border border-slate-200 bg-white">{items.length ? items.map((item) => <article key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{item.contentType || "Contenido"}{item.platform ? ` · ${item.platform}` : ""}</p></div><div className="flex items-center gap-4"><span className="text-xs text-slate-500">{item.publishDate ? new Intl.DateTimeFormat("es-MX", { dateStyle: "medium" }).format(new Date(item.publishDate)) : "Sin fecha editorial"}</span><StatusBadge label={item.statusLabel} /><Link href={`${base}/calendar`} className="text-xs font-semibold text-blue-700">Ver detalle →</Link></div></article>) : <p className="p-8 text-sm text-slate-500">No hay piezas visibles todavía.</p>}</div></Section></div>;
}
