import Link from "next/link";
import type { ReactNode } from "react";

type RouteName = "pieces" | "recordings" | "resources";
const links: Array<{ href: string; label: string; key: string; icon: string }> = [{ href: "/studio", label: "Inicio", key: "home", icon: "⌂" }, { href: "/studio/operation", label: "Operación", key: "operation", icon: "▷" }, { href: "/studio/pieces", label: "Piezas", key: "pieces", icon: "◈" }, { href: "/studio/changes", label: "Cambios", key: "changes", icon: "✦" }, { href: "/studio/recordings", label: "Grabaciones", key: "recordings", icon: "◉" }, { href: "/studio/resources", label: "Recursos", key: "resources", icon: "▣" }];

export function StudioSubpageShell({ active, userName, changesCount, children }: { active: RouteName; userName: string | null; changesCount: number; children: ReactNode }) {
  return <main className="min-h-screen bg-[#07111f] text-white"><div className="mx-auto grid max-w-[1600px] lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="border-r border-white/[.07] bg-[#081525] p-5 lg:min-h-screen"><div className="text-lg font-semibold tracking-[.28em]">COMETA</div><div className="text-[10px] uppercase tracking-[.25em] text-cyan-300">STUDIO</div><p className="mb-2 mt-10 px-2 text-[10px] uppercase tracking-[.2em] text-slate-600">MI PRODUCCIÓN</p><nav className="space-y-1">{links.map((item) => { const selected = item.key === active; return <Link key={item.href} href={item.href} aria-current={selected ? "page" : undefined} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${selected ? "bg-cyan-300/[.09] text-cyan-100" : "text-slate-300 hover:bg-white/[.06]"}`}><span className={`grid h-6 w-6 place-items-center rounded-lg ${selected ? "bg-cyan-300/15 text-cyan-200" : "bg-white/[.06] text-slate-500"}`}>{item.icon}</span><span>{item.label}</span>{item.key === "changes" && changesCount > 0 && <span className="ml-auto rounded-full bg-rose-400/20 px-2 text-[10px] text-rose-200">{changesCount}</span>}</Link>; })}</nav><div className="mt-10 border-t border-white/10 pt-4"><p className="text-sm text-slate-100">{userName || "Equipo Cometa"}</p><p className="mt-1 text-xs text-slate-500">Producción creativa · Team</p></div></aside><section className="min-w-0 p-5 sm:p-8 lg:p-10">{children}</section></div></main>;
}
