import { StudioSubpageShell } from "@/app/studio/components/studio-subpage-shell";
import { getBrandProductionProfile, type ProductionProfile } from "@/lib/studio/production";
import { getStudioWorkspaceData, requireStudioAccess } from "@/lib/studio/server";

export const dynamic = "force-dynamic";

export default async function ResourcesPage() { const studio = await requireStudioAccess(); const data = await getStudioWorkspaceData(studio); const rows = await Promise.all(data.brands.map(async (brand) => ({ brand: { slug: String(brand.slug), name: String(brand.name) }, profile: await getBrandProductionProfile(String(brand.slug)) }))); const changesCount = data.items.filter((item) => item.status === "changes_requested").length; return <StudioSubpageShell active="resources" userName={studio.fullName || studio.email} changesCount={changesCount}><header><p className="text-[10px] uppercase tracking-[.3em] text-cyan-300">CREATIVE OPERATIONS</p><h1 className="mt-2 text-3xl font-semibold">RECURSOS</h1><p className="mt-2 text-sm text-slate-400">Capacidades de producción confirmadas para tus marcas.</p></header>{rows.length ? <div className="mt-7 grid gap-4 xl:grid-cols-2 2xl:grid-cols-3">{rows.map(({ brand, profile }) => <ResourceCard key={brand.slug} brand={brand} profile={profile} />)}</div> : <div className="mt-8 rounded-3xl border border-dashed border-white/10 p-10 text-center text-sm text-slate-500">No tienes marcas operativas asignadas.</div>}</StudioSubpageShell>; }

function ResourceCard({ brand, profile }: { brand: { slug: string; name: string }; profile: ProductionProfile | null }) { return <article id={brand.slug} className="scroll-mt-8 rounded-3xl border border-white/10 bg-white/[.035] p-5"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-300">{brand.name}</p>{!profile ? <div className="mt-5 rounded-2xl border border-dashed border-white/10 bg-[#091827] p-5 text-sm leading-6 text-slate-400">Esta marca todavía no tiene un perfil de producción configurado.</div> : <div className="mt-5 space-y-5"><Group title="Talento"><ResourceRow icon="◉" label="Modelo Cometa" value={profile.noHumanTalent ? "No autorizado" : profile.agencyModelAllowed ? "Autorizada ✓" : "No confirmado"} tone={profile.agencyModelAllowed && !profile.noHumanTalent ? "yes" : "neutral"} /><ResourceRow icon="◇" label="Modelo del cliente" value={profile.noHumanTalent ? "No autorizado" : profile.clientModelAvailable ? "Permitido ✓" : "No confirmado"} tone={profile.clientModelAvailable && !profile.noHumanTalent ? "yes" : "neutral"} /></Group><Group title="Capacidades"><ResourceRow icon="✋" label="Manos" value={profile.handsAllowed ? "Permitido ✓" : "No autorizado"} tone={profile.handsAllowed ? "yes" : "no"} /><ResourceRow icon="▣" label="Producto solo" value={profile.productOnlyAllowed ? "Permitido ✓" : "No autorizado"} tone={profile.productOnlyAllowed ? "yes" : "no"} /></Group><Group title="Grabación"><ResourceRow icon="⌖" label="Ubicación habitual" value={locationLabel(profile.recordingLocationType)} tone="neutral" /><ResourceRow icon="↗" label="Recoger producto" value={profile.productPickupRequired ? "Sí" : "No"} tone="neutral" />{profile.recordingLocationNotes && <Note text={profile.recordingLocationNotes} />}{profile.usualRecordingNotes && <Note text={profile.usualRecordingNotes} />}</Group>{profile.visualRestrictions && <Group title="Restricciones"><Note text={profile.visualRestrictions} /></Group>}{profile.productionNotes && <Group title="Notas de producción"><Note text={profile.productionNotes} /></Group>}</div>}</article>; }
function Group({ title, children }: { title: string; children: React.ReactNode }) { return <section><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.18em] text-slate-600">{title}</p><div className="space-y-2">{children}</div></section>; }
function ResourceRow({ icon, label, value, tone }: { icon: string; label: string; value: string; tone: "yes" | "no" | "neutral" }) { return <div className="flex items-center gap-3 rounded-xl border border-white/[.07] bg-[#091827] px-3 py-2.5"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white/[.05] text-xs text-cyan-300">{icon}</span><span className="min-w-0 flex-1 text-sm text-slate-300">{label}</span><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${tone === "yes" ? "bg-emerald-300/10 text-emerald-200" : tone === "no" ? "bg-slate-400/10 text-slate-400" : "bg-cyan-300/[.07] text-slate-300"}`}>{value}</span></div>; }
function Note({ text }: { text: string }) { return <p className="rounded-xl border border-white/[.07] bg-[#091827] p-3 text-xs leading-5 text-slate-400">{text}</p>; }
function locationLabel(value: ProductionProfile["recordingLocationType"]) { return value === "client_location" ? "Cliente" : value === "cometa_location" ? "Cometa" : value === "external_location" ? "Externa" : value === "not_applicable" ? "No aplica" : "No confirmado"; }
