"use client";
import { useState } from "react";

type Props = { brandSlug: string; brandName: string; initial: Record<string, unknown> | null };
const arrayKeys = new Set(["objectivesSecondary", "contentPillars", "channels", "campaigns", "successMetrics"]);
export const strategyArrayToTextarea = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").join("\n") : typeof value === "string" ? value : "";
export const strategyTextareaToArray = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
const readValue = (row: Record<string, unknown> | null, key: string) => { const dbKey = key.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`); const value = row?.[dbKey]; return arrayKeys.has(key) ? strategyArrayToTextarea(value) : typeof value === "string" ? value : ""; };

export default function StrategyEditor({ brandSlug, brandName, initial }: Props) {
  const now = new Date();
  const keys = ["objectivePrimary", "objectivesSecondary", "targetAudience", "offerFocus", "strategicFocus", "contentPillars", "channels", "cadence", "tone", "campaigns", "primaryCta", "successMetrics", "nextMilestone", "notesInternal"];
  const [form, setForm] = useState<Record<string, string>>({ periodYear: String(initial?.period_year || now.getFullYear()), periodMonth: String(initial?.period_month || now.getMonth() + 1), version: String(initial?.version || 1), ...Object.fromEntries(keys.map((key) => [key, readValue(initial, key)])) });
  const [status, setStatus] = useState(initial?.status === "published" ? "PUBLICADA" : "BORRADOR INTERNO"); const [message, setMessage] = useState("");
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const payload = (action: string) => ({ ...form, action, strategyId: initial?.id, ...Object.fromEntries([...arrayKeys].map((key) => [key, strategyTextareaToArray(form[key])])) });
  async function save(action = "save") { setMessage("Guardando…"); const response = await fetch(`/api/admin/brands/${encodeURIComponent(brandSlug)}/strategy`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload(action)) }); const result = await response.json(); if (!response.ok) { setMessage(result.error || "No pudimos guardar el borrador generado. Inténtalo nuevamente."); return; } setMessage(action === "publish" ? "Estrategia publicada" : "Borrador guardado"); if (action === "publish") setStatus("PUBLICADA"); }
  async function ai() { setMessage("COSMOS está preparando un borrador…"); const response = await fetch(`/api/admin/brands/${encodeURIComponent(brandSlug)}/strategy`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "generate_ai", strategyId: initial?.id, periodYear: form.periodYear, periodMonth: form.periodMonth }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error === "STRATEGY_CONTEXT_INCOMPLETE" ? "Antes de generar la estrategia necesitamos completar información de la marca." : result.error || "No pudimos guardar el borrador generado. Inténtalo nuevamente."); return; } const row = result.strategy as Record<string, unknown>; setForm((current) => ({ ...current, ...Object.fromEntries(keys.map((key) => { const dbKey = key.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`); const value = row[dbKey]; return [key, arrayKeys.has(key) ? strategyArrayToTextarea(value) : typeof value === "string" ? value : current[key]]; })) })); setStatus("BORRADOR INTERNO"); setMessage("Borrador generado; revisa y publícalo manualmente"); }
  async function newVersion() { const response = await fetch(`/api/admin/brands/${encodeURIComponent(brandSlug)}/strategy`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "new_version", periodYear: form.periodYear, periodMonth: form.periodMonth }) }); const result = await response.json(); if (response.ok) window.location.reload(); else setMessage(result.error || "No se pudo crear la versión"); }
  const labels: Record<string, string> = { objectivePrimary: "Objetivo principal", objectivesSecondary: "Objetivos secundarios", targetAudience: "Público objetivo", offerFocus: "Oferta / productos prioritarios", strategicFocus: "Enfoque estratégico", contentPillars: "Pilares de contenido", channels: "Canales", cadence: "Frecuencia", tone: "Tono", campaigns: "Campañas / promociones", primaryCta: "CTA principal", successMetrics: "Qué vamos a medir", nextMilestone: "Próximo hito", notesInternal: "Notas internas" };
  return <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">ESTRATEGIA · {brandName}</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4 border-b border-white/[.08] pb-6"><div><h1 className="text-3xl font-semibold text-white">Estrategia de marketing</h1><p className="mt-2 text-sm text-slate-400">Periodo {form.periodMonth}/{form.periodYear} · Versión {form.version}</p></div><span className="rounded-full border border-cyan-400/20 bg-cyan-400/10 px-3 py-1.5 text-xs text-cyan-200">{status}</span></div><div className="mt-6 flex flex-wrap gap-3">{status === "PUBLICADA" ? <button onClick={() => void newVersion()} className="rounded-xl border border-cyan-400/30 px-4 py-2 text-sm text-cyan-200">Crear nueva versión</button> : <><button onClick={() => void ai()} className="rounded-xl border border-violet-400/30 px-4 py-2 text-sm text-violet-200">Generar con COSMOS ✦</button><button onClick={() => void save()} className="rounded-xl border border-white/10 px-4 py-2 text-sm text-slate-200">Guardar borrador</button><button onClick={() => void save("publish")} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Publicar estrategia</button></>}</div><div className="mt-8 grid gap-5 md:grid-cols-2">{keys.map((key) => <label key={key} className="block"><span className="text-sm text-slate-200">{labels[key]}</span><textarea disabled={status === "PUBLICADA"} value={form[key]} onChange={(event) => update(key, event.target.value)} rows={key === "notesInternal" ? 4 : arrayKeys.has(key) ? 4 : 2} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none focus:border-cyan-400/50 disabled:opacity-60" /></label>)}</div>{message && <p className="mt-5 text-sm text-cyan-200">{message}</p>}</div>;
}
