"use client";

import { useEffect, useState, type FormEvent } from "react";

type Seller = { id: string; public_name: string; brand_slug: string; status: string; verification_status: string };

export default function ComuAdminPage() {
  const [sellers, setSellers] = useState<Seller[]>([]);
  const [message, setMessage] = useState("");
  const [brandSlug, setBrandSlug] = useState("");
  const [publicName, setPublicName] = useState("");
  async function load() { const response = await fetch("/api/comu/sellers?all=1"); const data = await response.json() as { sellers?: Seller[]; error?: string }; if (!response.ok) setMessage(data.error || "No se pudo cargar sellers."); setSellers(data.sellers || []); }
  useEffect(() => { void load(); }, []);
  async function action(sellerId: string, actionName: string) { const response = await fetch("/api/comu/sellers", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, action: actionName }) }); const data = await response.json() as { ok?: boolean; error?: string; code?: string }; setMessage(data.ok ? "Seller actualizado." : data.error || data.code || "No se pudo actualizar."); void load(); }
  async function createSeller(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/comu/sellers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ brandSlug, publicName }) }); const data = await response.json() as { ok?: boolean; error?: string; code?: string }; setMessage(data.ok ? "Seller creado." : data.error || data.code || "No se pudo crear."); if (data.ok) { setBrandSlug(""); setPublicName(""); void load(); } }
  return <main className="mx-auto max-w-6xl px-5 py-12"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">COMU admin</p><h1 className="mt-3 text-5xl font-black tracking-[-.07em]">Sellers y publicaciones</h1>{message ? <p className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold">{message}</p> : null}<form onSubmit={createSeller} className="mt-8 grid gap-3 rounded-3xl bg-white p-6 sm:grid-cols-[1fr_1fr_auto]"><input required value={brandSlug} onChange={(event) => setBrandSlug(event.target.value)} placeholder="brand slug" className="min-h-11 rounded-xl border border-black/10 px-4" /><input required value={publicName} onChange={(event) => setPublicName(event.target.value)} placeholder="Nombre público" className="min-h-11 rounded-xl border border-black/10 px-4" /><button className="rounded-full bg-[#17201d] px-5 py-2 text-sm font-bold text-white">Crear seller</button></form><div className="mt-10 overflow-hidden rounded-3xl bg-white"><div className="grid grid-cols-[1.4fr_1fr_1fr_auto] gap-4 border-b border-black/5 p-5 text-xs font-black uppercase tracking-wide text-slate-500"><span>Seller</span><span>Brand</span><span>Estado</span><span>Acciones</span></div>{sellers.map((seller) => <div key={seller.id} className="grid grid-cols-[1.4fr_1fr_1fr_auto] items-center gap-4 border-b border-black/5 p-5"><div><p className="font-black">{seller.public_name}</p><p className="text-xs text-slate-500">{seller.verification_status}</p></div><span className="text-sm">{seller.brand_slug}</span><span className="text-sm font-bold">{seller.status}</span><div className="flex gap-2">{seller.verification_status !== "VERIFIED" ? <button onClick={() => void action(seller.id, "verify")} className="rounded-full border border-black/10 px-3 py-2 text-xs font-bold">Verificar</button> : null}{seller.status !== "ACTIVE" ? <button onClick={() => void action(seller.id, "activate")} className="rounded-full bg-[#17201d] px-3 py-2 text-xs font-bold text-white">Activar</button> : null}</div></div>)}{!sellers.length ? <p className="p-8 text-center text-sm text-slate-500">No hay sellers registrados.</p> : null}</div></main>;
}
