// LEGAL_REVIEW_REQUIRED / LEGAL_REVIEW_REQUIRED_BEFORE_PUBLIC_LAUNCH
// Operational V1 copy from COMU product rules. No representation of legal approval.
export const policies = {
  terms: { title: "Términos y condiciones", intro: "Un espacio de encuentro entre marcas y compradores. Estas son las reglas para participar.", sections: [
    ["Nuestro papel", "COMU facilita el descubrimiento de productos y la operación de compras entre compradores y tiendas. Cada tienda es responsable de la información, disponibilidad y calidad de los productos que publica. COMU coordina las herramientas de cuenta, pedidos y seguimiento disponibles en la plataforma."],
    ["Tu cuenta y tus compras", "Usa información correcta y conserva el acceso a tu cuenta. Antes de comprar, revisa variante, cantidad, dirección, precio y condiciones de la tienda. Una selección en el carrito no confirma una compra. La confirmación del pedido y su estado aparecen en tu cuenta."],
    ["Pagos, cancelaciones y disputas", "Los pagos se procesan con Stripe. El importe y las condiciones de envío deben estar confirmados antes de completar una compra. Las cancelaciones dependen del avance del pedido; una solicitud no equivale a una cancelación o reembolso aprobado. Conserva el folio y la evidencia para cualquier aclaración."],
    ["Uso de la comunidad", "No publiques contenido engañoso, productos prohibidos, información ajena sin autorización ni material que vulnere derechos de terceros. No uses cuentas o reseñas para simular operaciones, suplantar personas o cometer fraude. Una cuenta o publicación puede quedar en revisión ante incumplimientos."],
  ] },
  privacy: { title: "Privacidad", intro: "Información clara sobre los datos necesarios para tu experiencia en COMU.", sections: [
    ["Cuenta y actividad", "COMU utiliza los datos de tu cuenta, contacto y pedidos para identificarte, mostrar tus compras y permitir la operación de la plataforma. Las direcciones se utilizan para organizar entregas. Los favoritos y preferencias, cuando estén disponibles, se vinculan a tu cuenta."],
    ["Tiendas y entregas", "La información necesaria para preparar y entregar un pedido puede compartirse con la tienda y los servicios que participan en esa entrega. La dirección conservada en un pedido corresponde a la registrada al realizar la compra."],
    ["Pagos y seguridad", "Stripe procesa la información de pago. COMU no almacena el número completo de tarjeta ni su código de seguridad. La información de una cuenta se consulta mediante acceso autenticado y permisos; protege tus credenciales y evita compartir tu sesión."],
    ["Control de tu información", "Puedes consultar tu perfil y las direcciones guardadas desde tu cuenta. Eliminar una dirección guardada no modifica los datos históricos de un pedido. Para una aclaración relacionada con una compra, identifica el pedido y utiliza los canales de contacto publicados por la tienda. Las solicitudes sobre tratamiento de datos requieren validación de identidad y revisión del caso."],
  ] },
  returns: { title: "Devoluciones", intro: "Si algo no salió como esperabas, empieza por documentarlo. Cada solicitud se revisa con cuidado.", sections: [
    ["Cuatro días para reportar", "La regla de satisfacción COMU contempla 4 días después de la entrega para reportar una inconformidad. Conserva el folio, el empaque y la pieza mientras se revisa tu solicitud. Describe qué recibiste y qué no coincide con tu pedido."],
    ["Evidencia y revisión", "Incluye fotografías claras del producto, empaque y problema reportado. Según el caso puede requerirse evidencia adicional o devolución física. No envíes la pieza sin recibir instrucciones sobre el procedimiento y destino."],
    ["Responsabilidad de la tienda", "La tienda debe revisar las incidencias vinculadas a calidad, producto incorrecto o faltantes y colaborar con la resolución. El valor de la compra, la evidencia y las circunstancias se evalúan individualmente; no existe una aprobación automática por importe."],
    ["Resolución y reembolso", "Reportar un problema no ejecuta un reembolso automático. La resolución depende de la revisión de la solicitud. Si se autoriza un reembolso, su reflejo depende del medio de pago y la entidad financiera. Las solicitudes inconsistentes, duplicadas o con indicios de fraude requieren revisión adicional."],
  ] },
  shipping: { title: "Envíos", intro: "Desde la tienda o pasando por nuestro centro de consolidación: cada pedido tiene su propio recorrido.", sections: [
    ["Desde la tienda", "En el envío directo, la tienda prepara y despacha tus piezas desde su ubicación. La disponibilidad del servicio depende del origen, destino y características del paquete."],
    ["A través del centro COMETA", "En el flujo con centro de consolidación, las tiendas entregan sus piezas a COMETA para reunir y preparar el envío. Un pedido con varias tiendas puede requerir más de una etapa de preparación."],
    ["Preparación y seguimiento", "Los plazos de preparación se calculan según la confirmación del pedido y los días de operación. El corte operativo entre semana es a las 14:00; los sábados, a las 12:00, hora de Ciudad de México. Estos cortes no son una promesa de entrega al comprador. Consulta el avance del pedido y la guía cuando esté disponible."],
    ["Costo y dirección", "El costo debe confirmarse antes de completar la compra. No se presume envío gratuito ni una tarifa universal. Revisa la dirección y los datos de contacto; una incidencia de entrega puede requerir aclaraciones. Una selección sin una cotización válida no permite continuar con la compra."],
  ] },
  "seller-guidelines": { title: "Lineamientos para vendedores", intro: "Una comunidad de marcas con información clara, stock real y atención responsable.", sections: [
    ["Verificación y catálogo", "Solicita tu verificación antes de operar como tienda. Publica productos propios o que estés autorizado a comercializar, con fotografías fieles, descripción, variantes y precios correctos. No publiques artículos prohibidos, falsificaciones ni contenido que infrinja derechos de terceros."],
    ["Inventario y mayoreo", "Mantén actualizado el inventario compartido con tu operación POS. Configura de forma clara los mínimos y condiciones de mayoreo. No prometas existencias que no puedes surtir ni alteres una compra confirmada mediante cambios posteriores al catálogo."],
    ["Pedidos y entregas", "Prepara cada pedido dentro de sus plazos y según la ruta asignada: entrega directa o entrega al centro COMETA. Documenta faltantes, errores y daños. Colabora en devoluciones y disputas; los incumplimientos pueden provocar revisión de la cuenta y medidas operativas según el caso."],
    ["Modelo comercial y pagos", "COMU cobra 0% de comisión por venta. La presentación comercial vigente ofrece COMU Basic por $399 MXN al mes y COMU Pro por $599 MXN al mes, ambos sin comisión COMU por venta. El procesamiento de pagos de Stripe puede generar su costo correspondiente, separado de la renta COMU. La configuración de pagos y la verificación no garantizan liquidaciones inmediatas; su disponibilidad depende del estado del pedido y las reglas financieras aplicables."],
  ] },
} as const;
