import Link from "next/link";
import type { ReactNode } from "react";
import { CommerceProvider, CartLink } from "./components/commerce";
import "./marketplace.css";

const footerLinks = [["Catálogo", "/comu/search"], ["Ropa", "/comu/search?q=ropa"], ["Accesorios", "/comu/search?q=accesorios"], ["Comprar para tu negocio", "/comu/search?mode=wholesale"], ["Vende en COMU", "/comu/sell"], ["Términos", "/comu/legal/terms"], ["Privacidad", "/comu/legal/privacy"], ["Devoluciones", "/comu/legal/returns"], ["Envíos", "/comu/legal/shipping"], ["Lineamientos vendedores", "/comu/legal/seller-guidelines"]];
export default function ComuLayout({ children }: { children: ReactNode }) {
  return <div className="comu-market min-h-screen"><CommerceProvider><a href="#comu-content" className="sr-only focus:not-sr-only focus:block focus:p-4">Saltar al contenido</a><header className="sticky top-0 z-40 border-b border-[#d9cfc4]/70 bg-[#f8f5f0]/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-3 px-5 py-4"><Link aria-label="COMU inicio" href="/comu" className="mr-auto text-3xl font-black tracking-[-.1em]">COMU<span className="text-[#b58a68]">.</span></Link><nav aria-label="Navegación principal" className="order-3 flex w-full gap-5 overflow-x-auto whitespace-nowrap py-1 text-xs font-semibold sm:text-sm lg:order-none lg:w-auto lg:gap-6"><Link href="/comu/search">Explorar</Link><Link href="/comu/search?mode=wholesale">Para tu negocio</Link><Link href="/comu/sell">Vende en COMU</Link></nav><form action="/comu/search" role="search" className="order-last w-full lg:order-none lg:ml-5 lg:w-56"><input aria-label="Buscar en COMU" name="q" placeholder="Encuentra tu próxima pieza" className="w-full rounded-full border border-[#d9cfc4] bg-[#fffdf9] px-4 py-2.5 text-sm" /></form><CartLink /><Link href="/comu/account" className="comu-button !px-4 !py-2.5">Cuenta</Link></div></header><div id="comu-content">{children}</div><footer className="mt-20 bg-[#252d28] px-5 py-14 text-[#eee7dd]"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1fr_2fr]"><div><Link href="/comu" className="text-3xl font-black tracking-[-.1em]">COMU.</Link><p className="mt-5 text-xl">Moda real. Más tuya.</p><p className="mt-3 max-w-xs text-sm leading-6 text-[#c4c5be]">Un espacio para descubrir marcas y hacer crecer el comercio mexicano.</p></div><nav aria-label="Enlaces del pie" className="grid grid-cols-2 gap-x-8 gap-y-4 text-sm md:grid-cols-3">{footerLinks.map(([title, href]) => <Link key={href} href={href}>{title}</Link>)}</nav></div><div className="mx-auto mt-12 flex max-w-7xl justify-between border-t border-white/15 pt-6 text-xs text-[#c4c5be]"><Link href="/comu/legal">Centro legal</Link><span>Powered by COMETA</span></div></footer></CommerceProvider></div>;
}
