import Link from "next/link";
import { getPublicCatalog } from "@/lib/comu/public-catalog";
import { isComuFeatureEnabled } from "@/lib/comu/features";
import { EditorialCard, EmptyState, ModeSwitch, PlaceholderProduct, ProductCard, SectionHeading, SellerCard, type PublicListing } from "./components/public-ui";

export default async function ComuHome({ searchParams }: { searchParams: Promise<{ mode?: string }> }) {
  const { mode } = await searchParams;
  const enabled = isComuFeatureEnabled("enabled") && isComuFeatureEnabled("catalog");
  const listings = (enabled ? await getPublicCatalog() : []) as PublicListing[];
  const sellers = [...new Map(listings.filter((item) => item.seller).map((item) => [item.seller?.slug, item.seller])).values()].filter(Boolean) as NonNullable<PublicListing["seller"]>[];
  const hero = listings[0];
  const heroImage = hero?.media?.find((item) => item.is_primary)?.public_url || hero?.product?.image_url;
  return <main>
    <section className="mx-auto max-w-7xl px-5 pb-16 pt-8 md:pb-24 md:pt-12"><div className="grid overflow-hidden rounded-[2.5rem] bg-[#d8c5b1] md:grid-cols-[.9fr_1.1fr]"><div className="flex flex-col justify-between p-7 md:p-12 lg:p-16"><div><p className="text-[11px] font-black uppercase tracking-[.25em] text-[#735b49]">El marketplace textil de Mexico</p><h1 className="mt-6 max-w-xl text-5xl font-black leading-[.88] tracking-[-.08em] text-[#252d28] md:text-7xl">Moda real<br />para un mundo<br />mas tuyo.</h1><p className="mt-6 max-w-lg text-lg leading-7 text-[#5d5045]">Descubre marcas independientes, fabricantes y piezas unicas. Compra directo, para ti o para hacer crecer tu negocio.</p></div><div className="mt-10"><ModeSwitch mode={mode} /><div className="mt-5 flex flex-wrap gap-3"><Link href="/comu/search" className="rounded-full bg-[#252d28] px-6 py-3 text-sm font-bold text-white shadow-lg shadow-[#252d28]/15">Explorar productos</Link><Link href="/comu" className="rounded-full border border-[#8f7863]/40 bg-white/25 px-6 py-3 text-sm font-bold text-[#40342c]">Conoce COMU</Link></div></div></div><div className="relative min-h-[25rem] overflow-hidden bg-[#2d3731] md:min-h-[36rem]">{heroImage ? <img src={heroImage} alt="" className="h-full w-full object-cover opacity-90" /> : <div className="absolute inset-0 bg-[linear-gradient(145deg,#303a34_5%,#ab886c_48%,#dfcbb5_100%)]"><div className="absolute right-8 top-8 h-40 w-28 rotate-12 rounded-[5rem] border border-white/30" /><div className="absolute bottom-10 left-10 h-52 w-36 -rotate-12 rounded-[6rem] border border-white/25" /><div className="absolute left-1/2 top-1/3 h-56 w-40 -translate-x-1/2 rounded-[8rem] border border-white/20" /></div>}<div className="absolute left-6 top-6 rounded-full border border-white/25 bg-black/10 px-3 py-2 text-[10px] font-black uppercase tracking-[.15em] text-white/75">Piezas que conectan</div><div className="absolute inset-x-6 bottom-6 flex items-end justify-between gap-5 text-white"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-white/70">{hero?.seller?.public_name || "Selección editorial"}</p><p className="mt-2 max-w-xs text-2xl font-black leading-none tracking-[-.04em]">Moda que conecta.</p></div><span className="hidden rounded-full border border-white/30 bg-black/15 px-3 py-2 text-xs font-bold sm:block">Personas · Negocios · Historias</span></div></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-3 px-5 pb-20 sm:grid-cols-3"><div className="rounded-2xl bg-[#fffdf9] p-5"><p className="text-lg">✦</p><p className="mt-5 font-black">Marcas verificadas</p><p className="mt-1 text-sm text-[#8b8178]">Compra con confianza.</p></div><div className="rounded-2xl bg-[#fffdf9] p-5"><p className="text-lg">↗</p><p className="mt-5 font-black">Envíos a todo Mexico</p><p className="mt-1 text-sm text-[#8b8178]">Rapido y seguro.</p></div><div className="rounded-2xl bg-[#fffdf9] p-5"><p className="text-lg">♡</p><p className="mt-5 font-black">Apoya lo real</p><p className="mt-1 text-sm text-[#8b8178]">Negocios que impulsan Mexico.</p></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-24"><SectionHeading eyebrow="Nuevos lanzamientos" title="Lo nuevo, lo que vale la pena mirar" href="/comu/search" link="Ver todo" />{listings.length ? <div className="mt-9 grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{listings.slice(0, 5).map((listing, index) => <ProductCard key={listing.id} listing={listing} featured={index === 0} />)}</div> : <div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><PlaceholderProduct name="Camisa de lino" detail="Texturas para todos los días" tone="sand" /><PlaceholderProduct name="Bolsa de piel" detail="Hecho con oficio" tone="clay" /><PlaceholderProduct name="Chaleco tejido" detail="Una nueva mirada" tone="olive" /><PlaceholderProduct name="Piezas por llegar" detail="La selección está creciendo" tone="ink" /></div>}</section>
    <section className="bg-[#eee7de] py-20"><div className="mx-auto max-w-7xl px-5"><SectionHeading eyebrow="Tiendas verificadas" title="Marcas que tienen algo que decir" href="/comu/search" link="Ver todas las tiendas" />{sellers.length ? <div className="mt-9 grid gap-5 md:grid-cols-3">{sellers.slice(0, 3).map((seller) => <SellerCard key={seller.slug} seller={seller} />)}</div> : <div className="mt-8"><EmptyState title="Muy pronto: tiendas verificadas." body="Estamos curando una comunidad de fabricantes, talleres y marcas con capacidad real de surtido." /></div>}</div></section>
    <section className="mx-auto max-w-7xl px-5 py-24"><div className="grid gap-8 overflow-hidden rounded-[2rem] bg-[#252d28] p-8 text-[#f5f0e9] md:grid-cols-[1fr_.8fr] md:p-14"><div><p className="text-[11px] font-black uppercase tracking-[.24em] text-[#d5b99b]">Compra para tu negocio</p><h2 className="mt-5 max-w-xl text-4xl font-black leading-none tracking-[-.07em] md:text-6xl">Para vestirte. Para surtir. Para crecer.</h2><p className="mt-6 max-w-lg leading-7 text-white/65">Accede a precios de mayoreo, conecta con fabricantes verificados y haz crecer tu marca.</p><Link href="/comu?mode=wholesale" className="mt-8 inline-flex rounded-full bg-[#d6b796] px-6 py-3 text-sm font-black text-[#252d28]">Explorar proveedores</Link></div><div className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-3xl border border-white/10 bg-white/5 p-5"><p className="text-3xl font-black">01</p><p className="mt-14 text-white/65">Fabricantes mexicanos</p></div><div className="mt-10 rounded-3xl border border-white/10 bg-[#d6b796] p-5 text-[#252d28]"><p className="text-3xl font-black">02</p><p className="mt-14 text-[#544435]">Precios de mayoreo</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-24"><div className="grid gap-8 md:grid-cols-3"><div className="md:col-span-2"><p className="text-[11px] font-black uppercase tracking-[.24em] text-[#8b7564]">Una nueva forma de descubrir</p><h2 className="mt-4 max-w-2xl text-4xl font-black leading-none tracking-[-.07em] md:text-6xl">Del taller a tu closet. Del fabricante a tu negocio.</h2></div><p className="self-end text-lg leading-7 text-[#776b61]">COMU conecta talento textil, piezas con identidad y personas que quieren comprar mejor.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-3"><Link href="/comu/search?q=ropa" className="rounded-[1.5rem] bg-[#d9c4ae] p-7 text-2xl font-black tracking-[-.04em] text-[#3e332a]">Ropa <span className="float-right">↗</span></Link><Link href="/comu/search?q=accesorios" className="rounded-[1.5rem] bg-[#dfe4d9] p-7 text-2xl font-black tracking-[-.04em] text-[#344139]">Accesorios <span className="float-right">↗</span></Link><Link href="/comu/search?mode=wholesale" className="rounded-[1.5rem] bg-[#252d28] p-7 text-2xl font-black tracking-[-.04em] text-white">Mayoreo <span className="float-right">↗</span></Link></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-24"><SectionHeading eyebrow="Historias que inspiran" title="Personas, procesos y perspectivas" href="/comu/search" link="Ver más historias" /><div className="mt-9 grid gap-5 md:grid-cols-3"><EditorialCard eyebrow="Detrás de una marca" title="El oficio de hacer algo que dure." tone="sand" /><EditorialCard eyebrow="Para empezar" title="Cómo iniciar tu marca textil." tone="olive" /><EditorialCard eyebrow="Hecho aquí" title="El poder de lo local." tone="clay" /></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-28"><div className="rounded-[2rem] border border-[#d9cfc4] bg-[#fffdf9] px-7 py-12 md:flex md:items-center md:justify-between md:gap-12 md:px-14"><div><p className="text-[11px] font-black uppercase tracking-[.24em] text-[#8b7564]">Vende en COMU</p><h2 className="mt-4 max-w-2xl text-4xl font-black leading-none tracking-[-.07em]">Tu catálogo merece llegar más lejos.</h2><p className="mt-5 max-w-xl leading-7 text-[#776b61]">Conecta tu negocio, publica tus piezas y llega a personas que valoran lo que haces.</p></div><Link href="/comu/seller" className="mt-8 inline-flex shrink-0 rounded-full bg-[#252d28] px-6 py-3 text-sm font-bold text-white md:mt-0">Conoce COMU para sellers</Link></div></section>
  </main>;
}
