import { PosApiError, assertDatabaseResult, getBrandSlugFromUrl, handlePosError, ok, readJsonBody, uuidValue } from "@/lib/pos/server";
import { requirePosOperationalAccess } from "@/lib/pos/access";
import { PULSAR_MODEL,PULSAR_PROMPT_VERSION,PULSAR_SCHEMA_VERSION,generatePulsarReport,hashPulsarInput,insufficientDataReport,type PulsarInput } from "@/lib/pos/pulsar";

export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=60;
const TYPES=new Set(["daily","weekly","monthly","manual"]);

export async function GET(request:Request){try{const brandSlug=getBrandSlugFromUrl(request);const{admin,brand}=await requirePosOperationalAccess({brandSlug,entitlement:"intelligence.pulsar"});const url=new URL(request.url);const view=url.searchParams.get("view")||"latest";const locationId=parseLocation(url.searchParams.get("locationId"));let data:unknown,error:unknown;
 if(view==="latest")({data,error}=await admin.rpc("pos_get_latest_intelligence_report",{p_brand_slug:brand.slug,p_location_id:locationId}));
 else if(view==="history")({data,error}=await admin.rpc("pos_get_intelligence_reports",{p_brand_slug:brand.slug,p_location_id:locationId,p_limit:integer(url.searchParams.get("limit"),20,1,100),p_offset:integer(url.searchParams.get("offset"),0,0,10000)}));
 else if(view==="report"){const id=uuidValue(url.searchParams.get("id"),"id",true);({data,error}=await admin.rpc("pos_get_intelligence_report",{p_brand_slug:brand.slug,p_report_id:id}));}
 else throw new PosApiError(400,"POS_PULSAR_INVALID_VIEW","La vista PULSAR no es válida.");assertDatabaseResult(asDbError(error),"No se pudo cargar PULSAR.");return ok({view,report:data});
 }catch(error){return pulsarError(error,"No se pudo cargar PULSAR.")}}

export async function POST(request:Request){try{const brandSlug=getBrandSlugFromUrl(request);const{admin,brand}=await requirePosOperationalAccess({brandSlug,entitlement:"intelligence.pulsar"});const body=await readJsonBody<Record<string,unknown>>(request);if(body.action!=="generate")throw new PosApiError(400,"POS_PULSAR_INVALID_ACTION","La acción PULSAR no es válida.");const reportType=typeof body.reportType==="string"?body.reportType:"manual";if(!TYPES.has(reportType))throw new PosApiError(400,"POS_PULSAR_INVALID_PERIOD","El tipo de periodo no es válido.");const from=date(body.dateFrom,"dateFrom"),to=date(body.dateTo,"dateTo");if(to<=from)throw new PosApiError(400,"POS_PULSAR_INVALID_PERIOD","El periodo no es válido.");const locationId=parseLocation(typeof body.locationId==="string"?body.locationId:null);
 const args={p_brand_slug:brand.slug,p_date_from:from.toISOString(),p_date_to:to.toISOString(),p_location_id:locationId};
 const [summary,products,customers,inventory,loyalty,quality,signals]=await Promise.all([rpc(admin,"pos_get_analytics_summary",args),rpc(admin,"pos_get_analytics_products",{...args,p_limit:10,p_order_by:"sales_total"}),rpc(admin,"pos_get_analytics_customers",{...args,p_limit:10}),rpc(admin,"pos_get_analytics_inventory",args),rpc(admin,"pos_get_analytics_loyalty",args),rpc(admin,"pos_get_analytics_data_quality",args),rpc(admin,"pos_get_intelligence_signals",{p_brand_slug:brand.slug,p_location_id:locationId,p_status:"open",p_category:null,p_severity:null,p_limit:20,p_offset:0})]);
 const signalRows=isObject(signals)&&Array.isArray(signals.signals)?signals.signals.slice(0,20):[];const inventoryRows=Array.isArray(inventory)?inventory:[];const input:PulsarInput={business:{name:brand.name,industry:brand.industry||undefined,locationId},period:{reportType,periodStart:from.toISOString(),periodEnd:to.toISOString()},sales:isObject(summary)?summary.sales:{},customers:{summary:isObject(summary)?summary.customers:{},top:Array.isArray(customers)?customers.slice(0,10):[]},products:Array.isArray(products)?products.slice(0,10):[],inventory:{summary:summarizeInventory(inventoryRows),risks:inventoryRows.filter(isInventoryRisk).slice(0,10)},loyalty,dataQuality:quality,signals:signalRows};const inputHash=hashPulsarInput(input);
 const existing=await admin.from("pos_intelligence_reports").select("*").eq("brand_slug",brand.slug).eq("report_type",reportType).eq("period_start",from.toISOString()).eq("period_end",to.toISOString()).eq("input_hash",inputHash).eq("prompt_version",PULSAR_PROMPT_VERSION).eq("model",PULSAR_MODEL).eq("generation_status","completed").order("generated_at",{ascending:false}).limit(1).maybeSingle();assertDatabaseResult(existing.error,"No se pudo comprobar la idempotencia PULSAR.");if(existing.data)return ok({report:existing.data,idempotentReplay:true});
 const completedSales=isObject(summary)&&isObject(summary.sales)?number(summary.sales.completedSalesCount):0;const generated=completedSales<5?insufficientDataReport():await generatePulsarReport(input);const saved=await rpc(admin,"pos_create_intelligence_report_record",{p_brand_slug:brand.slug,p_location_id:locationId,p_report_type:reportType,p_period_start:from.toISOString(),p_period_end:to.toISOString(),p_analytics_snapshot_id:null,p_signals_snapshot:signalRows,p_input_snapshot:input,p_executive_summary:generated.executiveSummary,p_health_status:generated.businessHealth.status,p_health_score:null,p_findings:generated.findings,p_opportunities:generated.opportunities,p_risks:generated.risks,p_hypotheses:generated.hypotheses,p_recommended_actions:generated.recommendedActions,p_data_quality_notes:generated.dataQualityNotes,p_model:PULSAR_MODEL,p_prompt_version:PULSAR_PROMPT_VERSION,p_schema_version:PULSAR_SCHEMA_VERSION,p_input_hash:inputHash});return ok({report:saved,idempotentReplay:false});
 }catch(error){return pulsarError(error,"No se pudo generar el análisis. Tus reportes siguen disponibles.")}}

type DbError={message?:string;details?:string;hint?:string};
type Admin={rpc:(name:string,args:Record<string,unknown>)=>PromiseLike<{data:unknown;error:DbError|null}>};
async function rpc(admin:Admin,name:string,args:Record<string,unknown>){const{data,error}=await admin.rpc(name,args);assertDatabaseResult(error,`Falló ${name}.`);return data}
function date(value:unknown,name:string){if(typeof value!=="string")throw new PosApiError(400,"POS_PULSAR_INVALID_PERIOD",`${name} es obligatorio.`);const d=new Date(value);if(Number.isNaN(d.getTime()))throw new PosApiError(400,"POS_PULSAR_INVALID_PERIOD",`${name} no es válido.`);return d}
function parseLocation(value:string|null){try{return uuidValue(value,"locationId",false)}catch{throw new PosApiError(400,"POS_PULSAR_INVALID_LOCATION","La sucursal no es válida.")}}
function integer(value:string|null,fallback:number,min:number,max:number){if(!value)return fallback;const n=Number(value);if(!Number.isInteger(n)||n<min||n>max)throw new PosApiError(400,"POS_PULSAR_INVALID_PAGINATION","La paginación no es válida.");return n}
function isObject(v:unknown):v is Record<string,unknown>{return!!v&&typeof v==="object"&&!Array.isArray(v)}
function asDbError(v:unknown):DbError|null{return isObject(v)?{message:typeof v.message==="string"?v.message:undefined,details:typeof v.details==="string"?v.details:undefined,hint:typeof v.hint==="string"?v.hint:undefined}:null}
function number(v:unknown){return typeof v==="number"&&Number.isFinite(v)?v:0}
function summarizeInventory(rows:unknown[]){let out=0,below=0,value=0;for(const row of rows)if(isObject(row)){const available=number(row.availableQuantity),minimum=number(row.minimumQuantity);value+=number(row.inventoryCostValue);if(available<=0)out++;else if(minimum>0&&available<=minimum)below++}return{trackedRows:rows.length,outOfStock:out,belowMinimum:below,inventoryValue:value}}
function isInventoryRisk(v:unknown){return isObject(v)&&(number(v.availableQuantity)<=number(v.minimumQuantity)||(typeof v.daysOfStockEstimate==="number"&&v.daysOfStockEstimate<=7))}
function pulsarError(error:unknown,message:string){if(error instanceof PosApiError)return handlePosError(error);console.error("PULSAR error",{message:error instanceof Error?error.message:"unknown"});return handlePosError(new PosApiError(500,"POS_PULSAR_GENERATION_FAILED",message))}
