"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";

type AttentionItem = { pieceId: string; brandName: string; title: string; contentType: string | null; status: string; updatedAt: string | null; latestChangeAt: string | null; changeSource: "client" | "internal" | null; reviewDecision: string | null; reviewUpdatedAt: string | null };
type Snapshot = { asOf: string; fingerprint: string; counts: { changes: number; assigned: number; readyForReview: number }; attentionItems: AttentionItem[] };
export type StudioLiveEvent = { id: string; type: "client_change" | "internal_change" | "new_assignment" | "client_approved"; pieceId: string; brandName: string; title: string; occurredAt: string; href: string };
const AUTO_REFRESH_ROUTES = new Set(["/studio", "/studio/changes", "/studio/pieces", "/studio/recordings", "/studio/resources"]);

export function detectStudioLiveEvents(previous: Snapshot, current: Snapshot): StudioLiveEvent[] { const before = new Map(previous.attentionItems.map((item) => [item.pieceId, item])); const events: StudioLiveEvent[] = []; for (const item of current.attentionItems) { const old = before.get(item.pieceId); const enteredChanges = item.status === "changes_requested" && (old?.status !== "changes_requested" || old.latestChangeAt !== item.latestChangeAt || old.changeSource !== item.changeSource); if (enteredChanges) { const type = item.changeSource === "client" ? "client_change" : "internal_change"; events.push(event(type, item, item.latestChangeAt || item.updatedAt || current.asOf)); continue; } if (!old) { events.push(event("new_assignment", item, item.updatedAt || current.asOf)); continue; } if (item.status === "approved_client" && old.status !== "approved_client") events.push(event("client_approved", item, item.reviewUpdatedAt || item.updatedAt || current.asOf)); } return events.sort((a, b) => priority(a.type) - priority(b.type)); }
function event(type: StudioLiveEvent["type"], item: AttentionItem, occurredAt: string): StudioLiveEvent { return { id: `${type}:${item.pieceId}:${occurredAt}`, type, pieceId: item.pieceId, brandName: item.brandName, title: item.title, occurredAt, href: type === "client_change" || type === "internal_change" ? `/studio/pieces/${encodeURIComponent(item.pieceId)}` : `/studio/pieces/${encodeURIComponent(item.pieceId)}` }; }
function priority(type: StudioLiveEvent["type"]) { return type === "client_change" ? 1 : type === "internal_change" ? 2 : type === "new_assignment" ? 3 : 4; }

export function StudioLiveController() {
  const pathname = usePathname(); const router = useRouter(); const snapshot = useRef<Snapshot | null>(null); const inFlight = useRef(false); const lastStartedAt = useRef(0);
  const [notifications, setNotifications] = useState<Array<StudioLiveEvent & { read: boolean }>>([]); const [toast, setToast] = useState<StudioLiveEvent | null>(null); const [open, setOpen] = useState(false); const [updateAvailable, setUpdateAvailable] = useState(false); const [changesCount, setChangesCount] = useState<number | null>(null);
  const check = useCallback(async () => { if (document.visibilityState !== "visible" || navigator.onLine === false || inFlight.current || Date.now() - lastStartedAt.current < 750) return; inFlight.current = true; lastStartedAt.current = Date.now(); try { const response = await fetch("/api/studio/live", { cache: "no-store" }); if (!response.ok) return; const current = await response.json() as Snapshot; const previous = snapshot.current; snapshot.current = current; setChangesCount(current.counts.changes); if (!previous) return; if (previous.fingerprint === current.fingerprint) return; const events = detectStudioLiveEvents(previous, current); if (events.length) { setNotifications((existing) => [...events.map((item) => ({ ...item, read: false })), ...existing].slice(0, 30)); setToast(events[0]); } if (AUTO_REFRESH_ROUTES.has(pathname)) { router.refresh(); setUpdateAvailable(false); } else setUpdateAvailable(true); } catch { /* The next cycle retries without disrupting Studio. */ } finally { inFlight.current = false; } }, [pathname, router]);
  useEffect(() => { const kickoff = window.setTimeout(() => { void check(); }, 0); const timer = window.setInterval(() => { void check(); }, 15_000); const focus = () => { void check(); }; const visibility = () => { if (document.visibilityState === "visible") void check(); }; const online = () => { void check(); }; window.addEventListener("focus", focus); window.addEventListener("online", online); document.addEventListener("visibilitychange", visibility); return () => { window.clearTimeout(kickoff); window.clearInterval(timer); window.removeEventListener("focus", focus); window.removeEventListener("online", online); document.removeEventListener("visibilitychange", visibility); }; }, [check]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 7_000); return () => window.clearTimeout(timer); }, [toast]);
  const unread = notifications.filter((item) => !item.read).length;
  function refreshNow() { router.refresh(); setUpdateAvailable(false); }
  function markAllRead() { setNotifications((items) => items.map((item) => ({ ...item, read: true }))); }
  return <>{updateAvailable && <div className="fixed left-1/2 top-4 z-[70] flex -translate-x-1/2 items-center gap-3 rounded-2xl border border-cyan-300/25 bg-[#0b1b2c]/95 px-4 py-3 text-sm text-slate-200 shadow-2xl backdrop-blur"><span>Hay información nueva disponible.</span><button onClick={refreshNow} className="font-semibold text-cyan-300">Actualizar</button></div>}
    {toast && <div className="fixed right-5 top-5 z-[65] w-[min(360px,calc(100vw-2.5rem))] rounded-2xl border border-cyan-300/20 bg-[#0a1829]/95 p-4 shadow-2xl backdrop-blur"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-300">{eventLabel(toast.type)}</p><p className="mt-2 text-xs text-slate-400">{toast.brandName}</p><p className="mt-1 line-clamp-2 text-sm font-medium text-white">{toast.title}</p><Link href={toast.href} onClick={() => setToast(null)} className="mt-3 inline-block text-xs font-semibold text-cyan-300">{toast.type.includes("change") ? "Resolver cambios" : "Ver pieza"} →</Link></div>}
    <div className="fixed bottom-5 right-5 z-[60]"><button aria-label="Notificaciones de Studio" onClick={() => { setOpen((value) => !value); if (!open) markAllRead(); }} className="relative grid h-12 w-12 place-items-center rounded-2xl border border-cyan-300/20 bg-[#0a1829]/95 text-lg text-cyan-200 shadow-xl backdrop-blur">♢{unread > 0 && <span className="absolute -right-1 -top-1 min-w-5 rounded-full bg-fuchsia-400 px-1 text-[10px] font-bold leading-5 text-slate-950">{unread}</span>}</button>{changesCount !== null && <Link href="/studio/changes" className="mt-2 block rounded-full bg-rose-400/15 px-2 py-1 text-center text-[10px] text-rose-200">Cambios {changesCount}</Link>}
      {open && <aside className="absolute bottom-16 right-0 w-[min(380px,calc(100vw-2.5rem))] overflow-hidden rounded-3xl border border-white/10 bg-[#081525] shadow-2xl"><header className="flex items-center justify-between border-b border-white/10 p-4"><div><p className="text-xs font-semibold tracking-[.16em] text-white">NOTIFICACIONES</p><p className="mt-1 text-[10px] text-slate-500">Durante esta sesión de Studio</p></div>{notifications.length > 0 && <button onClick={markAllRead} className="text-[10px] text-cyan-300">Marcar leídas</button>}</header><div className="max-h-[420px] overflow-y-auto">{notifications.map((item) => <Link key={item.id} href={item.href} onClick={() => setOpen(false)} className={`block border-b border-white/[.07] p-4 last:border-0 ${item.read ? "bg-transparent" : "bg-cyan-300/[.035]"}`}><p className="text-[10px] font-semibold uppercase tracking-wider text-cyan-300">{eventLabel(item.type)}</p><p className="mt-2 text-xs text-slate-500">{item.brandName} · {relativeTime(item.occurredAt)}</p><p className="mt-1 line-clamp-2 text-sm text-slate-200">{item.title}</p></Link>)}{!notifications.length && <p className="p-8 text-center text-sm text-slate-500">No hay notificaciones nuevas en esta sesión.</p>}</div></aside>}
    </div></>;
}
function eventLabel(type: StudioLiveEvent["type"]) { return type === "client_change" ? "Cambio del cliente" : type === "internal_change" ? "Cambio solicitado" : type === "new_assignment" ? "Nueva pieza asignada" : "Cliente aprobó la pieza"; }
function relativeTime(value: string) { const minutes = Math.max(0, Math.floor((Date.now() - Date.parse(value)) / 60_000)); return minutes < 1 ? "Ahora" : minutes === 1 ? "Hace 1 min" : `Hace ${minutes} min`; }
