import { NextResponse } from "next/server";
import OpenAI from "openai";
import { createClient } from "@supabase/supabase-js";
import { requireAdminWorkspace } from "@/lib/workspace/admin-brands";
import { generateCalendarSlots, type CalendarSlot } from "@/lib/marketing/calendar-slots";
import { resolveMarketingChannels } from "@/lib/marketing/channels";
import { getPrimaryBrandProductionAssignee } from "@/lib/studio/assignments";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
const ITEM_FIELDS = "id,calendar_id,title,content_type,platform,publish_date,due_date,status,distribution_type,delivery_type,calendar_slot_key";
type Row = Record<string, unknown>;
function db() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE; if (!url || !key) throw new Error("SERVER_CONFIG_INVALID"); return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); }
function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function normalizeFunnelStage(value: unknown): "awareness" | "consideration" | "conversion" | "retention" | "loyalty" | null { const clean = text(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[\s_-]+/g, " ").trim(); const aliases: Record<string, "awareness" | "consideration" | "conversion" | "retention" | "loyalty"> = { awareness: "awareness", conciencia: "awareness", reconocimiento: "awareness", descubrimiento: "awareness", consideration: "consideration", "consideracion": "consideration", evaluacion: "consideration", "evaluation": "consideration", conversion: "conversion", conversiones: "conversion", retencion: "retention", retention: "retention", fidelizacion: "loyalty", lealtad: "loyalty", loyalty: "loyalty" }; return aliases[clean] || null; }
function slotPrompt(slots: CalendarSlot[]) { return slots.map(({ slotId, date, contentType, distributionType, platformCandidates, contractualSource }) => ({ slotId, date, contentType, distributionType, platformCandidates, contractualSource })); }
const outputSchema = { type: "object", additionalProperties: false, required: ["proposals"], properties: { proposals: { type: "array", items: { type: "object", additionalProperties: false, required: ["slotId", "title", "objective", "funnelStage", "brief", "copyBase", "cta", "visualDirection", "platform"], properties: { slotId: { type: "string" }, title: { type: "string" }, objective: { type: "string" }, funnelStage: { type: ["string", "null"] }, brief: { type: "string" }, copyBase: { type: "string" }, cta: { type: "string" }, visualDirection: { type: "string" }, platform: { type: "string" } } } } } };

export async function POST(request: Request, { params }: { params: Promise<{ brandSlug: string }> }) {
  try {
    const actor = await requireAdminWorkspace(); const { brandSlug } = await params; const body = await request.json().catch(() => ({})); const year = Number(body.year); const month = Number(body.month); const startDate = text(body.startDate); if (!/^\d{4}-\d{2}-\d{2}$/.test(startDate)) return NextResponse.json({ error: "START_DATE_REQUIRED" }, { status: 400 }); const parsedStart = new Date(`${startDate}T00:00:00Z`); if (Number.isNaN(parsedStart.getTime()) || parsedStart.getUTCFullYear() !== year || parsedStart.getUTCMonth() + 1 !== month) return NextResponse.json({ error: "START_DATE_OUTSIDE_PERIOD" }, { status: 400 });
    if (!Number.isInteger(year) || !Number.isInteger(month) || month < 1 || month > 12) return NextResponse.json({ error: "INVALID_PERIOD" }, { status: 400 });
    const client = db(); const brandResult = await client.from("brands").select("id,slug,name").eq("slug", brandSlug).maybeSingle(); if (brandResult.error) throw brandResult.error; if (!brandResult.data) return NextResponse.json({ error: "BRAND_NOT_FOUND" }, { status: 404 }); const canonicalBrand = brandResult.data;
    const strategyResult = await client.from("cometa_marketing_strategies").select("id,period_year,period_month,status,objective_primary,strategic_focus,channels").eq("brand_id", canonicalBrand.id).eq("period_year", year).eq("period_month", month).eq("status", "published").maybeSingle(); if (strategyResult.error) throw strategyResult.error; if (!strategyResult.data) return NextResponse.json({ error: "STRATEGY_NOT_PUBLISHED" }, { status: 409 }); const publishedStrategy = strategyResult.data;
    const assignmentResult = await client.from("cometa_brand_marketing_packages").select("package_snapshot,effective_from,effective_to").eq("brand_id", canonicalBrand.id).is("effective_to", null).maybeSingle(); if (assignmentResult.error) throw assignmentResult.error; if (!assignmentResult.data) return NextResponse.json({ error: "PACKAGE_NOT_ASSIGNED" }, { status: 409 }); const assignment = assignmentResult.data;
    const contextResult = await client.from("cometa_brand_context").select("context_claims").eq("brand_id", canonicalBrand.id).maybeSingle(); if (contextResult.error) throw contextResult.error; const claims: Row = contextResult.data?.context_claims && typeof contextResult.data.context_claims === "object" ? contextResult.data.context_claims as Row : {};
    const channels = resolveMarketingChannels({ contextClaim: claims.channels, publishedStrategyChannels: publishedStrategy.channels }); if (!channels.length) return NextResponse.json({ error: "CHANNEL_CONTEXT_INCOMPLETE", message: "No encontramos canales confirmados y compatibles para generar el calendario." }, { status: 409 });
    const slots = generateCalendarSlots({ year, month, startDate, packageSnapshot: assignment.package_snapshot as Row, platformCandidates: channels, effectiveFrom: assignment.effective_from, effectiveTo: assignment.effective_to }); if (!slots.length) return NextResponse.json({ error: "NO_ELIGIBLE_SLOTS" }, { status: 409 });
    const calendarResult = await client.from("mercury_calendars").select("id,status").eq("brand_slug", canonicalBrand.slug).eq("cycle_month", month).eq("cycle_year", year).maybeSingle(); if (calendarResult.error) throw calendarResult.error; let resolvedCalendar: { id: string; status: string | null };
    if (calendarResult.data) { resolvedCalendar = { id: String(calendarResult.data.id), status: typeof calendarResult.data.status === "string" ? calendarResult.data.status : null }; const updatedCalendar = await client.from("mercury_calendars").update({ cycle_start_date: startDate }).eq("id", resolvedCalendar.id).eq("brand_slug", canonicalBrand.slug); if (updatedCalendar.error) throw updatedCalendar.error; } else { const createdResult = await client.from("mercury_calendars").insert({ brand_name: canonicalBrand.name, brand_slug: canonicalBrand.slug, cycle_month: month, cycle_year: year, cycle_start_date: startDate, cycle_end_date: `${year}-${String(month).padStart(2, "0")}-${new Date(Date.UTC(year, month, 0)).getUTCDate()}`, status: "draft", monthly_objective: publishedStrategy.objective_primary, strategic_focus: publishedStrategy.strategic_focus, channels }).select("id,status").single(); if (createdResult.error) throw createdResult.error; if (!createdResult.data) throw new Error("CALENDAR_CREATE_FAILED"); resolvedCalendar = { id: String(createdResult.data.id), status: typeof createdResult.data.status === "string" ? createdResult.data.status : null }; }
    const existingResult = await client.from("mercury_content_items").select("calendar_slot_key").eq("calendar_id", resolvedCalendar.id).not("calendar_slot_key", "is", null); if (existingResult.error) throw existingResult.error; const existingKeys = new Set((existingResult.data || []).map((row) => String(row.calendar_slot_key))); const missing = slots.filter((slot) => !existingKeys.has(slot.slotKey)); if (!missing.length) return NextResponse.json({ ok: true, calendarId: resolvedCalendar.id, slots: slots.length, itemsCreated: 0, reused: true });
    const openaiKey = process.env.OPENAI_API_KEY; if (!openaiKey) throw new Error("OPENAI_CONFIG_INVALID"); const completion = await new OpenAI({ apiKey: openaiKey }).chat.completions.create({ model: "gpt-4.1-mini", temperature: 0.25, response_format: { type: "json_schema", json_schema: { name: "cometa_auto_calendar_v1", strict: true, schema: outputSchema } }, messages: [{ role: "system", content: "Completa exactamente los slots recibidos. No agregues ni elimines propuestas y no cambies slotId, fecha, tipo, distribución ni plataforma permitida. Usa hechos confirmados; no inventes promociones, métricas ni activos." }, { role: "user", content: JSON.stringify({ brand: canonicalBrand, strategy: publishedStrategy, confirmedContext: claims, packageSnapshot: assignment.package_snapshot, slots: slotPrompt(missing) }) }] });
    const parsed = JSON.parse(completion.choices[0]?.message?.content || "{}"); const proposals = Array.isArray(parsed.proposals) ? parsed.proposals as Row[] : []; const bySlot = new Map(proposals.map((proposal) => [String(proposal.slotId), proposal])); if (bySlot.size !== missing.length || missing.some((slot) => !bySlot.has(slot.slotId))) throw new Error("AUTO_CALENDAR_SLOT_MAPPING_INVALID");
    const primary = await getPrimaryBrandProductionAssignee(canonicalBrand.slug);
    const items = missing.map((slot) => { const proposal = bySlot.get(slot.slotId); if (!proposal) throw new Error("AUTO_CALENDAR_SLOT_MAPPING_INVALID"); const platform = text(proposal.platform); if (!slot.platformCandidates.includes(platform)) throw new Error("AUTO_CALENDAR_PLATFORM_INVALID"); return { calendar_id: resolvedCalendar.id, brand_name: canonicalBrand.name, brand_slug: canonicalBrand.slug, title: text(proposal.title) || `Contenido ${slot.contentType}`, content_type: slot.contentType, platform, objective: text(proposal.objective) || null, funnel_stage: normalizeFunnelStage(proposal.funnelStage), brief: text(proposal.brief) || null, copy_base: text(proposal.copyBase) || null, cta: text(proposal.cta) || null, visual_direction: text(proposal.visualDirection) || null, publish_date: slot.date, due_date: slot.date, assigned_to: primary.assignee?.userId || null, assigned_role: primary.assignee?.role || null, status: "generated", priority: "normal", created_by_agent: true, locked: false, private_notes: null, client_notes: null, raw_ai_data: {}, distribution_type: slot.distributionType, delivery_type: "contractual", calendar_slot_key: slot.slotKey }; });
    const inserted = await client.from("mercury_content_items").insert(items).select(ITEM_FIELDS); if (inserted.error) throw inserted.error; return NextResponse.json({ ok: true, calendarId: resolvedCalendar.id, slots: slots.length, itemsCreated: inserted.data?.length || 0, actorUserId: actor.userId });
  } catch (error) { console.error("[AUTO_CALENDAR_FAILURE]", error); return NextResponse.json({ error: error instanceof Error ? error.message : "AUTO_CALENDAR_FAILED" }, { status: 400 }); }
}
