import Link from "next/link";
import { getPublicListing } from "@/lib/comu/public-catalog";
import { isComuFeatureEnabled } from "@/lib/comu/features";
import { notFound } from "next/navigation";
import AddToCart from "./add-to-cart";

export default async function ComuProduct({ params }: { params: Promise<{ slug: string }> }) {
  if (!isComuFeatureEnabled("enabled") || !isComuFeatureEnabled("catalog")) notFound();
  const listing = await getPublicListing((await params).slug);
  if (!listing) return <main className="mx-auto max-w-4xl px-5 py-28 text-center"><p className="text-[11px] font-black uppercase tracking-[.24em] text-[#8b7564]">COMU</p><h1 className="mt-4 text-4xl font-black tracking-[-.06em]">Esta pieza ya no está disponible.</h1><Link href="/comu/search" className="mt-6 inline-block font-bold text-[#6b513e] underline underline-offset-4">Volver a explorar</Link></main>;
  const image = listing.media?.find((media) => media.is_primary)?.public_url || listing.product?.image_url;
  const price = listing.retail_price_override ?? listing.variants[0]?.productVariant?.price;
  return <main className="mx-auto grid max-w-7xl gap-10 px-5 py-10 md:grid-cols-[1.05fr_.95fr] md:gap-16 md:py-16"><div className="space-y-3"><div className="relative aspect-[.9/1] overflow-hidden rounded-[2.2rem] bg-[#ebe7e1]">{image ? <img src={image} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-end bg-[linear-gradient(145deg,#ded6cb,#f3eee7)] p-8"><p className="max-w-xs text-4xl font-black leading-none text-[#625449]">Una pieza para descubrir.</p></div>}<span className="absolute left-5 top-5 rounded-full bg-[#fffdf9]/90 px-4 py-2 text-[10px] font-black uppercase tracking-[.16em] text-[#5f4938]">Selección COMU</span></div><p className="px-1 text-xs text-[#9a8e83]">Imágenes del producto y del seller. La disponibilidad se confirma al reservar.</p></div><div className="py-3 md:py-8"><Link href={`/comu/sellers/${listing.seller?.slug}`} className="text-sm font-black text-[#795d48]">{listing.seller?.public_name} ↗</Link><h1 className="mt-5 text-5xl font-black leading-[.94] tracking-[-.08em] text-[#19201c] md:text-6xl">{listing.title_override || listing.product?.name}</h1><div className="mt-6 flex items-center gap-4">{price !== null && price !== undefined ? <p className="text-2xl font-black text-[#3d332c]">${Number(price).toFixed(2)}</p> : null}{listing.wholesale_enabled ? <span className="rounded-full bg-[#e2eadf] px-3 py-1.5 text-xs font-black text-[#3f5b44]">Mayoreo disponible</span> : null}</div><p className="mt-6 max-w-xl text-lg leading-8 text-[#776b61]">{listing.description_override || listing.product?.description || "Una pieza seleccionada por COMU."}</p><div className="mt-8 rounded-[1.5rem] border border-[#d9cfc4] bg-[#fffdf9] p-5"><p className="text-[11px] font-black uppercase tracking-[.2em] text-[#8b7564]">Elige tu variante</p><div className="mt-3 space-y-1">{listing.variants.map((variant) => <div key={variant.variant_id} className="flex items-center justify-between border-b border-[#eee7df] py-3 last:border-0"><div><p className="font-bold text-[#302a25]">{variant.productVariant?.name || "Variante"}</p><p className="text-xs text-[#9a8e83]">{variant.productVariant?.sku || ""}</p></div><span className={`text-sm font-bold ${variant.availability === "out_of_stock" ? "text-[#ad554d]" : variant.availability === "low_stock" ? "text-[#9a6d25]" : "text-[#4d7656]"}`}>{variant.availability === "out_of_stock" ? "Agotado" : variant.availability === "low_stock" ? "Pocas piezas" : "Disponible"}</span></div>)}</div></div><AddToCart listingId={listing.id} variants={listing.variants.map((variant) => ({ id: variant.id, name: variant.productVariant?.name || "Variante", available: Boolean(variant.enabled && variant.productVariant && ["available", "low_stock"].includes(variant.availability || "")) }))} /><p className="mt-5 text-xs leading-5 text-[#9a8e83]">La disponibilidad es informativa hasta iniciar checkout. COMU reserva tus piezas durante 15 minutos al confirmar.</p></div></main>;
}
