"use client";
import Image from "next/image";
import { useRef, useState } from "react";
export function ProductGallery({ images, title }: { images: string[]; title: string }) {
  const [active, setActive] = useState(0); const dialog = useRef<HTMLDialogElement>(null);
  const image = images[active];
  function move(direction: number) { setActive(index => (index + direction + images.length) % images.length); }
  return <div><div className="relative aspect-[1/1.05] max-h-[600px] overflow-hidden rounded-3xl bg-[#ebe7e1]">{image ? <button aria-label="Ampliar imagen del producto" onClick={() => dialog.current?.showModal()} className="absolute inset-0"><Image unoptimized src={image} alt={`${title}, vista ${active + 1}`} fill priority sizes="(max-width: 768px) 90vw, 45vw" className="object-contain" /></button> : <div className="grid h-full place-items-center text-[#72675e]">Imagen no disponible</div>}{images.length > 1 && <><button aria-label="Imagen anterior" onClick={() => move(-1)} className="absolute left-3 top-1/2 grid h-10 w-10 place-items-center rounded-full bg-[#fffdf9]">←</button><button aria-label="Imagen siguiente" onClick={() => move(1)} className="absolute right-3 top-1/2 grid h-10 w-10 place-items-center rounded-full bg-[#fffdf9]">→</button></>}</div>{images.length > 1 && <div aria-label="Vistas del producto" className="mt-4 flex gap-3 overflow-x-auto pb-2">{images.map((url, index) => <button key={`${url}-${index}`} aria-label={`Ver imagen ${index + 1}`} aria-pressed={index === active} onClick={() => setActive(index)} className={`relative h-20 w-16 shrink-0 overflow-hidden rounded-xl border-2 ${index === active ? "border-[#795d48]" : "border-transparent"}`}><Image unoptimized src={url} alt="" fill sizes="64px" className="object-cover" /></button>)}</div>}<dialog ref={dialog} className="comu-modal !w-[min(94vw,1000px)]" aria-label="Imagen ampliada"><button autoFocus onClick={() => dialog.current?.close()} className="float-right p-3" aria-label="Cerrar imagen ampliada">Cerrar ×</button>{image && <div className="relative mt-12 h-[65dvh]"><Image unoptimized src={image} alt={title} fill sizes="90vw" className="object-contain" /></div>}</dialog></div>;
}
export function SizeGuide({ guide }: { guide: string | null }) { const dialog = useRef<HTMLDialogElement>(null); return <><button onClick={() => dialog.current?.showModal()} className="mt-6 text-sm font-semibold underline underline-offset-4">Guía de tallas</button><dialog ref={dialog} aria-labelledby="size-guide-title" className="comu-modal"><div className="flex items-center justify-between"><h2 id="size-guide-title" className="text-2xl font-semibold">Guía de tallas</h2><button onClick={() => dialog.current?.close()} className="p-3" aria-label="Cerrar guía de tallas">×</button></div><p className="mt-6 whitespace-pre-wrap text-sm leading-7 text-[#72675e]">{guide || "Guía no disponible. Esta tienda todavía no ha publicado medidas para esta pieza. Revisa la descripción antes de elegir tu talla."}</p></dialog></>; }
