export type FoodUnit = { code: string; name: string; symbol: string; unit_type: string };
export type FoodPresentation = { id: string; name: string; conversion_factor: number; base_unit_code: string; configured_cost: number | null; supplier_name: string | null; active: boolean };
export type FoodIngredient = { id: string; product_id: string; name: string; unit_code: string; unit_cost: number; active: boolean; category: string; waste_percent: number; supplier_name: string | null; stock: number; reserved_stock: number; minimum_stock: number; usable_estimated_stock: number; presentations: FoodPresentation[] };
export type FoodRecipeComponent = { ingredient_variant_id: string; name: string; base_quantity: number; base_unit_code: string; unit_cost: number; subtotal: number; physical_stock: number; available_stock: number; usable_estimated_stock: number; possible: number; usable_estimated_possible: number; waste_percent: number };
export type FoodRecipeMetrics = { recipe_version_id: string; version: number; components: FoodRecipeComponent[]; unit_cost: number; price: number; gross_profit: number; gross_margin: number | null; availability: number | null; usable_estimated_availability: number | null; limiting_ingredient: string | null; limiting_remaining: number | null };
export type FoodRecipeProduct = { id: string; product_id: string; name: string; variant_name: string; price: number; description: string | null; tax_rate: number; active: boolean; inventory_mode: string; category_id: string | null; category_name: string | null; image_url?: string | null; recipe: FoodRecipeMetrics | null; recipe_components: { ingredient_variant_id: string; input_quantity: number; input_unit_code: string; base_quantity: number; base_unit_code: string }[] };
export type FoodRecipeEffect = { product_id: string; option_id: string; effect: 'ADD' | 'REMOVE' | 'REPLACE'; source_variant_id: string | null; ingredient_variant_id: string | null; input_quantity: number | null; input_unit_code: string | null };
export type FoodRecipeMovement = { id: string; variant_id: string; movement_type: string; quantity_delta: number; quantity_before: number; quantity_after: number; reference_id: string | null; created_at: string; notes: string | null };
export type FoodRecipesCatalog = { ingredients: FoodIngredient[]; products: FoodRecipeProduct[]; effects: FoodRecipeEffect[]; units: FoodUnit[]; movements: FoodRecipeMovement[] };

export const FOOD_RECIPE_ACTIONS = ['ingredient_save', 'ingredient_status', 'adjust', 'cost_set', 'receive', 'product_save', 'image_save', 'recipe_publish', 'effect_save'] as const;
export type FoodRecipeAction = typeof FOOD_RECIPE_ACTIONS[number];
