"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { APPROVAL_BUCKET_LABELS, contentTypeLabel, dateLabel, distributionLabel, type ApprovalBucket, type ApprovalItem } from "@/lib/workspace/content-presentation";

type Data = { items: ApprovalItem[]; brands: Array<{ slug: string; name: string }>; assignees: Array<{ id: string; name: string }>; counts: Record<ApprovalBucket, number> };
const filters: Array<{ value: "all" | ApprovalBucket; label: string }> = [{ value: "all", label: "Todas" }, { value: "internal_review", label: "Revisión interna" }, { value: "ready_for_client", label: "Listas para cliente" }, { value: "internal_changes", label: "Cambios internos" }, { value: "client_changes", label: "Cambios del cliente" }, { value: "client_reviewing", label: "Cliente revisando" }];

export function ApprovalsClient({ data }: { data: Data }) {
  const router = useRouter();
  const [bucket, setBucket] = useState<"all" | ApprovalBucket>("all"); const [brand, setBrand] = useState(""); const [distribution, setDistribution] = useState(""); const [assignee, setAssignee] = useState("");
  const [selected, setSelected] = useState<ApprovalItem | null>(null); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const items = useMemo(() => data.items.filter((item) => (bucket === "all" || item.bucket === bucket) && (!brand || item.brandSlug === brand) && (!distribution || item.distributionType === distribution) && (!assignee || item.assignedTo === assignee)), [data.items, bucket, brand, distribution, assignee]);
  async function act(action: "request_internal_changes" | "approve_internal" | "send_to_client") { if (!selected || busy) return; setBusy(true); setError(null); try { const response = await fetch("/api/admin/approvals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, brandSlug: selected.brandSlug, contentItemId: selected.id, comment }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "No se pudo completar la acción."); setSelected(null); setComment(""); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo completar la acción."); } finally { setBusy(false); } }
  const attention = data.counts.internal_review + data.counts.ready_for_client + data.counts.internal_changes + data.counts.client_changes;
  return <main className="space-y-7"><header><p className="text-xs font-semibold uppercase tracking-[.24em] text-cyan-300">Review command center</p><h1 className="mt-2 text-3xl font-semibold">APROBACIONES</h1><p className="mt-2 text-sm text-slate-400">{attention} piezas requieren tu atención.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Revisión interna", data.counts.internal_review], ["Listas para cliente", data.counts.ready_for_client], ["Cambios del cliente", data.counts.client_changes], ["Cliente revisando", data.counts.client_reviewing]].map(([label, count]) => <div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-white">{count}</p></div>)}</section>
    <section className="flex flex-wrap gap-2">{filters.map((item) => <button key={item.value} onClick={() => setBucket(item.value)} className={`rounded-full px-3 py-2 text-xs ${bucket === item.value ? "bg-cyan-300 text-slate-950" : "border border-white/10 text-slate-300"}`}>{item.label}</button>)}<Select value={brand} onChange={setBrand} label="Todas las marcas" options={data.brands.map((x) => [x.slug, x.name])} /><Select value={distribution} onChange={setDistribution} label="Orgánico / Pauta" options={[["organic", "Orgánico"], ["paid", "Pauta"]]} /><Select value={assignee} onChange={setAssignee} label="Responsable" options={data.assignees.map((x) => [x.id, x.name])} /></section>
    {items.length === 0 ? <div className="rounded-3xl border border-dashed border-white/10 p-12 text-center text-sm text-slate-400">No hay decisiones pendientes con estos filtros.</div> : <section className="grid gap-4 xl:grid-cols-2">{items.map((item) => <button key={item.id} onClick={() => { setSelected(item); setComment(""); setError(null); }} className="grid grid-cols-[104px_1fr] gap-4 rounded-2xl border border-white/10 bg-[#0b192a] p-3 text-left transition hover:border-cyan-300/30"><Preview item={item} /><div className="min-w-0"><div className="flex flex-wrap gap-2 text-[10px] uppercase tracking-wider text-cyan-200"><span>{item.brandName}</span><span>{contentTypeLabel(item.contentType)}</span><span>{distributionLabel(item.distributionType)}</span></div><h2 className="mt-2 truncate font-medium text-white">{item.title}</h2><p className="mt-2 text-xs text-slate-400">{item.assigneeName || "Sin responsable"} · {item.distributionType === "paid" ? "Activación prevista" : "Publicación"}: {dateLabel(item.publishDate || item.dueDate)}</p><p className="mt-3 text-xs font-semibold text-amber-200">{APPROVAL_BUCKET_LABELS[item.bucket]}</p>{item.latestComment && <p className="mt-2 line-clamp-2 text-xs text-slate-400">“{item.latestComment.text}”</p>}</div></button>)}</section>}
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-black/70" onClick={() => setSelected(null)}><aside className="h-full w-full max-w-2xl overflow-y-auto border-l border-white/10 bg-[#081525] p-6" onClick={(event) => event.stopPropagation()}><button onClick={() => setSelected(null)} className="float-right text-slate-400">Cerrar</button><p className="text-xs uppercase tracking-wider text-cyan-300">{selected.brandName} · {APPROVAL_BUCKET_LABELS[selected.bucket]}</p><h2 className="mt-3 text-2xl font-semibold">{selected.title}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{selected.assets.map((asset) => asset.url ? <a key={asset.id} href={asset.url} target="_blank" rel="noreferrer" className="overflow-hidden rounded-xl border border-white/10"><img src={asset.url} alt={asset.label || "Asset de contenido"} className="h-44 w-full object-cover" /></a> : null)}</div><Detail label="Objetivo" value={selected.objective} /><Detail label="Brief" value={selected.brief} /><Detail label="CTA" value={selected.cta} /><Detail label="Dirección visual" value={selected.visualDirection} /><Detail label="Referencias" value={selected.referenceNotes} />{selected.reviewHistory.length > 0 && <div className="mt-6"><p className="text-xs uppercase text-slate-500">Historial cliente</p>{selected.reviewHistory.map((review) => <div key={review.id} className="mt-2 rounded-xl bg-white/[.04] p-3 text-sm text-slate-300">{review.status}{review.decisionComment ? ` · ${review.decisionComment}` : ""}</div>)}</div>}
      {error && <p className="mt-5 rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}{["design_uploaded", "internal_review", "approved_internal"].includes(selected.status) && <textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Comentario interno obligatorio para pedir cambios" className="mt-6 min-h-24 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm outline-none focus:border-cyan-300/50" />}
      <div className="mt-4 flex flex-wrap gap-2">{["design_uploaded", "internal_review", "approved_internal"].includes(selected.status) && <button disabled={busy || comment.trim().length < 3} onClick={() => void act("request_internal_changes")} className="rounded-xl border border-amber-300/30 px-4 py-2 text-sm text-amber-200 disabled:opacity-40">Pedir cambios</button>}{["design_uploaded", "internal_review"].includes(selected.status) && <button disabled={busy} onClick={() => void act("approve_internal")} className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-40">Aprobar internamente</button>}{selected.status === "approved_internal" && <button disabled={busy} onClick={() => void act("send_to_client")} className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-40">Enviar al cliente</button>}</div></aside></div>}
  </main>;
}
function Select({ value, onChange, label, options }: { value: string; onChange: (value: string) => void; label: string; options: string[][] }) { return <select value={value} onChange={(event) => onChange(event.target.value)} className="rounded-full border border-white/10 bg-[#0b192a] px-3 py-2 text-xs text-slate-300"><option value="">{label}</option>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select>; }
function Preview({ item }: { item: ApprovalItem }) { return item.thumbnailUrl ? <img src={item.thumbnailUrl} alt="" className="h-28 w-[104px] rounded-xl object-cover" /> : <div className="grid h-28 w-[104px] place-items-center rounded-xl bg-gradient-to-br from-cyan-300/15 to-blue-500/10 text-xs font-semibold text-cyan-200">{contentTypeLabel(item.contentType)}</div>; }
function Detail({ label, value }: { label: string; value: string | null }) { return value ? <div className="mt-5"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{value}</p></div> : null; }
