import "server-only";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { requireAdminWorkspace } from "@/lib/workspace/admin-brands";

export const PRODUCTION_ROLES = ["designer", "reels", "cm", "copy", "producer"] as const;
export type ProductionRole = (typeof PRODUCTION_ROLES)[number];
export type RecordingLocationType = "client_location" | "cometa_location" | "external_location" | "not_applicable";
export type ProductionProfile = { id: string; brandId: string; brandSlug: string; agencyModelAllowed: boolean; clientModelAvailable: boolean; handsAllowed: boolean; productOnlyAllowed: boolean; noHumanTalent: boolean; recordingLocationType: RecordingLocationType | null; recordingLocationNotes: string | null; productPickupRequired: boolean; usualRecordingNotes: string | null; visualRestrictions: string | null; productionNotes: string | null };
export type ProductionProfileInput = Omit<ProductionProfile, "id" | "brandId" | "brandSlug">;

function serviceClient(): SupabaseClient { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE; if (!url || !key) throw new Error("STUDIO_SERVER_CONFIG_INVALID"); return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); }
async function canonicalBrand(client: SupabaseClient, slug: string) { const { data, error } = await client.from("brands").select("id,slug").eq("slug", slug).maybeSingle(); if (error) throw new Error("BRAND_LOOKUP_FAILED"); if (!data) throw new Error("BRAND_NOT_FOUND"); return { id: String(data.id), slug: String(data.slug) }; }
function map(row: Record<string, unknown>): ProductionProfile { return { id: String(row.id), brandId: String(row.brand_id), brandSlug: String(row.brand_slug), agencyModelAllowed: row.agency_model_allowed === true, clientModelAvailable: row.client_model_available === true, handsAllowed: row.hands_allowed !== false, productOnlyAllowed: row.product_only_allowed !== false, noHumanTalent: row.no_human_talent === true, recordingLocationType: (row.recording_location_type as RecordingLocationType | null) || null, recordingLocationNotes: (row.recording_location_notes as string | null) || null, productPickupRequired: row.product_pickup_required === true, usualRecordingNotes: (row.usual_recording_notes as string | null) || null, visualRestrictions: (row.visual_restrictions as string | null) || null, productionNotes: (row.production_notes as string | null) || null }; }
export async function getBrandProductionProfile(brandSlug: string): Promise<ProductionProfile | null> { const client = serviceClient(); const brand = await canonicalBrand(client, brandSlug); const { data, error } = await client.from("cometa_brand_production_profiles").select("*").eq("brand_id", brand.id).maybeSingle(); if (error) throw new Error("PRODUCTION_PROFILE_LOOKUP_FAILED"); return data ? map(data as Record<string, unknown>) : null; }
export async function saveBrandProductionProfile(brandSlug: string, input: ProductionProfileInput): Promise<ProductionProfile> { const actor = await requireAdminWorkspace(); const client = serviceClient(); const brand = await canonicalBrand(client, brandSlug); if (input.noHumanTalent && (input.agencyModelAllowed || input.clientModelAvailable)) throw new Error("PRODUCTION_TALENT_CONFLICT"); const payload = { brand_id: brand.id, brand_slug: brand.slug, agency_model_allowed: input.agencyModelAllowed, client_model_available: input.clientModelAvailable, hands_allowed: input.handsAllowed, product_only_allowed: input.productOnlyAllowed, no_human_talent: input.noHumanTalent, recording_location_type: input.recordingLocationType, recording_location_notes: input.recordingLocationNotes || null, product_pickup_required: input.productPickupRequired, usual_recording_notes: input.usualRecordingNotes || null, visual_restrictions: input.visualRestrictions || null, production_notes: input.productionNotes || null, updated_by: actor.userId, created_by: actor.userId }; const { data, error } = await client.from("cometa_brand_production_profiles").upsert(payload, { onConflict: "brand_id" }).select("*").single(); if (error || !data) throw new Error("PRODUCTION_PROFILE_SAVE_FAILED"); return map(data as Record<string, unknown>); }
export async function getProductionCapabilities(brandSlug: string) { const profile = await getBrandProductionProfile(brandSlug); return { canUseAgencyModel: profile?.agencyModelAllowed === true && profile.noHumanTalent !== true, canUseClientModel: profile?.clientModelAvailable === true && profile.noHumanTalent !== true, canUseHands: profile?.handsAllowed === true, canUseProductOnly: profile?.productOnlyAllowed === true }; }
export async function assignUnassignedPieces(brandSlug: string) { const actor=await requireAdminWorkspace(); const client=serviceClient(); const brand=await canonicalBrand(client,brandSlug); const primary=await client.from("mercury_team_assignments").select("user_id,role").eq("brand_slug",brand.slug).eq("active",true).eq("is_primary",true).in("role",["designer","reels","cm","copy","producer"]).maybeSingle(); if(primary.error)throw Error("PRIMARY_LOOKUP_FAILED"); if(!primary.data)throw Error("PRIMARY_ASSIGNEE_REQUIRED"); const eligible=["generated","assigned","in_design","design_uploaded","internal_review","changes_requested","approved_internal"]; const result=await client.from("mercury_content_items").update({assigned_to:String(primary.data.user_id),assigned_role:String(primary.data.role)}).eq("brand_slug",brand.slug).is("assigned_to",null).in("status",eligible).select("id"); if(result.error)throw Error("UNASSIGNED_ASSIGNMENT_FAILED"); return {assignedCount:(result.data||[]).length,skippedCount:0,actorUserId:actor.userId}; }
