"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

export type ProductManagerProduct = { id: string; name: string; description?: string | null; image_url?: string | null; category_id?: string | null; sku?: string | null; price?: number | null; available_quantity?: number };
export type ProductManagerListing = { id: string; product_id: string; status: string; public_slug: string; wholesale_enabled?: boolean };

type Props = { brandSlug: string; products: ProductManagerProduct[]; listings: ProductManagerListing[]; publish: (id: string) => Promise<void>; changeStatus: (id: string, status: string) => Promise<void>; uploadMedia: (id: string, file: File) => Promise<void>; refresh: () => Promise<void>; sellerId: string };

export default function ProductsManager({ brandSlug, products, listings, publish, changeStatus, uploadMedia, refresh }: Props) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("ALL");
  const [category, setCategory] = useState("ALL");
  const listingByProduct = useMemo(() => new Map(listings.map((listing) => [listing.product_id, listing])), [listings]);
  const categories = useMemo(() => [...new Set(products.map((product) => product.category_id).filter(Boolean))] as string[], [products]);
  const filtered = useMemo(() => products.filter((product) => { const listing = listingByProduct.get(product.id); const text = `${product.name} ${product.sku || ""} ${product.category_id || ""}`.toLowerCase(); const matchesQuery = !query.trim() || text.includes(query.trim().toLowerCase()); const matchesCategory = category === "ALL" || product.category_id === category; const matchesFilter = filter === "ALL" || (filter === "UNPUBLISHED" && !listing) || (filter === "PUBLISHED" && listing?.status === "PUBLISHED") || (filter === "STOCK" && Number(product.available_quantity || 0) > 0) || (filter === "OUT" && Number(product.available_quantity || 0) <= 0); return matchesQuery && matchesCategory && matchesFilter; }), [category, filter, listingByProduct, products, query]);
  const published = listings.filter((listing) => listing.status === "PUBLISHED");
  const hidden = listings.filter((listing) => listing.status !== "PUBLISHED");
  const selected = published[0] ? products.find((product) => product.id === published[0].product_id) : undefined;
  const counts = { all: products.length, unpublished: products.filter((product) => !listingByProduct.has(product.id)).length, published: published.length, stock: products.filter((product) => Number(product.available_quantity || 0) > 0).length, out: products.filter((product) => Number(product.available_quantity || 0) <= 0).length };

  return <section className="mt-8 space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon="▦" label="En POS" value={counts.all} copy="Productos disponibles en tu POS." /><Kpi icon="◈" label="Publicados" value={counts.published} copy="Visibles en tu tienda COMU." accent /><Kpi icon="○" label="Ocultos" value={hidden.length} copy="No visibles en tu tienda." /><Kpi icon="↗" label="Sincronizados" value={counts.all} copy="Inventario conectado al POS." /></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)]">
      <section className="min-w-0 rounded-[1.5rem] border border-white/10 bg-white/[.035] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,.03)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Catálogo conectado</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em] text-white">Catálogo POS disponible</h2><p className="mt-1 text-sm leading-6 text-slate-400">Selecciona los productos de tu POS para publicarlos en COMU.</p></div><button type="button" onClick={() => void refresh()} className="rounded-xl border border-white/15 px-3.5 py-2.5 text-xs font-bold text-slate-200 transition hover:border-emerald-300/40 hover:text-emerald-100">Sincronizar ahora</button></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar productos por nombre, SKU o categoría..." className="min-w-0 flex-1 rounded-xl border border-white/10 bg-[#0b1712] px-4 py-3 text-sm text-white outline-none placeholder:text-slate-500 focus:border-emerald-300/40" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-xl border border-white/10 bg-[#0b1712] px-4 py-3 text-sm text-slate-300 outline-none"><option value="ALL">Todas las categorías</option>{categories.map((item) => <option value={item} key={item}>{item}</option>)}</select></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{[["ALL", `Todos ${counts.all}`], ["UNPUBLISHED", `Sin publicar ${counts.unpublished}`], ["PUBLISHED", `Ya publicados ${counts.published}`], ["STOCK", `Con stock ${counts.stock}`], ["OUT", `Sin stock ${counts.out}`]].map(([value, label]) => <button key={value} type="button" onClick={() => setFilter(value)} className={`shrink-0 rounded-full border px-3 py-2 text-xs font-bold transition ${filter === value ? "border-emerald-300/40 bg-emerald-300/10 text-emerald-100" : "border-white/10 text-slate-400 hover:border-white/20 hover:text-white"}`}>{label}</button>)}</div><div className="mt-5 space-y-2">{filtered.map((product) => <ProductRow key={product.id} product={product} listing={listingByProduct.get(product.id)} onPublish={publish} onHide={changeStatus} />)}{!filtered.length ? <div className="rounded-2xl border border-dashed border-white/10 px-6 py-12 text-center"><p className="text-base font-bold text-white">No encontramos productos</p><p className="mt-2 text-sm text-slate-500">Prueba con otra búsqueda o revisa los filtros del catálogo.</p></div> : null}</div></section>
      <aside className="space-y-5"><section className="rounded-[1.5rem] border border-white/10 bg-white/[.035] p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Catálogo público</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em] text-white">Publicados en COMU</h2><p className="mt-1 text-sm leading-6 text-slate-400">Productos visibles en tu tienda en línea.</p></div><span className="rounded-full border border-emerald-300/20 bg-emerald-300/10 px-2.5 py-1 text-xs font-bold text-emerald-100">{published.length} productos</span></div><div className="mt-5 space-y-3">{published.map((listing) => { const product = products.find((item) => item.id === listing.product_id); return product ? <PublishedRow key={listing.id} brandSlug={brandSlug} product={product} listing={listing} onHide={changeStatus} onUpload={uploadMedia} /> : null; })}{!published.length ? <EmptyPublished href={`/brand/${encodeURIComponent(brandSlug)}/comu/store`} /> : null}</div></section><QuickPreview brandSlug={brandSlug} product={selected} listing={published[0]} /></aside>
    </div>
  </section>;
}

function Kpi({ icon, label, value, copy, accent = false }: { icon: string; label: string; value: number; copy: string; accent?: boolean }) { return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-4 shadow-[inset_0_1px_0_rgba(255,255,255,.03)]"><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-300/10 text-emerald-200">{icon}</span><span className="text-xs text-slate-600">↗</span></div><p className="mt-4 text-xs font-semibold text-slate-400">{label}</p><p className={`mt-1 text-2xl font-black ${accent ? "text-emerald-200" : "text-white"}`}>{value}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p></div>; }
function ProductRow({ product, listing, onPublish, onHide }: { product: ProductManagerProduct; listing?: ProductManagerListing; onPublish: (id: string) => Promise<void>; onHide: (id: string, status: string) => Promise<void> }) { const stock = Number(product.available_quantity || 0); return <article className="flex flex-col gap-4 rounded-2xl border border-white/[.07] bg-[#0b1712] p-4 transition hover:border-emerald-300/20 sm:flex-row sm:items-center"><Thumb product={product} /><div className="min-w-0 flex-1"><h3 className="truncate font-bold text-white">{product.name}</h3><p className="mt-1 truncate text-xs text-slate-500">{product.category_id || "Producto POS"} · SKU {product.sku || "Sin SKU"}</p><div className="mt-2 flex flex-wrap gap-2 text-xs"><span className={stock > 0 ? "text-emerald-200" : "text-slate-500"}>{stock > 0 ? `${stock} disponibles` : "Sin stock"}</span>{product.price !== null && product.price !== undefined ? <span className="text-slate-300">${Number(product.price).toFixed(2)} MXN</span> : null}</div></div><div className="flex items-center gap-3"><span className={`rounded-full border px-2.5 py-1 text-[11px] font-bold ${listing?.status === "PUBLISHED" ? "border-emerald-300/20 bg-emerald-300/10 text-emerald-100" : "border-white/10 text-slate-400"}`}>{listing ? (listing.status === "PUBLISHED" ? "Publicado" : "Oculto") : "Sin publicar"}</span>{listing?.status === "PUBLISHED" ? <button type="button" onClick={() => void onHide(listing.id, "HIDDEN")} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-bold text-slate-300 transition hover:border-rose-300/30 hover:text-rose-100">Ocultar</button> : <button type="button" onClick={() => void onPublish(product.id)} className="rounded-xl bg-emerald-300 px-3 py-2 text-xs font-black text-[#06100b] transition hover:bg-emerald-200">Publicar</button>}</div></article>; }
function PublishedRow({ brandSlug, product, listing, onHide, onUpload }: { brandSlug: string; product: ProductManagerProduct; listing: ProductManagerListing; onHide: (id: string, status: string) => Promise<void>; onUpload: (id: string, file: File) => Promise<void> }) { return <article className="rounded-2xl border border-white/[.07] bg-[#0b1712] p-4"><div className="flex items-center gap-3"><Thumb product={product} /><div className="min-w-0 flex-1"><h3 className="truncate font-bold text-white">{product.name}</h3><p className="mt-1 text-xs text-slate-500">SKU {product.sku || "Sin SKU"}</p></div><span className="rounded-full border border-emerald-300/20 bg-emerald-300/10 px-2.5 py-1 text-[11px] font-bold text-emerald-100">Publicado</span></div><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-white/[.06] px-2.5 py-1 text-[11px] text-slate-300">Menudeo</span>{listing.wholesale_enabled ? <span className="rounded-full bg-white/[.06] px-2.5 py-1 text-[11px] text-slate-300">Mayoreo</span> : null}</div><details className="mt-3 rounded-xl border border-white/[.07] px-3 py-2"><summary className="cursor-pointer text-xs font-bold text-slate-300">Perfil logístico</summary><p className="mt-2 text-xs leading-5 text-slate-500">Peso y empaque estimados desde tu configuración logística.</p></details><div className="mt-4 flex flex-wrap gap-2"><Link href={`/comu/products/${encodeURIComponent(listing.public_slug)}`} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-bold text-slate-300 hover:border-emerald-300/30 hover:text-emerald-100">Vista previa</Link><label className="cursor-pointer rounded-xl border border-white/15 px-3 py-2 text-xs font-bold text-slate-300 hover:border-emerald-300/30">Editar<input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void onUpload(listing.id, file); event.currentTarget.value = ""; }} /></label><Link href={`/brand/${encodeURIComponent(brandSlug)}/pos/products`} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-bold text-slate-300 hover:border-emerald-300/30 hover:text-emerald-100">Editar producto</Link><button type="button" onClick={() => void onHide(listing.id, "HIDDEN")} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-bold text-slate-300 hover:border-rose-300/30 hover:text-rose-100">Ocultar</button></div></article>; }
function QuickPreview({ product, listing, brandSlug }: { product?: ProductManagerProduct; listing?: ProductManagerListing; brandSlug: string }) { return <section className="rounded-[1.5rem] border border-white/10 bg-white/[.035] p-5 sm:p-6"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Vista rápida en COMU</p><h2 className="mt-2 text-xl font-black text-white">Así se verá este producto en tu tienda.</h2>{product && listing ? <div className="mt-5 overflow-hidden rounded-2xl border border-white/[.08] bg-[#0b1712]"><div className="aspect-[4/3] bg-[#14231b]">{product.image_url ? <img src={product.image_url} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-4xl font-black text-emerald-200">{product.name.slice(0, 1).toUpperCase()}</div>}</div><div className="p-4"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-emerald-200">Tu tienda COMU</p><h3 className="mt-2 font-black text-white">{product.name}</h3><p className="mt-2 text-sm font-black text-emerald-100">{product.price !== null && product.price !== undefined ? `$${Number(product.price).toFixed(2)} MXN` : "Precio disponible en tu tienda"}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{product.description || "Una pieza seleccionada de tu catálogo POS."}</p><div className="mt-4 grid gap-2 text-[11px] text-slate-400"><span>✓ Envío a todo México</span><span>✓ Pagos seguros</span><span>✓ Producto original</span></div><Link href={`/comu/products/${encodeURIComponent(listing.public_slug)}`} className="mt-4 block rounded-xl bg-emerald-300 px-3 py-2.5 text-center text-xs font-black text-[#06100b]">Agregar al carrito</Link></div></div> : <div className="mt-5 rounded-2xl border border-dashed border-white/10 px-5 py-10 text-center"><p className="text-sm font-bold text-white">Publica un producto para verlo aquí</p><p className="mt-2 text-xs leading-5 text-slate-500">La vista previa usará el primer producto visible de tu tienda.</p><Link href={`/brand/${encodeURIComponent(brandSlug)}/comu/store`} className="mt-4 inline-flex rounded-xl border border-white/15 px-3 py-2 text-xs font-bold text-slate-300">Administrar tienda</Link></div>}</section>; }
function Thumb({ product }: { product: ProductManagerProduct }) { return <div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-xl border border-white/10 bg-[#14231b] text-xl font-black text-emerald-200">{product.image_url ? <img src={product.image_url} alt="" className="h-full w-full object-cover" /> : product.name.slice(0, 1).toUpperCase()}</div>; }
function EmptyPublished({ href }: { href: string }) { return <div className="rounded-2xl border border-dashed border-white/10 px-5 py-10 text-center"><p className="text-sm font-bold text-white">Aún no hay productos publicados</p><p className="mt-2 text-xs leading-5 text-slate-500">Selecciona productos de tu POS para comenzar a vender en COMU.</p><Link href={href} className="mt-4 inline-flex rounded-xl border border-white/15 px-3 py-2 text-xs font-bold text-slate-300">Revisar mi tienda</Link></div>; }
