"use client";

import { useCallback, useEffect, useState } from "react";
import StorefrontEditor from "./storefront-editor";
import WholesaleProductEditor from "./wholesale-product-editor";
import LogisticsProfile from "./logistics-profile";
import ShippingSettings from "./shipping-settings";

type View = "summary" | "store" | "products" | "wholesale" | "shipping" | "settings";
type Seller = { id: string; slug: string; public_name: string; status: string; verification_status: string; brand_slug: string; comu_storefronts?: { id: string; name: string }[] };
type Product = { id: string; name: string; description?: string | null };
type Listing = { id: string; product_id: string; status: string; public_slug: string };

export default function SellerDashboard({ brandSlug, view = "summary" }: { brandSlug: string; view?: View }) {
  const [sellers, setSellers] = useState<Seller[]>([]); const [sellerId, setSellerId] = useState(""); const [products, setProducts] = useState<Product[]>([]); const [listings, setListings] = useState<Listing[]>([]); const [message, setMessage] = useState("");
  const base = `/brand/${encodeURIComponent(brandSlug)}/comu`;
  const load = useCallback(async () => { const response = await fetch("/api/comu/sellers?mine=1"); const data = await response.json() as { sellers?: Seller[] }; const next = (data.sellers || []).filter((seller) => seller.brand_slug === brandSlug); setSellers(next); const selected = sellerId || next[0]?.id || ""; setSellerId(selected); if (!selected) return; const catalog = await fetch(`/api/comu/catalog?scope=eligible&sellerId=${encodeURIComponent(selected)}`); const catalogData = await catalog.json() as { products?: Product[]; existing?: Listing[] }; setProducts(catalogData.products || []); setListings(catalogData.existing || []); }, [brandSlug, sellerId]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function publish(productId: string) { const seller = sellers.find((item) => item.id === sellerId); const storefrontId = seller?.comu_storefronts?.[0]?.id; if (!seller || !storefrontId) { setMessage("Configura primero tu tienda."); return; } const response = await fetch("/api/comu/listings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, storefrontId, productId }) }); const data = await response.json() as { ok?: boolean; error?: string }; setMessage(data.ok ? "Producto agregado a tu catálogo." : data.error || "No se pudo publicar el producto."); void load(); }
  async function changeStatus(listingId: string, status: string) { const response = await fetch("/api/comu/listings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, listingId, status }) }); const data = await response.json() as { ok?: boolean; error?: string }; setMessage(data.ok ? "Visibilidad actualizada." : data.error || "No se pudo actualizar."); void load(); }
  async function uploadMedia(listingId: string, file: File) { const form = new FormData(); form.set("sellerId", sellerId); form.set("listingId", listingId); form.set("file", file); const response = await fetch("/api/comu/media", { method: "POST", body: form }); const data = await response.json() as { ok?: boolean; error?: string }; setMessage(data.ok ? "Imagen actualizada." : data.error || "No se pudo cargar la imagen."); }
  const seller = sellers.find((item) => item.id === sellerId); const storefrontId = seller?.comu_storefronts?.[0]?.id || "";
  if (!sellerId || !seller) return <p className="rounded-2xl border border-white/10 bg-white/[.04] p-5 text-sm text-slate-300">Cargando tu tienda…</p>;
  if (view === "store") return <section className="max-w-4xl"><PageIntro title="Mi tienda" copy="Así te ven tus compradores." /><StorefrontEditor sellerId={sellerId} /><div className="mt-4 flex flex-wrap gap-3"><a href={`/comu/sellers/${seller.slug}`} className="rounded-full bg-emerald-300 px-5 py-3 text-sm font-black text-[#07100d]">Ver tienda pública</a></div></section>;
  if (view === "shipping") return <section className="max-w-5xl"><PageIntro title="Envíos" copy="Configura cómo quieres manejar tus envíos. COMU calcula las opciones de entrega con nuestros aliados logísticos y muestra al comprador únicamente el costo que le corresponde." /><ShippingSettings sellerId={sellerId} storefrontId={storefrontId} /></section>;
  if (view === "wholesale") return <section><PageIntro title="Mayoreo" copy="Configura las reglas de venta al por mayor de tu tienda y de tus productos publicados." /><div className="grid gap-4 lg:grid-cols-2">{listings.map((listing) => <article key={listing.id} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="font-bold text-white">{listing.public_slug}</p><WholesaleProductEditor sellerId={sellerId} listingId={listing.id} productId={listing.product_id} /></article>)}{!listings.length ? <Empty text="Publica un producto para configurar mayoreo." /> : null}</div></section>;
  if (view === "products") return <section><PageIntro title="Productos" copy="Publica y organiza los productos que ya tienes en tu POS." /><ProductLists products={products} listings={listings} publish={publish} changeStatus={changeStatus} uploadMedia={uploadMedia} sellerId={sellerId} /></section>;
  if (view === "settings") return <section className="max-w-3xl"><PageIntro title="Configuración" copy="Revisa el estado de tu tienda COMU y sus conexiones operativas." /><div className="grid gap-4 sm:grid-cols-2"><Info label="Estado de la tienda" value={seller.status === "ACTIVE" ? "Activa" : seller.status} /><Info label="Verificación" value={seller.verification_status === "VERIFIED" ? "Verificada" : seller.verification_status} /><Info label="Inventario" value="Conectado al POS" /><Info label="Publicaciones" value={`${listings.length} producto${listings.length === 1 ? "" : "s"}`} /></div></section>;
  return <section><PageIntro title="Resumen" copy="La operación de tu tienda COMU, en un solo lugar." />{message ? <p className="mb-5 rounded-xl border border-emerald-300/20 bg-emerald-300/10 p-4 text-sm font-semibold text-emerald-100">{message}</p> : null}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Estado de la tienda" value="Activa" /><Info label="Productos publicados" value={String(listings.length)} /><Info label="Menudeo" value="Activo" /><Info label="Mayoreo" value={listings.some((item) => item.status === "PUBLISHED") ? "Disponible" : "Pendiente"} /></div><div className="mt-6 flex flex-wrap gap-3"><a href={`/comu/sellers/${seller.slug}`} className="rounded-full bg-emerald-300 px-5 py-3 text-sm font-black text-[#07100d]">Ver tienda pública</a><a href={`${base}/products`} className="rounded-full border border-white/15 px-5 py-3 text-sm font-bold text-white">Agregar productos</a><a href={`${base}/orders`} className="rounded-full border border-white/15 px-5 py-3 text-sm font-bold text-white">Ver pedidos</a></div></section>;
}
function PageIntro({ title, copy }: { title: string; copy: string }) { return <header className="mb-6"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">COMU seller</p><h1 className="mt-2 text-3xl font-black tracking-[-.05em] text-white sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{copy}</p></header>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-3 text-2xl font-black text-white">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-white/15 p-6 text-sm text-slate-400">{text}</p>; }
function ProductLists({ products, listings, publish, changeStatus, uploadMedia, sellerId }: { products: Product[]; listings: Listing[]; publish: (id: string) => Promise<void>; changeStatus: (id: string, status: string) => Promise<void>; uploadMedia: (id: string, file: File) => Promise<void>; sellerId: string }) { return <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><h2 className="text-xl font-black">Productos disponibles</h2><div className="mt-4 space-y-2">{products.map((product) => <div key={product.id} className="flex items-center justify-between gap-3 rounded-xl bg-[#101d18] p-4"><span className="font-semibold">{product.name}</span><button onClick={() => void publish(product.id)} className="rounded-full bg-emerald-300 px-4 py-2 text-xs font-black text-[#07100d]">Publicar</button></div>)}{!products.length ? <Empty text="No hay productos POS elegibles." /> : null}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><h2 className="text-xl font-black">Productos publicados</h2><div className="mt-4 space-y-3">{listings.map((listing) => <article key={listing.id} className="rounded-xl bg-[#101d18] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{listing.public_slug}</p><p className="text-xs text-slate-400">{listing.status === "PUBLISHED" ? "Publicado" : "Oculto"}</p></div><div className="flex gap-2"><label className="cursor-pointer rounded-full border border-white/15 px-3 py-2 text-xs font-bold">Imagen<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadMedia(listing.id, file); }} /></label><button onClick={() => void changeStatus(listing.id, listing.status === "PUBLISHED" ? "HIDDEN" : "PUBLISHED")} className="rounded-full border border-white/15 px-3 py-2 text-xs font-bold">{listing.status === "PUBLISHED" ? "Ocultar" : "Publicar"}</button></div></div><LogisticsProfile sellerId={sellerId} productId={listing.product_id} /></article>)}{!listings.length ? <Empty text="Aún no hay productos publicados." /> : null}</div></div></div>; }