"use client";
import { useEffect, useState } from "react";

type Policy = { mode: "RETAIL" | "WHOLESALE"; buyer_pays_percent: number; free_shipping_threshold: number | null; seller_subsidy_percent: number; seller_max_subsidy: number | null };
export default function ShippingSettings({ sellerId, storefrontId }: { sellerId: string; storefrontId: string }) {
  const [policies, setPolicies] = useState<Policy[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!sellerId || !storefrontId) return; void fetch(`/api/comu/shipping/policy?sellerId=${encodeURIComponent(sellerId)}&storefrontId=${encodeURIComponent(storefrontId)}`).then(r => r.json()).then((d: { policies?: Policy[] }) => setPolicies(d.policies || [])); }, [sellerId, storefrontId]);
  function value(mode: Policy["mode"]): Policy { return policies.find(p => p.mode === mode) || { mode, buyer_pays_percent: 100, free_shipping_threshold: null, seller_subsidy_percent: 0, seller_max_subsidy: null }; }
  function update(mode: Policy["mode"], key: keyof Policy, next: number | null) { setPolicies(current => [...current.filter(p => p.mode !== mode), { ...value(mode), [key]: next }]); }
  async function save(mode: Policy["mode"]) { const p = value(mode); if ([p.buyer_pays_percent, p.seller_subsidy_percent].some(n => n < 0 || n > 100) || (p.free_shipping_threshold != null && p.free_shipping_threshold < 0) || (p.seller_max_subsidy != null && p.seller_max_subsidy < 0)) { setMessage("Revisa los valores de la política."); return; } setBusy(true); const response = await fetch("/api/comu/shipping/policy", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, storefrontId, mode, buyerPaysPercent: p.buyer_pays_percent, freeShippingThreshold: p.free_shipping_threshold, sellerSubsidyPercent: p.seller_subsidy_percent, sellerMaxSubsidy: p.seller_max_subsidy }) }); setMessage(response.ok ? `${mode === "RETAIL" ? "Menudeo" : "Mayoreo"} guardado.` : "No se pudo guardar la política."); setBusy(false); }
  if (!storefrontId) return null;
  return <section className="mt-6 rounded-3xl border border-black/5 bg-slate-50 p-5"><h2 className="text-xl font-black">Envíos</h2><p className="mt-1 text-sm text-slate-600">Configura quién absorbe el envío. El comprador sólo verá su cargo final.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{(["RETAIL", "WHOLESALE"] as const).map(mode => { const p = value(mode); return <div key={mode} className="rounded-2xl bg-white p-4"><h3 className="font-black">{mode === "RETAIL" ? "Menudeo" : "Mayoreo"}</h3><label className="mt-3 block text-xs font-bold">Paga comprador (%)<input type="number" min="0" max="100" value={p.buyer_pays_percent} onChange={e => update(mode, "buyer_pays_percent", Number(e.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><label className="mt-3 block text-xs font-bold">Subsidio tienda (%)<input type="number" min="0" max="100" value={p.seller_subsidy_percent} onChange={e => update(mode, "seller_subsidy_percent", Number(e.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><label className="mt-3 block text-xs font-bold">Envío gratis desde (opcional)<input type="number" min="0" value={p.free_shipping_threshold ?? ""} onChange={e => update(mode, "free_shipping_threshold", e.target.value === "" ? null : Number(e.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><label className="mt-3 block text-xs font-bold">Subsidio máximo (opcional)<input type="number" min="0" value={p.seller_max_subsidy ?? ""} onChange={e => update(mode, "seller_max_subsidy", e.target.value === "" ? null : Number(e.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><button type="button" disabled={busy} onClick={() => void save(mode)} className="mt-4 rounded-full bg-[#17201d] px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Guardar {mode === "RETAIL" ? "menudeo" : "mayoreo"}</button></div>; })}</div>{message ? <p className="mt-4 text-sm font-semibold text-emerald-700">{message}</p> : null}</section>;
}
