"use client";

import { useEffect, useState } from "react";

type Policy = { mode: "RETAIL" | "WHOLESALE"; buyer_pays_percent: number; free_shipping_threshold: number | null; seller_subsidy_percent: number; seller_max_subsidy: number | null };

export default function ShippingSettings({ sellerId, storefrontId }: { sellerId: string; storefrontId: string }) {
  const [policies, setPolicies] = useState<Policy[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!sellerId || !storefrontId) return; void fetch(`/api/comu/shipping/policy?sellerId=${encodeURIComponent(sellerId)}&storefrontId=${encodeURIComponent(storefrontId)}`).then((response) => response.json()).then((data: { policies?: Policy[] }) => setPolicies(data.policies || [])); }, [sellerId, storefrontId]);
  function value(mode: Policy["mode"]): Policy { return policies.find((policy) => policy.mode === mode) || { mode, buyer_pays_percent: mode === "WHOLESALE" ? 50 : 100, free_shipping_threshold: null, seller_subsidy_percent: mode === "WHOLESALE" ? 50 : 0, seller_max_subsidy: null }; }
  function update(mode: Policy["mode"], key: keyof Policy, next: number | null) { setPolicies((current) => [...current.filter((policy) => policy.mode !== mode), { ...value(mode), [key]: next }]); }
  async function save(mode: Policy["mode"]) { const policy = value(mode); if ([policy.buyer_pays_percent, policy.seller_subsidy_percent].some((number) => number < 0 || number > 100) || (policy.free_shipping_threshold != null && policy.free_shipping_threshold < 0) || (policy.seller_max_subsidy != null && policy.seller_max_subsidy < 0) || policy.buyer_pays_percent + policy.seller_subsidy_percent === 0) { setMessage("Elige quién cubre el envío o define un umbral de envío gratis."); return; } setBusy(true); const response = await fetch("/api/comu/shipping/policy", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, storefrontId, mode, buyerPaysPercent: policy.buyer_pays_percent, freeShippingThreshold: policy.free_shipping_threshold, sellerSubsidyPercent: policy.seller_subsidy_percent, sellerMaxSubsidy: policy.seller_max_subsidy }) }); setMessage(response.ok ? `${mode === "RETAIL" ? "Menudeo" : "Mayoreo"} guardado.` : "No se pudo guardar la política."); setBusy(false); }
  if (!storefrontId) return null;
  return <section className="mt-6 rounded-3xl border border-black/5 bg-slate-50 p-5"><h2 className="text-xl font-black">Envíos</h2><p className="mt-1 text-sm text-slate-600">Configura cómo quieres manejar tus envíos. COMU calcula las opciones de entrega y muestra al comprador sólo el costo que le corresponde.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{(["RETAIL", "WHOLESALE"] as const).map((mode) => { const policy = value(mode); return <div key={mode} className="rounded-2xl bg-white p-4"><h3 className="font-black">{mode === "RETAIL" ? "Menudeo" : "Mayoreo"}</h3><p className="mt-1 text-xs text-slate-500">{mode === "RETAIL" ? "El comprador paga o tu tienda ofrece envío gratis desde un umbral." : "Elige si compartes el costo con tus compradores."}</p><label className="mt-3 block text-xs font-bold">Paga comprador (%)<input type="number" min="0" max="100" value={policy.buyer_pays_percent} onChange={(event) => update(mode, "buyer_pays_percent", Number(event.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><label className="mt-3 block text-xs font-bold">Mi tienda cubre (%)<input type="number" min="0" max="100" value={policy.seller_subsidy_percent} onChange={(event) => update(mode, "seller_subsidy_percent", Number(event.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><label className="mt-3 block text-xs font-bold">Envío gratis desde (opcional)<input type="number" min="0" value={policy.free_shipping_threshold ?? ""} onChange={(event) => update(mode, "free_shipping_threshold", event.target.value === "" ? null : Number(event.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><label className="mt-3 block text-xs font-bold">Subsidio máximo (opcional)<input type="number" min="0" value={policy.seller_max_subsidy ?? ""} onChange={(event) => update(mode, "seller_max_subsidy", event.target.value === "" ? null : Number(event.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><button type="button" disabled={busy} onClick={() => void save(mode)} className="mt-4 rounded-full bg-[#17201d] px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Guardar {mode === "RETAIL" ? "menudeo" : "mayoreo"}</button></div>; })}</div>{message ? <p className="mt-4 text-sm font-semibold text-emerald-700">{message}</p> : null}</section>;
}
