"use client";
import { useEffect, useState, type FormEvent } from "react";

export default function StorefrontEditor({ sellerId }: { sellerId: string }) {
  const [name, setName] = useState(""); const [headline, setHeadline] = useState(""); const [description, setDescription] = useState(""); const [storefrontId, setStorefrontId] = useState(""); const [wholesale, setWholesale] = useState(false); const [minimum, setMinimum] = useState(6); const [mix, setMix] = useState(false); const [discount, setDiscount] = useState(20); const [message, setMessage] = useState("");
  useEffect(() => { if (!sellerId) return; void fetch(`/api/comu/storefronts?sellerId=${encodeURIComponent(sellerId)}`).then((response) => response.json()).then(async (data: { storefront?: { id?: string; name?: string; headline?: string; description?: string } }) => { setStorefrontId(data.storefront?.id || ""); setName(data.storefront?.name || ""); setHeadline(data.storefront?.headline || ""); setDescription(data.storefront?.description || ""); if (data.storefront?.id) { const pricing = await fetch(`/api/comu/wholesale?sellerId=${encodeURIComponent(sellerId)}&storefrontId=${encodeURIComponent(data.storefront.id)}`).then((response) => response.json()) as { policy?: { enabled?: boolean; minimum_quantity?: number; allow_product_mix?: boolean }; tiers?: Array<{ value?: number }> }; setWholesale(Boolean(pricing.policy?.enabled)); setMinimum(Number(pricing.policy?.minimum_quantity || 6)); setMix(Boolean(pricing.policy?.allow_product_mix)); setDiscount(Number(pricing.tiers?.[0]?.value || 20)); } }); }, [sellerId]);
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/comu/storefronts", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, name, headline, description }) }); if (storefrontId) await fetch("/api/comu/wholesale", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, storefrontId, enabled: wholesale, minimumQuantity: minimum, allowProductMix: mix, allowVariantMix: true, tiers: [{ minQuantity: minimum, pricingMode: "AMOUNT_OFF", value: discount }] }) }); const data = await response.json() as { ok?: boolean; error?: string }; setMessage(data.ok ? "Storefront y mayoreo actualizados." : data.error || "No se pudo actualizar."); }
  if (!sellerId) return null;
  return <form onSubmit={save} className="mt-8 rounded-3xl bg-white p-6"><h2 className="text-xl font-black">Storefront</h2><div className="mt-4 grid gap-3"><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Nombre público" className="min-h-12 rounded-xl border border-black/10 px-4" /><input value={headline} onChange={(event) => setHeadline(event.target.value)} placeholder="Headline" className="min-h-12 rounded-xl border border-black/10 px-4" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Descripción" className="min-h-24 rounded-xl border border-black/10 p-4" /><fieldset className="rounded-2xl border border-black/10 p-4"><legend className="px-2 text-sm font-black">Mayoreo</legend><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={wholesale} onChange={(event) => setWholesale(event.target.checked)} /> Activar mayoreo</label>{wholesale ? <div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-xs font-bold">Mínimo<input type="number" min="1" value={minimum} onChange={(event) => setMinimum(Number(event.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><label className="text-xs font-bold">Descuento por pieza<input type="number" min="0" value={discount} onChange={(event) => setDiscount(Number(event.target.value))} className="mt-1 h-10 w-full rounded-lg border px-2" /></label><label className="flex items-center gap-2 pt-5 text-xs"><input type="checkbox" checked={mix} onChange={(event) => setMix(event.target.checked)} /> Combinar productos</label></div> : null}</fieldset><button className="w-fit rounded-full bg-[#17201d] px-5 py-3 text-sm font-bold text-white">Guardar storefront</button>{message ? <p className="text-sm text-emerald-700">{message}</p> : null}</div></form>;
}
