"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";

type Theme = { whatsapp?: string | null; address?: string | null; showLocation?: boolean; accentColor?: string | null };
type Storefront = { id?: string; slug?: string; name?: string; headline?: string; description?: string; logo_url?: string | null; cover_url?: string | null; theme_config?: Theme; comu_sellers?: { city?: string | null; status?: string; verification_status?: string } };
type StorefrontEditorProps = { sellerId: string; brandSlug: string; sellerSlug: string; verified: boolean; listingCount: number };

export default function StorefrontEditor({ sellerId, brandSlug, sellerSlug, verified, listingCount }: StorefrontEditorProps) {
  const [storefront, setStorefront] = useState<Storefront | null>(null);
  const [name, setName] = useState(""); const [headline, setHeadline] = useState(""); const [description, setDescription] = useState(""); const [whatsapp, setWhatsapp] = useState(""); const [city, setCity] = useState(""); const [address, setAddress] = useState(""); const [showLocation, setShowLocation] = useState(true);
  const [accentColor, setAccentColor] = useState("#8DFFBF"); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState<"logo" | "banner" | null>(null); const [message, setMessage] = useState(""); const [saveError, setSaveError] = useState(false); const [wholesaleEnabled, setWholesaleEnabled] = useState(false);

  useEffect(() => {
    if (!sellerId) return;
    void fetch(`/api/comu/storefronts?sellerId=${encodeURIComponent(sellerId)}`).then((response) => response.json()).then(async (data: { storefront?: Storefront }) => {
      const next = data.storefront || {};
      setStorefront(next); setName(next.name || ""); setHeadline(next.headline || ""); setDescription(next.description || ""); setWhatsapp(next.theme_config?.whatsapp || ""); setAddress(next.theme_config?.address || ""); setShowLocation(next.theme_config?.showLocation !== false); setAccentColor(validHex(next.theme_config?.accentColor) ? next.theme_config?.accentColor || "#8DFFBF" : "#8DFFBF"); setCity(next.comu_sellers?.city || "");
      if (next.id) { const wholesale = await fetch(`/api/comu/wholesale?sellerId=${encodeURIComponent(sellerId)}&storefrontId=${encodeURIComponent(next.id)}`); const wholesaleData = await wholesale.json() as { policy?: { enabled?: boolean } | null }; setWholesaleEnabled(wholesaleData.policy?.enabled === true); }
    }).catch(() => { setMessage("No se pudo cargar la información de tu tienda."); setSaveError(true); });
  }, [sellerId]);

  async function save(event: FormEvent) {
    event.preventDefault(); setSaving(true); setMessage(""); setSaveError(false);
    const response = await fetch("/api/comu/storefronts", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, name, headline, description, whatsapp, city, address, showLocation, theme: { accentColor }, logoUrl: storefront?.logo_url || undefined, coverUrl: storefront?.cover_url || undefined }) });
    const data = await response.json() as { ok?: boolean; storefront?: Storefront; error?: string };
    if (data.ok) { setStorefront((current) => ({ ...current, ...(data.storefront || {}), name, headline, description, theme_config: { ...current?.theme_config, whatsapp, address, showLocation, accentColor } })); setMessage("Cambios guardados."); } else { setSaveError(true); setMessage(data.error || "No se pudo actualizar la tienda."); }
    setSaving(false);
  }

  async function uploadAsset(kind: "logo" | "banner", file: File) {
    if (file.size > 5 * 1024 * 1024 || !["image/jpeg", "image/png", "image/webp"].includes(file.type)) { setSaveError(true); setMessage("Usa JPG, PNG o WEBP de máximo 5 MB."); return; }
    const localUrl = URL.createObjectURL(file); setStorefront((current) => ({ ...current, [kind === "logo" ? "logo_url" : "cover_url"]: localUrl })); setUploading(kind); setMessage(""); setSaveError(false);
    const form = new FormData(); form.set("sellerId", sellerId); form.set("kind", kind); form.set("file", file);
    const response = await fetch("/api/comu/storefronts/assets", { method: "POST", body: form }); const data = await response.json() as { ok?: boolean; url?: string; error?: string };
    URL.revokeObjectURL(localUrl); if (data.ok && data.url) { setStorefront((current) => ({ ...current, [kind === "logo" ? "logo_url" : "cover_url"]: data.url })); setMessage(kind === "logo" ? "Foto actualizada." : "Banner actualizado."); } else { setSaveError(true); setMessage(data.error || "No se pudo subir la imagen."); }
    setUploading(null);
  }

  const publicSlug = storefront?.slug || sellerSlug;
  const publicUrl = `/comu/sellers/${encodeURIComponent(publicSlug)}`;
  const profileReady = Boolean(name.trim() && (description.trim() || headline.trim()) && listingCount > 0);
  const modes = wholesaleEnabled ? ["Menudeo", "Mayoreo"] : ["Menudeo"];
  const initial = (name.trim() || "Tienda").charAt(0).toUpperCase();
  const coverStyle = storefront?.cover_url ? { backgroundImage: `url(${storefront.cover_url})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined;
  const locationStatus = showLocation && (city.trim() || address.trim()) ? "Configurada" : "No configurada";
  const whatsappStatus = whatsapp.trim() ? "Configurado" : "No configurado";
  const helper = useMemo(() => profileReady ? "Tu perfil tiene la información esencial para recibir compradores." : "Agrega una descripción y publica al menos un producto para completar tu perfil.", [profileReady]);

  if (!sellerId) return null;
  return <section>
    <header className="mb-8"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">COMU SELLER</p><h1 className="mt-3 text-4xl font-black tracking-[-.055em] text-white sm:text-5xl">Mi tienda</h1><p className="mt-3 max-w-2xl text-base leading-7 text-slate-400">Así te ven tus compradores.</p></header>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.8fr)]">
      <div className="space-y-5">
        <form onSubmit={save} className="rounded-[1.5rem] border border-white/10 bg-white/[.035] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,.03)] sm:p-7"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Tu identidad</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em] text-white">Así te ven tus compradores</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-400">Completa la información de tu tienda para generar confianza y atraer más clientes.</p></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Nombre público" count={`${name.length} / 50`}><input required maxLength={50} value={name} onChange={(event) => setName(event.target.value)} className={inputClass} /></Field><Field label="Frase corta" count={`${headline.length} / 100`}><input maxLength={100} value={headline} onChange={(event) => setHeadline(event.target.value)} placeholder="Una idea clara sobre tu tienda" className={inputClass} /></Field><Field label="Descripción" count={`${description.length} / 500`} wide><textarea maxLength={500} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Cuéntales qué hace especial a tu tienda" className={`${inputClass} min-h-32 py-3`} /></Field><Field label="WhatsApp público (opcional)"><input value={whatsapp} onChange={(event) => setWhatsapp(event.target.value)} placeholder="Ej. 55 1234 5678" className={inputClass} /></Field><Field label="Ciudad"><input value={city} onChange={(event) => setCity(event.target.value)} placeholder="Ej. Moroleón, Guanajuato" className={inputClass} /></Field><Field label="Dirección (opcional)" wide><input value={address} onChange={(event) => setAddress(event.target.value)} placeholder="Ej. Av. principal 123, Centro" className={inputClass} /></Field></div><label className="mt-6 flex cursor-pointer items-start gap-3 rounded-2xl border border-white/[.08] bg-[#0a1510] p-4"><input type="checkbox" checked={showLocation} onChange={(event) => setShowLocation(event.target.checked)} className="mt-1 h-4 w-4 accent-emerald-300" /><span><span className="block text-sm font-bold text-white">Mostrar ubicación en COMU</span><span className="mt-1 block text-xs leading-5 text-slate-500">Tu ciudad y dirección serán visibles en tu tienda pública.</span></span></label><div className="mt-7 flex flex-wrap items-center gap-3"><button type="submit" disabled={saving} className="rounded-xl bg-emerald-300 px-5 py-3 text-sm font-black text-[#06100b] shadow-[0_0_25px_rgba(110,255,187,.12)] transition hover:bg-emerald-200 disabled:cursor-wait disabled:opacity-60">{saving ? "Guardando…" : "Guardar cambios"}</button>{message ? <p className={`text-sm font-semibold ${saveError ? "text-red-200" : "text-emerald-200"}`}>{message}</p> : null}</div></form>
        <VisualIdentity logoUrl={storefront?.logo_url} coverUrl={storefront?.cover_url} accentColor={accentColor} uploading={uploading} onAccentChange={setAccentColor} onUpload={uploadAsset} />
      </div>
      <aside className="space-y-5">
        <section className="overflow-hidden rounded-[1.5rem] border border-white/10 bg-white/[.035] shadow-[inset_0_1px_0_rgba(255,255,255,.03)]"><div className="p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Vista previa</p><h2 className="mt-2 text-xl font-black text-white">Así se verá tu tienda</h2><p className="mt-1 text-sm leading-6 text-slate-400">Así se verá tu tienda para los compradores en COMU.</p></div><div className="mx-5 overflow-hidden rounded-2xl border border-white/10 bg-[#0a1510]"><div className="relative h-28 overflow-hidden bg-[radial-gradient(circle_at_80%_10%,rgba(110,255,187,.32),transparent_38%),linear-gradient(135deg,#153b2a,#07110d)]" style={coverStyle}><div className="absolute inset-0 bg-gradient-to-t from-[#0a1510] to-transparent" /></div><div className="relative px-4 pb-5"><div className="-mt-8 grid h-16 w-16 place-items-center overflow-hidden rounded-2xl border-4 border-[#0a1510] bg-emerald-300 text-2xl font-black text-[#06100b]">{storefront?.logo_url ? <img src={storefront.logo_url} alt="" className="h-full w-full object-cover" /> : initial}</div><div className="mt-3 flex items-center gap-2"><h3 className="text-lg font-black text-white">{name || "Tu tienda"}</h3>{verified ? <span className="rounded-full border border-emerald-300/20 bg-emerald-300/10 px-2 py-1 text-[10px] font-bold text-emerald-100">Vendedor verificado</span> : null}</div><p className="mt-1 text-sm text-emerald-100">{headline || "Una idea clara sobre tu tienda"}</p><p className="mt-3 text-sm leading-6 text-slate-400">{description || "Agrega una descripción para contarle a tus compradores quién eres."}</p>{showLocation && city ? <p className="mt-3 text-xs text-slate-500">{city}{address ? ` · ${address}` : ""}</p> : null}<div className="mt-4 flex flex-wrap gap-2">{modes.map((mode) => <span key={mode} className="rounded-full border border-white/10 bg-white/[.06] px-2.5 py-1 text-xs font-semibold text-slate-300">{mode}</span>)}</div></div></div><div className="p-5"><Link href={publicUrl} className="block rounded-xl bg-emerald-300 px-4 py-3 text-center text-sm font-black text-[#06100b] transition hover:bg-emerald-200">Ver tienda pública</Link></div></section>
        <section className="rounded-[1.5rem] border border-white/10 bg-white/[.035] p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Señales de confianza</p><h2 className="mt-2 text-xl font-black text-white">Información pública</h2><p className="mt-1 text-sm leading-6 text-slate-400">Esta es la información que verán tus compradores.</p><div className="mt-5 space-y-3"><StatusRow label="WhatsApp" value={whatsappStatus} /><StatusRow label="Ubicación" value={locationStatus} /><StatusRow label="Modos de venta" value={modes.join(" · ")} /><StatusRow label="Estado" value={profileReady ? "Perfil listo" : "Información pendiente"} /><p className="pt-1 text-xs leading-5 text-slate-500">{helper}</p></div></section>
        <section className="rounded-[1.5rem] border border-white/10 bg-white/[.035] p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Atajos</p><h2 className="mt-2 text-xl font-black text-white">Acciones rápidas</h2><div className="mt-4 space-y-2"><QuickLink href={publicUrl} label="Ver tienda pública" /><QuickLink href={`/brand/${encodeURIComponent(brandSlug)}/comu/products`} label="Ir a productos" /><QuickLink href={`/brand/${encodeURIComponent(brandSlug)}/comu/shipping`} label="Configurar envíos" /></div></section>
      </aside>
    </div>
  </section>;
}

const inputClass = "mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-[#0b1712] px-4 text-sm text-white outline-none placeholder:text-slate-500 focus:border-emerald-300/50 focus:ring-2 focus:ring-emerald-300/10";
function Field({ label, count, wide = false, children }: { label: string; count?: string; wide?: boolean; children: ReactNode }) { return <label className={wide ? "sm:col-span-2" : ""}><span className="flex items-center justify-between text-sm font-bold text-slate-200"><span>{label}</span>{count ? <span className="text-xs font-medium text-slate-500">{count}</span> : null}</span>{children}</label>; }
function VisualIdentity({ logoUrl, coverUrl, accentColor, uploading, onAccentChange, onUpload }: { logoUrl?: string | null; coverUrl?: string | null; accentColor: string; uploading: "logo" | "banner" | null; onAccentChange: (value: string) => void; onUpload: (kind: "logo" | "banner", file: File) => Promise<void> }) { const colors = ["#8DFFBF", "#7CE7C1", "#B5F2D0", "#F0C987", "#C5B8FF"]; return <section className="rounded-[1.5rem] border border-white/10 bg-white/[.035] p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Identidad visual</p><h2 className="mt-2 text-2xl font-black text-white">Haz que tu tienda se reconozca</h2><p className="mt-2 text-sm leading-6 text-slate-400">Personaliza la imagen de tu tienda. Una buena identidad genera más confianza.</p><div className="mt-6 grid gap-3 md:grid-cols-3"><VisualCard title="Foto de tu tienda" preview={logoUrl ? <img src={logoUrl} alt="" className="h-full w-full object-cover" /> : <span className="text-2xl font-black text-emerald-200">N</span>} action={uploading === "logo" ? "Subiendo…" : "Cambiar foto"} onUpload={(file) => onUpload("logo", file)} /><VisualCard title="Banner de portada" preview={coverUrl ? <img src={coverUrl} alt="" className="h-full w-full object-cover" /> : null} action={uploading === "banner" ? "Subiendo…" : "Cambiar banner"} onUpload={(file) => onUpload("banner", file)} wide /><VisualCard title="Colores de tu tienda" preview={<div className="flex gap-1.5">{colors.map((color) => <button type="button" key={color} aria-label={`Seleccionar color ${color}`} onClick={() => onAccentChange(color)} className={`h-6 w-6 rounded-full border-2 ${accentColor === color ? "border-white ring-2 ring-emerald-300/60" : "border-white/20"}`} style={{ backgroundColor: color }} />)}<label className="grid h-6 w-6 cursor-pointer place-items-center rounded-full border border-dashed border-white/25 text-xs text-slate-400">+<input type="color" value={accentColor} onChange={(event) => onAccentChange(event.target.value.toUpperCase())} className="sr-only" /></label></div>} action="Guardar con el perfil" /></div><p className="mt-4 text-xs text-slate-500">Selecciona un color y presiona Guardar cambios para aplicarlo a tu tienda pública.</p></section>; }
function VisualCard({ title, preview, action, wide = false, onUpload }: { title: string; preview: ReactNode; action: string; wide?: boolean; onUpload?: (file: File) => void }) { return <div className={`${wide ? "md:col-span-1" : ""} rounded-2xl border border-white/[.08] bg-[#0a1510] p-3`}><div className="grid h-20 place-items-center overflow-hidden rounded-xl bg-[radial-gradient(circle_at_80%_10%,rgba(110,255,187,.2),transparent_45%),#12251b]">{preview || <span className="text-xs font-semibold text-slate-500">Sin portada</span>}</div><p className="mt-3 text-sm font-bold text-white">{title}</p>{onUpload ? <label className="mt-2 inline-flex cursor-pointer text-xs font-bold text-emerald-200">{action}<input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) onUpload(file); event.currentTarget.value = ""; }} /></label> : <span className="mt-2 block text-xs font-bold text-slate-500">{action}</span>}</div>; }
function StatusRow({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-3 border-b border-white/[.06] pb-3 text-sm"><span className="text-slate-400">{label}</span><span className="font-bold text-slate-200">{value}</span></div>; }
function QuickLink({ href, label }: { href: string; label: string }) { return <Link href={href} className="flex items-center justify-between rounded-xl border border-white/[.07] bg-[#0a1510] px-3.5 py-3 text-sm font-bold text-slate-200 transition hover:border-emerald-300/30 hover:text-emerald-100"><span>{label}</span><span className="text-emerald-200">→</span></Link>; }
function validHex(value?: string | null): value is string { return typeof value === "string" && /^#[0-9A-Fa-f]{6}$/.test(value); }
