"use client";

import { useEffect, useState, type FormEvent } from "react";
type Theme = { whatsapp?: string; address?: string; showLocation?: boolean };
type Storefront = { id?: string; name?: string; headline?: string; description?: string; theme_config?: Theme; comu_sellers?: { city?: string } };

export default function StorefrontEditor({ sellerId }: { sellerId: string }) {
  const [name, setName] = useState(""); const [headline, setHeadline] = useState(""); const [description, setDescription] = useState(""); const [whatsapp, setWhatsapp] = useState(""); const [city, setCity] = useState(""); const [address, setAddress] = useState(""); const [showLocation, setShowLocation] = useState(true); const [message, setMessage] = useState("");
  useEffect(() => { if (!sellerId) return; void fetch(`/api/comu/storefronts?sellerId=${encodeURIComponent(sellerId)}`).then((response) => response.json()).then((data: { storefront?: Storefront }) => { const next = data.storefront || {}; setName(next.name || ""); setHeadline(next.headline || ""); setDescription(next.description || ""); setWhatsapp(next.theme_config?.whatsapp || ""); setAddress(next.theme_config?.address || ""); setShowLocation(next.theme_config?.showLocation !== false); setCity(next.comu_sellers?.city || ""); }); }, [sellerId]);
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/comu/storefronts", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, name, headline, description, whatsapp, city, address, showLocation }) }); const data = await response.json() as { ok?: boolean; error?: string }; setMessage(data.ok ? "Cambios guardados." : data.error || "No se pudo actualizar la tienda."); }
  if (!sellerId) return null;
  const field = "mt-2 min-h-11 w-full rounded-xl border border-white/15 bg-[#101d18] px-4 text-sm text-white outline-none placeholder:text-slate-500 focus:border-emerald-300/70 focus:ring-2 focus:ring-emerald-300/20";
  return <form onSubmit={save} className="rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><h2 className="text-xl font-black text-white">Así te ven tus compradores</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-300">Nombre público<input required value={name} onChange={(event) => setName(event.target.value)} className={field} /></label><label className="text-sm font-semibold text-slate-300">Frase corta<input value={headline} onChange={(event) => setHeadline(event.target.value)} placeholder="Una idea clara sobre tu tienda" className={field} /></label><label className="text-sm font-semibold text-slate-300 sm:col-span-2">Descripción<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Cuéntales qué haces" className={`${field} min-h-28 py-3`} /></label><label className="text-sm font-semibold text-slate-300">WhatsApp público (opcional)<input value={whatsapp} onChange={(event) => setWhatsapp(event.target.value)} className={field} /></label><label className="text-sm font-semibold text-slate-300">Ciudad<input value={city} onChange={(event) => setCity(event.target.value)} className={field} /></label><label className="text-sm font-semibold text-slate-300 sm:col-span-2">Dirección (opcional)<input value={address} onChange={(event) => setAddress(event.target.value)} className={field} /></label><label className="flex items-center gap-3 text-sm font-semibold text-slate-300 sm:col-span-2"><input type="checkbox" checked={showLocation} onChange={(event) => setShowLocation(event.target.checked)} className="h-4 w-4 accent-emerald-300" /> Mostrar ubicación en COMU</label></div><div className="mt-6 flex flex-wrap items-center gap-3"><button className="rounded-full bg-emerald-300 px-5 py-3 text-sm font-black text-[#07100d]">Guardar cambios</button>{message ? <p className="text-sm font-semibold text-emerald-200">{message}</p> : null}</div></form>;
}