"use client";
import { useEffect, useMemo, useState } from "react";

type Variant = { id: string; name?: string | null; variant_id?: string; product_id?: string };
type Saved = { comu_product_run_items?: Array<{ variant_listing_id: string; quantity_per_run: number }> } | null;

export default function WholesaleProductEditor({ sellerId, listingId, productId }: { sellerId: string; listingId: string; productId: string }) {
  const [mode, setMode] = useState("STORE"); const [run, setRun] = useState(false); const [variants, setVariants] = useState<Variant[]>([]); const [quantities, setQuantities] = useState<Record<string, number>>({}); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let alive = true; void fetch(`/api/comu/wholesale/product?sellerId=${encodeURIComponent(sellerId)}&listingId=${encodeURIComponent(listingId)}`).then((response) => response.json()).then((saved: { variants?: Variant[]; override?: { mode?: string; allow_run?: boolean }; run?: Saved }) => { if (!alive) return; setVariants(saved.variants || []); setMode(saved.override?.mode || "STORE"); setRun(Boolean(saved.override?.allow_run)); const map: Record<string, number> = {}; for (const item of saved.run?.comu_product_run_items || []) map[item.variant_listing_id] = Number(item.quantity_per_run); setQuantities(map); }); return () => { alive = false; }; }, [sellerId, listingId, productId]);
  const total = useMemo(() => variants.reduce((sum, variant) => sum + Number(quantities[variant.id] || 0), 0), [quantities, variants]);
  async function save() { if (run && total <= 0) { setMessage("Agrega al menos una variante a la corrida."); return; } setBusy(true); const response = await fetch("/api/comu/wholesale/product", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sellerId, listingId, mode, allowPieces: true, allowVariantMix: true, allowRun: run, corridaEnabled: run, runItems: run ? variants.filter((variant) => Number(quantities[variant.id] || 0) > 0).map((variant) => ({ variantListingId: variant.id, quantityPerRun: Number(quantities[variant.id]) })) : [] }) }); const data = await response.json() as { ok?: boolean; error?: string }; setMessage(data.ok ? "Mayoreo y corrida guardados." : data.error || "No se pudo guardar."); setBusy(false); }
  return <div className="mt-3 rounded-xl border border-white/10 bg-[#0d1a15] p-3"><p className="text-[10px] font-black uppercase tracking-[.16em]">Mayoreo</p><div className="mt-2 flex flex-wrap items-center gap-2"><select aria-label="Configuración de mayoreo" value={mode} onChange={(event) => setMode(event.target.value)} className="rounded-lg border border-white/15 bg-[#101d18] px-2 py-1 text-xs"><option value="STORE">Usar configuración de mi tienda</option><option value="CUSTOM">Configuración personalizada</option><option value="DISABLED">Desactivado</option></select><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={run} onChange={(event) => setRun(event.target.checked)} /> Permitir corrida</label></div>{run ? <div className="mt-3 rounded-lg bg-white p-3"><p className="text-xs font-black">Composición de corrida</p><div className="mt-2 space-y-2">{variants.map((variant) => <label key={variant.id} className="flex items-center justify-between gap-2 text-xs"><span>{variant.name || "Variante"}</span><span className="flex items-center gap-1"><button type="button" disabled={busy} onClick={() => setQuantities((current) => ({ ...current, [variant.id]: Math.max(0, Number(current[variant.id] || 0) - 1) }))} className="h-7 w-7 rounded border border-white/15 bg-[#101d18] text-white">−</button><input aria-label={`Cantidad ${variant.name || "variante"}`} type="number" min="0" value={quantities[variant.id] || 0} disabled={busy} onChange={(event) => setQuantities((current) => ({ ...current, [variant.id]: Math.max(0, Number(event.target.value) || 0) }))} className="h-7 w-12 rounded border border-white/15 bg-[#101d18] text-center text-white" /><button type="button" disabled={busy} onClick={() => setQuantities((current) => ({ ...current, [variant.id]: Number(current[variant.id] || 0) + 1 }))} className="h-7 w-7 rounded border border-white/15 bg-[#101d18] text-white">+</button></span></label>)}</div><p className="mt-2 text-xs font-semibold">Total: {total} piezas por corrida</p><p className="mt-1 text-xs text-slate-400">Cada corrida incluye {variants.filter((variant) => Number(quantities[variant.id] || 0) > 0).map((variant) => `${quantities[variant.id]} ${variant.name || "variante"}`).join(" · ") || "ninguna variante"}.</p></div> : null}<button disabled={busy} onClick={() => void save()} className="mt-2 rounded-full bg-emerald-300 px-3 py-1 text-xs font-bold text-[#07100d] disabled:opacity-50">{busy ? "Guardando…" : "Guardar"}</button>{message ? <p className="mt-2 text-xs text-emerald-200">{message}</p> : null}</div>;
}
